/*
Harmony SASE Public API

Testing EnhancedRegionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perimeter81-Public/perimeter-81-client-sdk"
)

func Test_perimeter81sdk_EnhancedRegionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EnhancedRegionsAPIService CreateEnhancedRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.CreateEnhancedRegion(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService DeleteEnhancedRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var regionId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.DeleteEnhancedRegion(context.Background(), networkId, regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService EnhancedNetworksControllerV2GetRegions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.EnhancedNetworksControllerV2GetRegions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService GetEnhancedRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var regionId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.GetEnhancedRegion(context.Background(), networkId, regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService IncreaseScaleUnit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var regionId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.IncreaseScaleUnit(context.Background(), networkId, regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService ListEnhancedRegions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.ListEnhancedRegions(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRegionsAPIService ReduceScaleUnit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var regionId string

		resp, httpRes, err := apiClient.EnhancedRegionsAPI.ReduceScaleUnit(context.Background(), networkId, regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
