/*
Harmony SASE Public API

Testing EnhancedRouteTablesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perimeter81-Public/perimeter-81-client-sdk/v2"
)

func Test_perimeter81sdk_EnhancedRouteTablesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EnhancedRouteTablesAPIService CreateDynamicRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.CreateDynamicRoute(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRouteTablesAPIService CreateStaticRoute", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.CreateStaticRoute(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRouteTablesAPIService DeleteRouteEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var routeId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.DeleteRouteEntry(context.Background(), networkId, routeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRouteTablesAPIService GetEnhancedRouteTable", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.GetEnhancedRouteTable(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRouteTablesAPIService GetRouteEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var routeId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.GetRouteEntry(context.Background(), networkId, routeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EnhancedRouteTablesAPIService UpdateRouteEntry", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var routeId string

		resp, httpRes, err := apiClient.EnhancedRouteTablesAPI.UpdateRouteEntry(context.Background(), networkId, routeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
