/*
Harmony SASE Public API

Testing OpenVPNAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perimeter81-Public/perimeter-81-client-sdk"
)

func Test_perimeter81sdk_OpenVPNAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OpenVPNAPIService StandardCreateOpenVPNTunnel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.OpenVPNAPI.StandardCreateOpenVPNTunnel(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OpenVPNAPIService StandardDeleteOpenVPNTunnel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var tunnelId string

		resp, httpRes, err := apiClient.OpenVPNAPI.StandardDeleteOpenVPNTunnel(context.Background(), networkId, tunnelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OpenVPNAPIService StandardGetOpenVPNTunnel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var tunnelId string

		resp, httpRes, err := apiClient.OpenVPNAPI.StandardGetOpenVPNTunnel(context.Background(), networkId, tunnelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OpenVPNAPIService StandardUpdateOpenVPNTunnel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var tunnelId string

		resp, httpRes, err := apiClient.OpenVPNAPI.StandardUpdateOpenVPNTunnel(context.Background(), networkId, tunnelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
