/*
Harmony SASE Public API

Testing GatewaysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perimeter81-Public/perimeter-81-client-sdk/v2"
)

func Test_perimeter81sdk_GatewaysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GatewaysAPIService StandardGetInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var gatewayId string

		resp, httpRes, err := apiClient.GatewaysAPI.StandardGetInstance(context.Background(), networkId, gatewayId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GatewaysAPIService StandardNetworksControllerV2AddNetworkInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.GatewaysAPI.StandardNetworksControllerV2AddNetworkInstance(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GatewaysAPIService StandardNetworksControllerV2DeleteNetworkInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.GatewaysAPI.StandardNetworksControllerV2DeleteNetworkInstance(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
