/*
Harmony SASE Public API

Testing RegionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package perimeter81sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Perimeter81-Public/perimeter-81-client-sdk"
)

func Test_perimeter81sdk_RegionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RegionsAPIService StandardGetRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string
		var regionId string

		resp, httpRes, err := apiClient.RegionsAPI.StandardGetRegion(context.Background(), networkId, regionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService StandardNetworksControllerV2AddNetworkRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.RegionsAPI.StandardNetworksControllerV2AddNetworkRegion(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService StandardNetworksControllerV2DeleteNetworkRegion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var networkId string

		resp, httpRes, err := apiClient.RegionsAPI.StandardNetworksControllerV2DeleteNetworkRegion(context.Background(), networkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionsAPIService StandardNetworksControllerV2GetRegions", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RegionsAPI.StandardNetworksControllerV2GetRegions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
