/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectsAddressFQDN type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectsAddressFQDN{}

// ObjectsAddressFQDN struct for ObjectsAddressFQDN
type ObjectsAddressFQDN struct {
	ValueType string `json:"valueType"`
	Value []string `json:"value"`
}

type _ObjectsAddressFQDN ObjectsAddressFQDN

// NewObjectsAddressFQDN instantiates a new ObjectsAddressFQDN object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectsAddressFQDN(valueType string, value []string) *ObjectsAddressFQDN {
	this := ObjectsAddressFQDN{}
	this.ValueType = valueType
	this.Value = value
	return &this
}

// NewObjectsAddressFQDNWithDefaults instantiates a new ObjectsAddressFQDN object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectsAddressFQDNWithDefaults() *ObjectsAddressFQDN {
	this := ObjectsAddressFQDN{}
	return &this
}

// GetValueType returns the ValueType field value
func (o *ObjectsAddressFQDN) GetValueType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value
// and a boolean to check if the value has been set.
func (o *ObjectsAddressFQDN) GetValueTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueType, true
}

// SetValueType sets field value
func (o *ObjectsAddressFQDN) SetValueType(v string) {
	o.ValueType = v
}

// GetValue returns the Value field value
func (o *ObjectsAddressFQDN) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ObjectsAddressFQDN) GetValueOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *ObjectsAddressFQDN) SetValue(v []string) {
	o.Value = v
}

func (o ObjectsAddressFQDN) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectsAddressFQDN) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["valueType"] = o.ValueType
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ObjectsAddressFQDN) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"valueType",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectsAddressFQDN := _ObjectsAddressFQDN{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varObjectsAddressFQDN)

	if err != nil {
		return err
	}

	*o = ObjectsAddressFQDN(varObjectsAddressFQDN)

	return err
}

type NullableObjectsAddressFQDN struct {
	value *ObjectsAddressFQDN
	isSet bool
}

func (v NullableObjectsAddressFQDN) Get() *ObjectsAddressFQDN {
	return v.value
}

func (v *NullableObjectsAddressFQDN) Set(val *ObjectsAddressFQDN) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectsAddressFQDN) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectsAddressFQDN) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectsAddressFQDN(val *ObjectsAddressFQDN) *NullableObjectsAddressFQDN {
	return &NullableObjectsAddressFQDN{value: val, isSet: true}
}

func (v NullableObjectsAddressFQDN) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectsAddressFQDN) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


