/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedRegionAttributesEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedRegionAttributesEdge{}

// EnhancedRegionAttributesEdge struct for EnhancedRegionAttributesEdge
type EnhancedRegionAttributesEdge struct {
	// Array of IP addresses for the edge
	Addresses []string `json:"addresses"`
	// Array of Global IP addresses for the edge
	GlobalIPs []string `json:"globalIPs,omitempty"`
}

type _EnhancedRegionAttributesEdge EnhancedRegionAttributesEdge

// NewEnhancedRegionAttributesEdge instantiates a new EnhancedRegionAttributesEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedRegionAttributesEdge(addresses []string) *EnhancedRegionAttributesEdge {
	this := EnhancedRegionAttributesEdge{}
	this.Addresses = addresses
	return &this
}

// NewEnhancedRegionAttributesEdgeWithDefaults instantiates a new EnhancedRegionAttributesEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedRegionAttributesEdgeWithDefaults() *EnhancedRegionAttributesEdge {
	this := EnhancedRegionAttributesEdge{}
	return &this
}

// GetAddresses returns the Addresses field value
func (o *EnhancedRegionAttributesEdge) GetAddresses() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value
// and a boolean to check if the value has been set.
func (o *EnhancedRegionAttributesEdge) GetAddressesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addresses, true
}

// SetAddresses sets field value
func (o *EnhancedRegionAttributesEdge) SetAddresses(v []string) {
	o.Addresses = v
}

// GetGlobalIPs returns the GlobalIPs field value if set, zero value otherwise.
func (o *EnhancedRegionAttributesEdge) GetGlobalIPs() []string {
	if o == nil || IsNil(o.GlobalIPs) {
		var ret []string
		return ret
	}
	return o.GlobalIPs
}

// GetGlobalIPsOk returns a tuple with the GlobalIPs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedRegionAttributesEdge) GetGlobalIPsOk() ([]string, bool) {
	if o == nil || IsNil(o.GlobalIPs) {
		return nil, false
	}
	return o.GlobalIPs, true
}

// HasGlobalIPs returns a boolean if a field has been set.
func (o *EnhancedRegionAttributesEdge) HasGlobalIPs() bool {
	if o != nil && !IsNil(o.GlobalIPs) {
		return true
	}

	return false
}

// SetGlobalIPs gets a reference to the given []string and assigns it to the GlobalIPs field.
func (o *EnhancedRegionAttributesEdge) SetGlobalIPs(v []string) {
	o.GlobalIPs = v
}

func (o EnhancedRegionAttributesEdge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedRegionAttributesEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["addresses"] = o.Addresses
	if !IsNil(o.GlobalIPs) {
		toSerialize["globalIPs"] = o.GlobalIPs
	}
	return toSerialize, nil
}

func (o *EnhancedRegionAttributesEdge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"addresses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedRegionAttributesEdge := _EnhancedRegionAttributesEdge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEnhancedRegionAttributesEdge)

	if err != nil {
		return err
	}

	*o = EnhancedRegionAttributesEdge(varEnhancedRegionAttributesEdge)

	return err
}

type NullableEnhancedRegionAttributesEdge struct {
	value *EnhancedRegionAttributesEdge
	isSet bool
}

func (v NullableEnhancedRegionAttributesEdge) Get() *EnhancedRegionAttributesEdge {
	return v.value
}

func (v *NullableEnhancedRegionAttributesEdge) Set(val *EnhancedRegionAttributesEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedRegionAttributesEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedRegionAttributesEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedRegionAttributesEdge(val *EnhancedRegionAttributesEdge) *NullableEnhancedRegionAttributesEdge {
	return &NullableEnhancedRegionAttributesEdge{value: val, isSet: true}
}

func (v NullableEnhancedRegionAttributesEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedRegionAttributesEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


