/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IPSecAdvancedSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecAdvancedSettings{}

// IPSecAdvancedSettings struct for IPSecAdvancedSettings
type IPSecAdvancedSettings struct {
	KeyExchange string `json:"keyExchange"`
	IkeLifeTime string `json:"ikeLifeTime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime string `json:"lifetime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay string `json:"dpdDelay" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout string `json:"dpdTimeout" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 IPSecPhaseConfig `json:"phase1"`
	Phase2 IPSecPhaseConfig `json:"phase2"`
}

type _IPSecAdvancedSettings IPSecAdvancedSettings

// NewIPSecAdvancedSettings instantiates a new IPSecAdvancedSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecAdvancedSettings(keyExchange string, ikeLifeTime string, lifetime string, dpdDelay string, dpdTimeout string, phase1 IPSecPhaseConfig, phase2 IPSecPhaseConfig) *IPSecAdvancedSettings {
	this := IPSecAdvancedSettings{}
	this.KeyExchange = keyExchange
	this.IkeLifeTime = ikeLifeTime
	this.Lifetime = lifetime
	this.DpdDelay = dpdDelay
	this.DpdTimeout = dpdTimeout
	this.Phase1 = phase1
	this.Phase2 = phase2
	return &this
}

// NewIPSecAdvancedSettingsWithDefaults instantiates a new IPSecAdvancedSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecAdvancedSettingsWithDefaults() *IPSecAdvancedSettings {
	this := IPSecAdvancedSettings{}
	return &this
}

// GetKeyExchange returns the KeyExchange field value
func (o *IPSecAdvancedSettings) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *IPSecAdvancedSettings) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetIkeLifeTime returns the IkeLifeTime field value
func (o *IPSecAdvancedSettings) GetIkeLifeTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IkeLifeTime, true
}

// SetIkeLifeTime sets field value
func (o *IPSecAdvancedSettings) SetIkeLifeTime(v string) {
	o.IkeLifeTime = v
}

// GetLifetime returns the Lifetime field value
func (o *IPSecAdvancedSettings) GetLifetime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifetime, true
}

// SetLifetime sets field value
func (o *IPSecAdvancedSettings) SetLifetime(v string) {
	o.Lifetime = v
}

// GetDpdDelay returns the DpdDelay field value
func (o *IPSecAdvancedSettings) GetDpdDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetDpdDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdDelay, true
}

// SetDpdDelay sets field value
func (o *IPSecAdvancedSettings) SetDpdDelay(v string) {
	o.DpdDelay = v
}

// GetDpdTimeout returns the DpdTimeout field value
func (o *IPSecAdvancedSettings) GetDpdTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetDpdTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdTimeout, true
}

// SetDpdTimeout sets field value
func (o *IPSecAdvancedSettings) SetDpdTimeout(v string) {
	o.DpdTimeout = v
}

// GetPhase1 returns the Phase1 field value
func (o *IPSecAdvancedSettings) GetPhase1() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetPhase1Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase1, true
}

// SetPhase1 sets field value
func (o *IPSecAdvancedSettings) SetPhase1(v IPSecPhaseConfig) {
	o.Phase1 = v
}

// GetPhase2 returns the Phase2 field value
func (o *IPSecAdvancedSettings) GetPhase2() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettings) GetPhase2Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase2, true
}

// SetPhase2 sets field value
func (o *IPSecAdvancedSettings) SetPhase2(v IPSecPhaseConfig) {
	o.Phase2 = v
}

func (o IPSecAdvancedSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecAdvancedSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyExchange"] = o.KeyExchange
	toSerialize["ikeLifeTime"] = o.IkeLifeTime
	toSerialize["lifetime"] = o.Lifetime
	toSerialize["dpdDelay"] = o.DpdDelay
	toSerialize["dpdTimeout"] = o.DpdTimeout
	toSerialize["phase1"] = o.Phase1
	toSerialize["phase2"] = o.Phase2
	return toSerialize, nil
}

func (o *IPSecAdvancedSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keyExchange",
		"ikeLifeTime",
		"lifetime",
		"dpdDelay",
		"dpdTimeout",
		"phase1",
		"phase2",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecAdvancedSettings := _IPSecAdvancedSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIPSecAdvancedSettings)

	if err != nil {
		return err
	}

	*o = IPSecAdvancedSettings(varIPSecAdvancedSettings)

	return err
}

type NullableIPSecAdvancedSettings struct {
	value *IPSecAdvancedSettings
	isSet bool
}

func (v NullableIPSecAdvancedSettings) Get() *IPSecAdvancedSettings {
	return v.value
}

func (v *NullableIPSecAdvancedSettings) Set(val *IPSecAdvancedSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecAdvancedSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecAdvancedSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecAdvancedSettings(val *IPSecAdvancedSettings) *NullableIPSecAdvancedSettings {
	return &NullableIPSecAdvancedSettings{value: val, isSet: true}
}

func (v NullableIPSecAdvancedSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecAdvancedSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


