/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the IPSecSharedSettingsFeatures type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecSharedSettingsFeatures{}

// IPSecSharedSettingsFeatures struct for IPSecSharedSettingsFeatures
type IPSecSharedSettingsFeatures struct {
	SymmetricInnerMesh *IPSecSharedSettingsFeaturesSymmetricInnerMesh `json:"symmetricInnerMesh,omitempty"`
}

// NewIPSecSharedSettingsFeatures instantiates a new IPSecSharedSettingsFeatures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecSharedSettingsFeatures() *IPSecSharedSettingsFeatures {
	this := IPSecSharedSettingsFeatures{}
	return &this
}

// NewIPSecSharedSettingsFeaturesWithDefaults instantiates a new IPSecSharedSettingsFeatures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecSharedSettingsFeaturesWithDefaults() *IPSecSharedSettingsFeatures {
	this := IPSecSharedSettingsFeatures{}
	return &this
}

// GetSymmetricInnerMesh returns the SymmetricInnerMesh field value if set, zero value otherwise.
func (o *IPSecSharedSettingsFeatures) GetSymmetricInnerMesh() IPSecSharedSettingsFeaturesSymmetricInnerMesh {
	if o == nil || IsNil(o.SymmetricInnerMesh) {
		var ret IPSecSharedSettingsFeaturesSymmetricInnerMesh
		return ret
	}
	return *o.SymmetricInnerMesh
}

// GetSymmetricInnerMeshOk returns a tuple with the SymmetricInnerMesh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsFeatures) GetSymmetricInnerMeshOk() (*IPSecSharedSettingsFeaturesSymmetricInnerMesh, bool) {
	if o == nil || IsNil(o.SymmetricInnerMesh) {
		return nil, false
	}
	return o.SymmetricInnerMesh, true
}

// HasSymmetricInnerMesh returns a boolean if a field has been set.
func (o *IPSecSharedSettingsFeatures) HasSymmetricInnerMesh() bool {
	if o != nil && !IsNil(o.SymmetricInnerMesh) {
		return true
	}

	return false
}

// SetSymmetricInnerMesh gets a reference to the given IPSecSharedSettingsFeaturesSymmetricInnerMesh and assigns it to the SymmetricInnerMesh field.
func (o *IPSecSharedSettingsFeatures) SetSymmetricInnerMesh(v IPSecSharedSettingsFeaturesSymmetricInnerMesh) {
	o.SymmetricInnerMesh = &v
}

func (o IPSecSharedSettingsFeatures) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecSharedSettingsFeatures) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SymmetricInnerMesh) {
		toSerialize["symmetricInnerMesh"] = o.SymmetricInnerMesh
	}
	return toSerialize, nil
}

type NullableIPSecSharedSettingsFeatures struct {
	value *IPSecSharedSettingsFeatures
	isSet bool
}

func (v NullableIPSecSharedSettingsFeatures) Get() *IPSecSharedSettingsFeatures {
	return v.value
}

func (v *NullableIPSecSharedSettingsFeatures) Set(val *IPSecSharedSettingsFeatures) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecSharedSettingsFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecSharedSettingsFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecSharedSettingsFeatures(val *IPSecSharedSettingsFeatures) *NullableIPSecSharedSettingsFeatures {
	return &NullableIPSecSharedSettingsFeatures{value: val, isSet: true}
}

func (v NullableIPSecSharedSettingsFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecSharedSettingsFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


