/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateNetworkDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNetworkDto{}

// UpdateNetworkDto struct for UpdateNetworkDto
type UpdateNetworkDto struct {
	Network BaseNetworkDto `json:"network"`
}

type _UpdateNetworkDto UpdateNetworkDto

// NewUpdateNetworkDto instantiates a new UpdateNetworkDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNetworkDto(network BaseNetworkDto) *UpdateNetworkDto {
	this := UpdateNetworkDto{}
	this.Network = network
	return &this
}

// NewUpdateNetworkDtoWithDefaults instantiates a new UpdateNetworkDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkDtoWithDefaults() *UpdateNetworkDto {
	this := UpdateNetworkDto{}
	return &this
}

// GetNetwork returns the Network field value
func (o *UpdateNetworkDto) GetNetwork() BaseNetworkDto {
	if o == nil {
		var ret BaseNetworkDto
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *UpdateNetworkDto) GetNetworkOk() (*BaseNetworkDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *UpdateNetworkDto) SetNetwork(v BaseNetworkDto) {
	o.Network = v
}

func (o UpdateNetworkDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNetworkDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["network"] = o.Network
	return toSerialize, nil
}

func (o *UpdateNetworkDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"network",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateNetworkDto := _UpdateNetworkDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varUpdateNetworkDto)

	if err != nil {
		return err
	}

	*o = UpdateNetworkDto(varUpdateNetworkDto)

	return err
}

type NullableUpdateNetworkDto struct {
	value *UpdateNetworkDto
	isSet bool
}

func (v NullableUpdateNetworkDto) Get() *UpdateNetworkDto {
	return v.value
}

func (v *NullableUpdateNetworkDto) Set(val *UpdateNetworkDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkDto(val *UpdateNetworkDto) *NullableUpdateNetworkDto {
	return &NullableUpdateNetworkDto{value: val, isSet: true}
}

func (v NullableUpdateNetworkDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


