/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the EnhancedNetworkUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedNetworkUpdate{}

// EnhancedNetworkUpdate struct for EnhancedNetworkUpdate
type EnhancedNetworkUpdate struct {
	Network *EnhancedNetworkUpdateNetwork `json:"network,omitempty"`
}

// NewEnhancedNetworkUpdate instantiates a new EnhancedNetworkUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedNetworkUpdate() *EnhancedNetworkUpdate {
	this := EnhancedNetworkUpdate{}
	return &this
}

// NewEnhancedNetworkUpdateWithDefaults instantiates a new EnhancedNetworkUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedNetworkUpdateWithDefaults() *EnhancedNetworkUpdate {
	this := EnhancedNetworkUpdate{}
	return &this
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *EnhancedNetworkUpdate) GetNetwork() EnhancedNetworkUpdateNetwork {
	if o == nil || IsNil(o.Network) {
		var ret EnhancedNetworkUpdateNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedNetworkUpdate) GetNetworkOk() (*EnhancedNetworkUpdateNetwork, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *EnhancedNetworkUpdate) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given EnhancedNetworkUpdateNetwork and assigns it to the Network field.
func (o *EnhancedNetworkUpdate) SetNetwork(v EnhancedNetworkUpdateNetwork) {
	o.Network = &v
}

func (o EnhancedNetworkUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedNetworkUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableEnhancedNetworkUpdate struct {
	value *EnhancedNetworkUpdate
	isSet bool
}

func (v NullableEnhancedNetworkUpdate) Get() *EnhancedNetworkUpdate {
	return v.value
}

func (v *NullableEnhancedNetworkUpdate) Set(val *EnhancedNetworkUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedNetworkUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedNetworkUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedNetworkUpdate(val *EnhancedNetworkUpdate) *NullableEnhancedNetworkUpdate {
	return &NullableEnhancedNetworkUpdate{value: val, isSet: true}
}

func (v NullableEnhancedNetworkUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedNetworkUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


