/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the BasicApplicationAllOfIcon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicApplicationAllOfIcon{}

// BasicApplicationAllOfIcon Application icon
type BasicApplicationAllOfIcon struct {
	// Icon name
	Name *string `json:"name,omitempty"`
	// Icon URL
	Url *string `json:"url,omitempty"`
}

// NewBasicApplicationAllOfIcon instantiates a new BasicApplicationAllOfIcon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicApplicationAllOfIcon() *BasicApplicationAllOfIcon {
	this := BasicApplicationAllOfIcon{}
	return &this
}

// NewBasicApplicationAllOfIconWithDefaults instantiates a new BasicApplicationAllOfIcon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicApplicationAllOfIconWithDefaults() *BasicApplicationAllOfIcon {
	this := BasicApplicationAllOfIcon{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BasicApplicationAllOfIcon) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfIcon) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BasicApplicationAllOfIcon) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BasicApplicationAllOfIcon) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BasicApplicationAllOfIcon) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfIcon) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BasicApplicationAllOfIcon) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BasicApplicationAllOfIcon) SetUrl(v string) {
	o.Url = &v
}

func (o BasicApplicationAllOfIcon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicApplicationAllOfIcon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableBasicApplicationAllOfIcon struct {
	value *BasicApplicationAllOfIcon
	isSet bool
}

func (v NullableBasicApplicationAllOfIcon) Get() *BasicApplicationAllOfIcon {
	return v.value
}

func (v *NullableBasicApplicationAllOfIcon) Set(val *BasicApplicationAllOfIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicApplicationAllOfIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicApplicationAllOfIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicApplicationAllOfIcon(val *BasicApplicationAllOfIcon) *NullableBasicApplicationAllOfIcon {
	return &NullableBasicApplicationAllOfIcon{value: val, isSet: true}
}

func (v NullableBasicApplicationAllOfIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicApplicationAllOfIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


