/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type FirewallPolicy struct {
	// whether the policy is enabled.
	Enabled bool `json:"enabled"`
	// whether the policy is allow or deny.
	Allowed bool   `json:"allowed"`
	Id      string `json:"id"`
	// an array of policy rules.
	PolicyRules []FirewallPolicyRule `json:"policyRules"`
}
