/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationsListObjectAllOfNetwork type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationsListObjectAllOfNetwork{}

// ApplicationsListObjectAllOfNetwork Application related Network data
type ApplicationsListObjectAllOfNetwork struct {
	// Network Id
	Id string `json:"id"`
	// Network name
	Name string `json:"name"`
}

type _ApplicationsListObjectAllOfNetwork ApplicationsListObjectAllOfNetwork

// NewApplicationsListObjectAllOfNetwork instantiates a new ApplicationsListObjectAllOfNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationsListObjectAllOfNetwork(id string, name string) *ApplicationsListObjectAllOfNetwork {
	this := ApplicationsListObjectAllOfNetwork{}
	this.Id = id
	this.Name = name
	return &this
}

// NewApplicationsListObjectAllOfNetworkWithDefaults instantiates a new ApplicationsListObjectAllOfNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationsListObjectAllOfNetworkWithDefaults() *ApplicationsListObjectAllOfNetwork {
	this := ApplicationsListObjectAllOfNetwork{}
	return &this
}

// GetId returns the Id field value
func (o *ApplicationsListObjectAllOfNetwork) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ApplicationsListObjectAllOfNetwork) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApplicationsListObjectAllOfNetwork) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ApplicationsListObjectAllOfNetwork) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApplicationsListObjectAllOfNetwork) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApplicationsListObjectAllOfNetwork) SetName(v string) {
	o.Name = v
}

func (o ApplicationsListObjectAllOfNetwork) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationsListObjectAllOfNetwork) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *ApplicationsListObjectAllOfNetwork) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationsListObjectAllOfNetwork := _ApplicationsListObjectAllOfNetwork{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationsListObjectAllOfNetwork)

	if err != nil {
		return err
	}

	*o = ApplicationsListObjectAllOfNetwork(varApplicationsListObjectAllOfNetwork)

	return err
}

type NullableApplicationsListObjectAllOfNetwork struct {
	value *ApplicationsListObjectAllOfNetwork
	isSet bool
}

func (v NullableApplicationsListObjectAllOfNetwork) Get() *ApplicationsListObjectAllOfNetwork {
	return v.value
}

func (v *NullableApplicationsListObjectAllOfNetwork) Set(val *ApplicationsListObjectAllOfNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationsListObjectAllOfNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationsListObjectAllOfNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationsListObjectAllOfNetwork(val *ApplicationsListObjectAllOfNetwork) *NullableApplicationsListObjectAllOfNetwork {
	return &NullableApplicationsListObjectAllOfNetwork{value: val, isSet: true}
}

func (v NullableApplicationsListObjectAllOfNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationsListObjectAllOfNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


