/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RdpCreateApplication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RdpCreateApplication{}

// RdpCreateApplication struct for RdpCreateApplication
type RdpCreateApplication struct {
	// Application name
	Name string "json:\"name\" validate:\"regexp=^[^~`()!#$%^&*+=[]\\\\';,\\/{}|\\\":<>?№@]+$\""
	// Application type
	Type string `json:"type"`
	// Application network ID. To get the ID use endpoint '/networks' with [network:read] permission.
	Network string `json:"network" validate:"regexp=^[a-zA-Z0-9]+$"`
	Host NullableOneOfFixedHostIdpHost `json:"host"`
	Port NullableOneOfFixedPortIdpPort `json:"port"`
	Users []string `json:"users"`
	Groups []string `json:"groups"`
	Attributes RdpAttributes `json:"attributes"`
	Auth ApplicationAuth `json:"auth"`
}

type _RdpCreateApplication RdpCreateApplication

// NewRdpCreateApplication instantiates a new RdpCreateApplication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRdpCreateApplication(name string, type_ string, network string, host NullableOneOfFixedHostIdpHost, port NullableOneOfFixedPortIdpPort, users []string, groups []string, attributes RdpAttributes, auth ApplicationAuth) *RdpCreateApplication {
	this := RdpCreateApplication{}
	this.Name = name
	this.Type = type_
	this.Network = network
	this.Host = host
	this.Port = port
	this.Users = users
	this.Groups = groups
	this.Attributes = attributes
	this.Auth = auth
	return &this
}

// NewRdpCreateApplicationWithDefaults instantiates a new RdpCreateApplication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRdpCreateApplicationWithDefaults() *RdpCreateApplication {
	this := RdpCreateApplication{}
	return &this
}

// GetName returns the Name field value
func (o *RdpCreateApplication) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RdpCreateApplication) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *RdpCreateApplication) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RdpCreateApplication) SetType(v string) {
	o.Type = v
}

// GetNetwork returns the Network field value
func (o *RdpCreateApplication) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *RdpCreateApplication) SetNetwork(v string) {
	o.Network = v
}

// GetHost returns the Host field value
// If the value is explicit nil, the zero value for OneOfFixedHostIdpHost will be returned
func (o *RdpCreateApplication) GetHost() OneOfFixedHostIdpHost {
	if o == nil || o.Host.Get() == nil {
		var ret OneOfFixedHostIdpHost
		return ret
	}

	return *o.Host.Get()
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RdpCreateApplication) GetHostOk() (*OneOfFixedHostIdpHost, bool) {
	if o == nil {
		return nil, false
	}
	return o.Host.Get(), o.Host.IsSet()
}

// SetHost sets field value
func (o *RdpCreateApplication) SetHost(v OneOfFixedHostIdpHost) {
	o.Host.Set(&v)
}

// GetPort returns the Port field value
// If the value is explicit nil, the zero value for OneOfFixedPortIdpPort will be returned
func (o *RdpCreateApplication) GetPort() OneOfFixedPortIdpPort {
	if o == nil || o.Port.Get() == nil {
		var ret OneOfFixedPortIdpPort
		return ret
	}

	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RdpCreateApplication) GetPortOk() (*OneOfFixedPortIdpPort, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// SetPort sets field value
func (o *RdpCreateApplication) SetPort(v OneOfFixedPortIdpPort) {
	o.Port.Set(&v)
}

// GetUsers returns the Users field value
func (o *RdpCreateApplication) GetUsers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetUsersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *RdpCreateApplication) SetUsers(v []string) {
	o.Users = v
}

// GetGroups returns the Groups field value
func (o *RdpCreateApplication) GetGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *RdpCreateApplication) SetGroups(v []string) {
	o.Groups = v
}

// GetAttributes returns the Attributes field value
func (o *RdpCreateApplication) GetAttributes() RdpAttributes {
	if o == nil {
		var ret RdpAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetAttributesOk() (*RdpAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RdpCreateApplication) SetAttributes(v RdpAttributes) {
	o.Attributes = v
}

// GetAuth returns the Auth field value
func (o *RdpCreateApplication) GetAuth() ApplicationAuth {
	if o == nil {
		var ret ApplicationAuth
		return ret
	}

	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value
// and a boolean to check if the value has been set.
func (o *RdpCreateApplication) GetAuthOk() (*ApplicationAuth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auth, true
}

// SetAuth sets field value
func (o *RdpCreateApplication) SetAuth(v ApplicationAuth) {
	o.Auth = v
}

func (o RdpCreateApplication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RdpCreateApplication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["network"] = o.Network
	toSerialize["host"] = o.Host.Get()
	toSerialize["port"] = o.Port.Get()
	toSerialize["users"] = o.Users
	toSerialize["groups"] = o.Groups
	toSerialize["attributes"] = o.Attributes
	toSerialize["auth"] = o.Auth
	return toSerialize, nil
}

func (o *RdpCreateApplication) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"network",
		"host",
		"port",
		"users",
		"groups",
		"attributes",
		"auth",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRdpCreateApplication := _RdpCreateApplication{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRdpCreateApplication)

	if err != nil {
		return err
	}

	*o = RdpCreateApplication(varRdpCreateApplication)

	return err
}

type NullableRdpCreateApplication struct {
	value *RdpCreateApplication
	isSet bool
}

func (v NullableRdpCreateApplication) Get() *RdpCreateApplication {
	return v.value
}

func (v *NullableRdpCreateApplication) Set(val *RdpCreateApplication) {
	v.value = val
	v.isSet = true
}

func (v NullableRdpCreateApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableRdpCreateApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRdpCreateApplication(val *RdpCreateApplication) *NullableRdpCreateApplication {
	return &NullableRdpCreateApplication{value: val, isSet: true}
}

func (v NullableRdpCreateApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRdpCreateApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


