/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DynamicTunnelUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicTunnelUpdate{}

// DynamicTunnelUpdate struct for DynamicTunnelUpdate
type DynamicTunnelUpdate struct {
	// Name of the tunnel
	TunnelName string `json:"tunnelName"`
	// Optional description for the tunnel
	Description *string `json:"description,omitempty"`
	AddTunnels []DynamicTunnelDetails `json:"addTunnels,omitempty"`
	UpdateTunnels []DynamicTunnelUpdateUpdateTunnelsInner `json:"updateTunnels,omitempty"`
	RemoveTunnels []DynamicTunnelUpdateRemoveTunnelsInner `json:"removeTunnels,omitempty"`
	SharedSettings *EnhancedIPSecSharedSettingsUpdate `json:"sharedSettings,omitempty"`
	AdvancedSettings *IPSecAdvancedSettingsUpdateV23 `json:"advancedSettings,omitempty"`
	RoutingType *RoutingType `json:"routingType,omitempty"`
}

type _DynamicTunnelUpdate DynamicTunnelUpdate

// NewDynamicTunnelUpdate instantiates a new DynamicTunnelUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicTunnelUpdate(tunnelName string) *DynamicTunnelUpdate {
	this := DynamicTunnelUpdate{}
	this.TunnelName = tunnelName
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	return &this
}

// NewDynamicTunnelUpdateWithDefaults instantiates a new DynamicTunnelUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicTunnelUpdateWithDefaults() *DynamicTunnelUpdate {
	this := DynamicTunnelUpdate{}
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	return &this
}

// GetTunnelName returns the TunnelName field value
func (o *DynamicTunnelUpdate) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *DynamicTunnelUpdate) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DynamicTunnelUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetAddTunnels returns the AddTunnels field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetAddTunnels() []DynamicTunnelDetails {
	if o == nil || IsNil(o.AddTunnels) {
		var ret []DynamicTunnelDetails
		return ret
	}
	return o.AddTunnels
}

// GetAddTunnelsOk returns a tuple with the AddTunnels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetAddTunnelsOk() ([]DynamicTunnelDetails, bool) {
	if o == nil || IsNil(o.AddTunnels) {
		return nil, false
	}
	return o.AddTunnels, true
}

// HasAddTunnels returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasAddTunnels() bool {
	if o != nil && !IsNil(o.AddTunnels) {
		return true
	}

	return false
}

// SetAddTunnels gets a reference to the given []DynamicTunnelDetails and assigns it to the AddTunnels field.
func (o *DynamicTunnelUpdate) SetAddTunnels(v []DynamicTunnelDetails) {
	o.AddTunnels = v
}

// GetUpdateTunnels returns the UpdateTunnels field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetUpdateTunnels() []DynamicTunnelUpdateUpdateTunnelsInner {
	if o == nil || IsNil(o.UpdateTunnels) {
		var ret []DynamicTunnelUpdateUpdateTunnelsInner
		return ret
	}
	return o.UpdateTunnels
}

// GetUpdateTunnelsOk returns a tuple with the UpdateTunnels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetUpdateTunnelsOk() ([]DynamicTunnelUpdateUpdateTunnelsInner, bool) {
	if o == nil || IsNil(o.UpdateTunnels) {
		return nil, false
	}
	return o.UpdateTunnels, true
}

// HasUpdateTunnels returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasUpdateTunnels() bool {
	if o != nil && !IsNil(o.UpdateTunnels) {
		return true
	}

	return false
}

// SetUpdateTunnels gets a reference to the given []DynamicTunnelUpdateUpdateTunnelsInner and assigns it to the UpdateTunnels field.
func (o *DynamicTunnelUpdate) SetUpdateTunnels(v []DynamicTunnelUpdateUpdateTunnelsInner) {
	o.UpdateTunnels = v
}

// GetRemoveTunnels returns the RemoveTunnels field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetRemoveTunnels() []DynamicTunnelUpdateRemoveTunnelsInner {
	if o == nil || IsNil(o.RemoveTunnels) {
		var ret []DynamicTunnelUpdateRemoveTunnelsInner
		return ret
	}
	return o.RemoveTunnels
}

// GetRemoveTunnelsOk returns a tuple with the RemoveTunnels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetRemoveTunnelsOk() ([]DynamicTunnelUpdateRemoveTunnelsInner, bool) {
	if o == nil || IsNil(o.RemoveTunnels) {
		return nil, false
	}
	return o.RemoveTunnels, true
}

// HasRemoveTunnels returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasRemoveTunnels() bool {
	if o != nil && !IsNil(o.RemoveTunnels) {
		return true
	}

	return false
}

// SetRemoveTunnels gets a reference to the given []DynamicTunnelUpdateRemoveTunnelsInner and assigns it to the RemoveTunnels field.
func (o *DynamicTunnelUpdate) SetRemoveTunnels(v []DynamicTunnelUpdateRemoveTunnelsInner) {
	o.RemoveTunnels = v
}

// GetSharedSettings returns the SharedSettings field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetSharedSettings() EnhancedIPSecSharedSettingsUpdate {
	if o == nil || IsNil(o.SharedSettings) {
		var ret EnhancedIPSecSharedSettingsUpdate
		return ret
	}
	return *o.SharedSettings
}

// GetSharedSettingsOk returns a tuple with the SharedSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetSharedSettingsOk() (*EnhancedIPSecSharedSettingsUpdate, bool) {
	if o == nil || IsNil(o.SharedSettings) {
		return nil, false
	}
	return o.SharedSettings, true
}

// HasSharedSettings returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasSharedSettings() bool {
	if o != nil && !IsNil(o.SharedSettings) {
		return true
	}

	return false
}

// SetSharedSettings gets a reference to the given EnhancedIPSecSharedSettingsUpdate and assigns it to the SharedSettings field.
func (o *DynamicTunnelUpdate) SetSharedSettings(v EnhancedIPSecSharedSettingsUpdate) {
	o.SharedSettings = &v
}

// GetAdvancedSettings returns the AdvancedSettings field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetAdvancedSettings() IPSecAdvancedSettingsUpdateV23 {
	if o == nil || IsNil(o.AdvancedSettings) {
		var ret IPSecAdvancedSettingsUpdateV23
		return ret
	}
	return *o.AdvancedSettings
}

// GetAdvancedSettingsOk returns a tuple with the AdvancedSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetAdvancedSettingsOk() (*IPSecAdvancedSettingsUpdateV23, bool) {
	if o == nil || IsNil(o.AdvancedSettings) {
		return nil, false
	}
	return o.AdvancedSettings, true
}

// HasAdvancedSettings returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasAdvancedSettings() bool {
	if o != nil && !IsNil(o.AdvancedSettings) {
		return true
	}

	return false
}

// SetAdvancedSettings gets a reference to the given IPSecAdvancedSettingsUpdateV23 and assigns it to the AdvancedSettings field.
func (o *DynamicTunnelUpdate) SetAdvancedSettings(v IPSecAdvancedSettingsUpdateV23) {
	o.AdvancedSettings = &v
}

// GetRoutingType returns the RoutingType field value if set, zero value otherwise.
func (o *DynamicTunnelUpdate) GetRoutingType() RoutingType {
	if o == nil || IsNil(o.RoutingType) {
		var ret RoutingType
		return ret
	}
	return *o.RoutingType
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelUpdate) GetRoutingTypeOk() (*RoutingType, bool) {
	if o == nil || IsNil(o.RoutingType) {
		return nil, false
	}
	return o.RoutingType, true
}

// HasRoutingType returns a boolean if a field has been set.
func (o *DynamicTunnelUpdate) HasRoutingType() bool {
	if o != nil && !IsNil(o.RoutingType) {
		return true
	}

	return false
}

// SetRoutingType gets a reference to the given RoutingType and assigns it to the RoutingType field.
func (o *DynamicTunnelUpdate) SetRoutingType(v RoutingType) {
	o.RoutingType = &v
}

func (o DynamicTunnelUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicTunnelUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tunnelName"] = o.TunnelName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AddTunnels) {
		toSerialize["addTunnels"] = o.AddTunnels
	}
	if !IsNil(o.UpdateTunnels) {
		toSerialize["updateTunnels"] = o.UpdateTunnels
	}
	if !IsNil(o.RemoveTunnels) {
		toSerialize["removeTunnels"] = o.RemoveTunnels
	}
	if !IsNil(o.SharedSettings) {
		toSerialize["sharedSettings"] = o.SharedSettings
	}
	if !IsNil(o.AdvancedSettings) {
		toSerialize["advancedSettings"] = o.AdvancedSettings
	}
	if !IsNil(o.RoutingType) {
		toSerialize["routingType"] = o.RoutingType
	}
	return toSerialize, nil
}

func (o *DynamicTunnelUpdate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tunnelName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDynamicTunnelUpdate := _DynamicTunnelUpdate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDynamicTunnelUpdate)

	if err != nil {
		return err
	}

	*o = DynamicTunnelUpdate(varDynamicTunnelUpdate)

	return err
}

type NullableDynamicTunnelUpdate struct {
	value *DynamicTunnelUpdate
	isSet bool
}

func (v NullableDynamicTunnelUpdate) Get() *DynamicTunnelUpdate {
	return v.value
}

func (v *NullableDynamicTunnelUpdate) Set(val *DynamicTunnelUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicTunnelUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicTunnelUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicTunnelUpdate(val *DynamicTunnelUpdate) *NullableDynamicTunnelUpdate {
	return &NullableDynamicTunnelUpdate{value: val, isSet: true}
}

func (v NullableDynamicTunnelUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicTunnelUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


