/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type ObjectsServicesRequestObj struct {
	Name        string                              `json:"name"`
	Id          string                              `json:"id,omitempty"`
	Description string                              `json:"description,omitempty"`
	Protocols   []ObjectsServicesProtocolRequestObj `json:"protocols"`
}
