/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DynamicTunnelDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicTunnelDetails{}

// DynamicTunnelDetails struct for DynamicTunnelDetails
type DynamicTunnelDetails struct {
	// Authentication type for tunnel (psk for pre-shared key, cert for certificate)
	AuthType *string `json:"authType,omitempty"`
	// Pre-shared key for tunnel authentication (8-64 characters). Required when authType is psk.
	Passphrase *string `json:"passphrase,omitempty"`
	// Customer root certificate authority. Required when authType is cert.
	CustomerRootCA *string `json:"customerRootCA,omitempty"`
	// Harmony Sase gateway internal IP address
	P81GWInternalIP *string `json:"p81GWInternalIP,omitempty"`
	// Remote gateway internal IP address
	RemoteGWInternalIP *string `json:"remoteGWInternalIP,omitempty"`
	// Remote gateway public IP address
	RemotePublicIP *string `json:"remotePublicIP,omitempty"`
	RemoteASN *ASN `json:"remoteASN,omitempty"`
	// Remote gateway ID
	RemoteID *string `json:"remoteID,omitempty"`
	RoutingType *RoutingType `json:"routingType,omitempty"`
	// Dynamic tunnel enhanced region ID
	RegionID string `json:"regionID"`
}

type _DynamicTunnelDetails DynamicTunnelDetails

// NewDynamicTunnelDetails instantiates a new DynamicTunnelDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicTunnelDetails(regionID string) *DynamicTunnelDetails {
	this := DynamicTunnelDetails{}
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	this.RegionID = regionID
	return &this
}

// NewDynamicTunnelDetailsWithDefaults instantiates a new DynamicTunnelDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicTunnelDetailsWithDefaults() *DynamicTunnelDetails {
	this := DynamicTunnelDetails{}
	var routingType RoutingType = ROUTINGTYPE_ROUTE
	this.RoutingType = &routingType
	return &this
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetAuthType() string {
	if o == nil || IsNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetAuthTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *DynamicTunnelDetails) SetAuthType(v string) {
	o.AuthType = &v
}

// GetPassphrase returns the Passphrase field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetPassphrase() string {
	if o == nil || IsNil(o.Passphrase) {
		var ret string
		return ret
	}
	return *o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.Passphrase) {
		return nil, false
	}
	return o.Passphrase, true
}

// HasPassphrase returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasPassphrase() bool {
	if o != nil && !IsNil(o.Passphrase) {
		return true
	}

	return false
}

// SetPassphrase gets a reference to the given string and assigns it to the Passphrase field.
func (o *DynamicTunnelDetails) SetPassphrase(v string) {
	o.Passphrase = &v
}

// GetCustomerRootCA returns the CustomerRootCA field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetCustomerRootCA() string {
	if o == nil || IsNil(o.CustomerRootCA) {
		var ret string
		return ret
	}
	return *o.CustomerRootCA
}

// GetCustomerRootCAOk returns a tuple with the CustomerRootCA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetCustomerRootCAOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerRootCA) {
		return nil, false
	}
	return o.CustomerRootCA, true
}

// HasCustomerRootCA returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasCustomerRootCA() bool {
	if o != nil && !IsNil(o.CustomerRootCA) {
		return true
	}

	return false
}

// SetCustomerRootCA gets a reference to the given string and assigns it to the CustomerRootCA field.
func (o *DynamicTunnelDetails) SetCustomerRootCA(v string) {
	o.CustomerRootCA = &v
}

// GetP81GWInternalIP returns the P81GWInternalIP field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetP81GWInternalIP() string {
	if o == nil || IsNil(o.P81GWInternalIP) {
		var ret string
		return ret
	}
	return *o.P81GWInternalIP
}

// GetP81GWInternalIPOk returns a tuple with the P81GWInternalIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetP81GWInternalIPOk() (*string, bool) {
	if o == nil || IsNil(o.P81GWInternalIP) {
		return nil, false
	}
	return o.P81GWInternalIP, true
}

// HasP81GWInternalIP returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasP81GWInternalIP() bool {
	if o != nil && !IsNil(o.P81GWInternalIP) {
		return true
	}

	return false
}

// SetP81GWInternalIP gets a reference to the given string and assigns it to the P81GWInternalIP field.
func (o *DynamicTunnelDetails) SetP81GWInternalIP(v string) {
	o.P81GWInternalIP = &v
}

// GetRemoteGWInternalIP returns the RemoteGWInternalIP field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetRemoteGWInternalIP() string {
	if o == nil || IsNil(o.RemoteGWInternalIP) {
		var ret string
		return ret
	}
	return *o.RemoteGWInternalIP
}

// GetRemoteGWInternalIPOk returns a tuple with the RemoteGWInternalIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRemoteGWInternalIPOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteGWInternalIP) {
		return nil, false
	}
	return o.RemoteGWInternalIP, true
}

// HasRemoteGWInternalIP returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasRemoteGWInternalIP() bool {
	if o != nil && !IsNil(o.RemoteGWInternalIP) {
		return true
	}

	return false
}

// SetRemoteGWInternalIP gets a reference to the given string and assigns it to the RemoteGWInternalIP field.
func (o *DynamicTunnelDetails) SetRemoteGWInternalIP(v string) {
	o.RemoteGWInternalIP = &v
}

// GetRemotePublicIP returns the RemotePublicIP field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetRemotePublicIP() string {
	if o == nil || IsNil(o.RemotePublicIP) {
		var ret string
		return ret
	}
	return *o.RemotePublicIP
}

// GetRemotePublicIPOk returns a tuple with the RemotePublicIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRemotePublicIPOk() (*string, bool) {
	if o == nil || IsNil(o.RemotePublicIP) {
		return nil, false
	}
	return o.RemotePublicIP, true
}

// HasRemotePublicIP returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasRemotePublicIP() bool {
	if o != nil && !IsNil(o.RemotePublicIP) {
		return true
	}

	return false
}

// SetRemotePublicIP gets a reference to the given string and assigns it to the RemotePublicIP field.
func (o *DynamicTunnelDetails) SetRemotePublicIP(v string) {
	o.RemotePublicIP = &v
}

// GetRemoteASN returns the RemoteASN field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetRemoteASN() ASN {
	if o == nil || IsNil(o.RemoteASN) {
		var ret ASN
		return ret
	}
	return *o.RemoteASN
}

// GetRemoteASNOk returns a tuple with the RemoteASN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRemoteASNOk() (*ASN, bool) {
	if o == nil || IsNil(o.RemoteASN) {
		return nil, false
	}
	return o.RemoteASN, true
}

// HasRemoteASN returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasRemoteASN() bool {
	if o != nil && !IsNil(o.RemoteASN) {
		return true
	}

	return false
}

// SetRemoteASN gets a reference to the given ASN and assigns it to the RemoteASN field.
func (o *DynamicTunnelDetails) SetRemoteASN(v ASN) {
	o.RemoteASN = &v
}

// GetRemoteID returns the RemoteID field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetRemoteID() string {
	if o == nil || IsNil(o.RemoteID) {
		var ret string
		return ret
	}
	return *o.RemoteID
}

// GetRemoteIDOk returns a tuple with the RemoteID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRemoteIDOk() (*string, bool) {
	if o == nil || IsNil(o.RemoteID) {
		return nil, false
	}
	return o.RemoteID, true
}

// HasRemoteID returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasRemoteID() bool {
	if o != nil && !IsNil(o.RemoteID) {
		return true
	}

	return false
}

// SetRemoteID gets a reference to the given string and assigns it to the RemoteID field.
func (o *DynamicTunnelDetails) SetRemoteID(v string) {
	o.RemoteID = &v
}

// GetRoutingType returns the RoutingType field value if set, zero value otherwise.
func (o *DynamicTunnelDetails) GetRoutingType() RoutingType {
	if o == nil || IsNil(o.RoutingType) {
		var ret RoutingType
		return ret
	}
	return *o.RoutingType
}

// GetRoutingTypeOk returns a tuple with the RoutingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRoutingTypeOk() (*RoutingType, bool) {
	if o == nil || IsNil(o.RoutingType) {
		return nil, false
	}
	return o.RoutingType, true
}

// HasRoutingType returns a boolean if a field has been set.
func (o *DynamicTunnelDetails) HasRoutingType() bool {
	if o != nil && !IsNil(o.RoutingType) {
		return true
	}

	return false
}

// SetRoutingType gets a reference to the given RoutingType and assigns it to the RoutingType field.
func (o *DynamicTunnelDetails) SetRoutingType(v RoutingType) {
	o.RoutingType = &v
}

// GetRegionID returns the RegionID field value
func (o *DynamicTunnelDetails) GetRegionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionID
}

// GetRegionIDOk returns a tuple with the RegionID field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelDetails) GetRegionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionID, true
}

// SetRegionID sets field value
func (o *DynamicTunnelDetails) SetRegionID(v string) {
	o.RegionID = v
}

func (o DynamicTunnelDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicTunnelDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthType) {
		toSerialize["authType"] = o.AuthType
	}
	if !IsNil(o.Passphrase) {
		toSerialize["passphrase"] = o.Passphrase
	}
	if !IsNil(o.CustomerRootCA) {
		toSerialize["customerRootCA"] = o.CustomerRootCA
	}
	if !IsNil(o.P81GWInternalIP) {
		toSerialize["p81GWInternalIP"] = o.P81GWInternalIP
	}
	if !IsNil(o.RemoteGWInternalIP) {
		toSerialize["remoteGWInternalIP"] = o.RemoteGWInternalIP
	}
	if !IsNil(o.RemotePublicIP) {
		toSerialize["remotePublicIP"] = o.RemotePublicIP
	}
	if !IsNil(o.RemoteASN) {
		toSerialize["remoteASN"] = o.RemoteASN
	}
	if !IsNil(o.RemoteID) {
		toSerialize["remoteID"] = o.RemoteID
	}
	if !IsNil(o.RoutingType) {
		toSerialize["routingType"] = o.RoutingType
	}
	toSerialize["regionID"] = o.RegionID
	return toSerialize, nil
}

func (o *DynamicTunnelDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDynamicTunnelDetails := _DynamicTunnelDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDynamicTunnelDetails)

	if err != nil {
		return err
	}

	*o = DynamicTunnelDetails(varDynamicTunnelDetails)

	return err
}

type NullableDynamicTunnelDetails struct {
	value *DynamicTunnelDetails
	isSet bool
}

func (v NullableDynamicTunnelDetails) Get() *DynamicTunnelDetails {
	return v.value
}

func (v *NullableDynamicTunnelDetails) Set(val *DynamicTunnelDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicTunnelDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicTunnelDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicTunnelDetails(val *DynamicTunnelDetails) *NullableDynamicTunnelDetails {
	return &NullableDynamicTunnelDetails{value: val, isSet: true}
}

func (v NullableDynamicTunnelDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicTunnelDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


