/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

import (
	"time"
)

type IpSecSingleTunnel struct {
	P81GatewaySubnets    []string    `json:"p81GatewaySubnets,omitempty"`
	RemoteGatewaySubnets []string    `json:"remoteGatewaySubnets,omitempty"`
	Passphrase           string      `json:"passphrase,omitempty"`
	RemotePublicIP       string      `json:"remotePublicIP,omitempty"`
	KeyExchange          string      `json:"keyExchange,omitempty"`
	IkeLifeTime          string      `json:"ikeLifeTime,omitempty"`
	DpdDelay             string      `json:"dpdDelay,omitempty"`
	DpdTimeout           string      `json:"dpdTimeout,omitempty"`
	RemoteID             string      `json:"remoteID,omitempty"`
	Phase1               *IpSecPhase `json:"phase1,omitempty"`
	Phase2               *IpSecPhase `json:"phase2,omitempty"`
	// Region ID
	RegionID string `json:"regionID"`
	// Gatwway ID
	GatewayID  string    `json:"gatewayID"`
	TunnelName string    `json:"tunnelName"`
	Type_      string    `json:"type,omitempty"`
	CreatedAt  time.Time `json:"createdAt,omitempty"`
	UpdatedAt  time.Time `json:"updatedAt,omitempty"`
	TunnelID   string    `json:"tunnelID,omitempty"`
}
