/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the IPSecSingleTunnel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecSingleTunnel{}

// IPSecSingleTunnel struct for IPSecSingleTunnel
type IPSecSingleTunnel struct {
	// Region ID
	RegionID string `json:"regionID"`
	// Gateway ID
	GatewayID string `json:"gatewayID"`
	// The name of the tunnel
	TunnelName string `json:"tunnelName" validate:"regexp=^[a-zA-Z0-9]*$"`
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidth *int32 `json:"peakBandwidth,omitempty"`
	P81ASN *RemoteASN `json:"p81ASN,omitempty"`
	Features *IPSecSharedSettingsFeatures `json:"features,omitempty"`
	KeyExchange string `json:"keyExchange"`
	IkeLifeTime string `json:"ikeLifeTime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime string `json:"lifetime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay string `json:"dpdDelay" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout string `json:"dpdTimeout" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 IPSecPhaseConfig `json:"phase1"`
	Phase2 IPSecPhaseConfig `json:"phase2"`
	Passphrase *string `json:"passphrase,omitempty" validate:"regexp=^[a-zA-Z1-9._][a-zA-Z0-9._]{7,63}$"`
	RemotePublicIP *string `json:"remotePublicIP,omitempty"`
	RemoteID *RemoteID `json:"remoteID,omitempty"`
	// The date when this record was created.
	CreatedAt time.Time `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Type *string `json:"type,omitempty"`
	TunnelID *string `json:"tunnelID,omitempty"`
}

type _IPSecSingleTunnel IPSecSingleTunnel

// NewIPSecSingleTunnel instantiates a new IPSecSingleTunnel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecSingleTunnel(regionID string, gatewayID string, tunnelName string, p81GatewaySubnets []string, remoteGatewaySubnets []string, keyExchange string, ikeLifeTime string, lifetime string, dpdDelay string, dpdTimeout string, phase1 IPSecPhaseConfig, phase2 IPSecPhaseConfig, createdAt time.Time) *IPSecSingleTunnel {
	this := IPSecSingleTunnel{}
	this.RegionID = regionID
	this.GatewayID = gatewayID
	this.TunnelName = tunnelName
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	this.KeyExchange = keyExchange
	this.IkeLifeTime = ikeLifeTime
	this.Lifetime = lifetime
	this.DpdDelay = dpdDelay
	this.DpdTimeout = dpdTimeout
	this.Phase1 = phase1
	this.Phase2 = phase2
	this.CreatedAt = createdAt
	var type_ string = "ipsec"
	this.Type = &type_
	return &this
}

// NewIPSecSingleTunnelWithDefaults instantiates a new IPSecSingleTunnel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecSingleTunnelWithDefaults() *IPSecSingleTunnel {
	this := IPSecSingleTunnel{}
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	var type_ string = "ipsec"
	this.Type = &type_
	return &this
}

// GetRegionID returns the RegionID field value
func (o *IPSecSingleTunnel) GetRegionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionID
}

// GetRegionIDOk returns a tuple with the RegionID field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetRegionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionID, true
}

// SetRegionID sets field value
func (o *IPSecSingleTunnel) SetRegionID(v string) {
	o.RegionID = v
}

// GetGatewayID returns the GatewayID field value
func (o *IPSecSingleTunnel) GetGatewayID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayID
}

// GetGatewayIDOk returns a tuple with the GatewayID field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetGatewayIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayID, true
}

// SetGatewayID sets field value
func (o *IPSecSingleTunnel) SetGatewayID(v string) {
	o.GatewayID = v
}

// GetTunnelName returns the TunnelName field value
func (o *IPSecSingleTunnel) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *IPSecSingleTunnel) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *IPSecSingleTunnel) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *IPSecSingleTunnel) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *IPSecSingleTunnel) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *IPSecSingleTunnel) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetPeakBandwidth returns the PeakBandwidth field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetPeakBandwidth() int32 {
	if o == nil || IsNil(o.PeakBandwidth) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidth
}

// GetPeakBandwidthOk returns a tuple with the PeakBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetPeakBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidth) {
		return nil, false
	}
	return o.PeakBandwidth, true
}

// HasPeakBandwidth returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasPeakBandwidth() bool {
	if o != nil && !IsNil(o.PeakBandwidth) {
		return true
	}

	return false
}

// SetPeakBandwidth gets a reference to the given int32 and assigns it to the PeakBandwidth field.
func (o *IPSecSingleTunnel) SetPeakBandwidth(v int32) {
	o.PeakBandwidth = &v
}

// GetP81ASN returns the P81ASN field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetP81ASN() RemoteASN {
	if o == nil || IsNil(o.P81ASN) {
		var ret RemoteASN
		return ret
	}
	return *o.P81ASN
}

// GetP81ASNOk returns a tuple with the P81ASN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetP81ASNOk() (*RemoteASN, bool) {
	if o == nil || IsNil(o.P81ASN) {
		return nil, false
	}
	return o.P81ASN, true
}

// HasP81ASN returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasP81ASN() bool {
	if o != nil && !IsNil(o.P81ASN) {
		return true
	}

	return false
}

// SetP81ASN gets a reference to the given RemoteASN and assigns it to the P81ASN field.
func (o *IPSecSingleTunnel) SetP81ASN(v RemoteASN) {
	o.P81ASN = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetFeatures() IPSecSharedSettingsFeatures {
	if o == nil || IsNil(o.Features) {
		var ret IPSecSharedSettingsFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetFeaturesOk() (*IPSecSharedSettingsFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given IPSecSharedSettingsFeatures and assigns it to the Features field.
func (o *IPSecSingleTunnel) SetFeatures(v IPSecSharedSettingsFeatures) {
	o.Features = &v
}

// GetKeyExchange returns the KeyExchange field value
func (o *IPSecSingleTunnel) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *IPSecSingleTunnel) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetIkeLifeTime returns the IkeLifeTime field value
func (o *IPSecSingleTunnel) GetIkeLifeTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IkeLifeTime, true
}

// SetIkeLifeTime sets field value
func (o *IPSecSingleTunnel) SetIkeLifeTime(v string) {
	o.IkeLifeTime = v
}

// GetLifetime returns the Lifetime field value
func (o *IPSecSingleTunnel) GetLifetime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifetime, true
}

// SetLifetime sets field value
func (o *IPSecSingleTunnel) SetLifetime(v string) {
	o.Lifetime = v
}

// GetDpdDelay returns the DpdDelay field value
func (o *IPSecSingleTunnel) GetDpdDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetDpdDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdDelay, true
}

// SetDpdDelay sets field value
func (o *IPSecSingleTunnel) SetDpdDelay(v string) {
	o.DpdDelay = v
}

// GetDpdTimeout returns the DpdTimeout field value
func (o *IPSecSingleTunnel) GetDpdTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetDpdTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdTimeout, true
}

// SetDpdTimeout sets field value
func (o *IPSecSingleTunnel) SetDpdTimeout(v string) {
	o.DpdTimeout = v
}

// GetPhase1 returns the Phase1 field value
func (o *IPSecSingleTunnel) GetPhase1() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetPhase1Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase1, true
}

// SetPhase1 sets field value
func (o *IPSecSingleTunnel) SetPhase1(v IPSecPhaseConfig) {
	o.Phase1 = v
}

// GetPhase2 returns the Phase2 field value
func (o *IPSecSingleTunnel) GetPhase2() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetPhase2Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase2, true
}

// SetPhase2 sets field value
func (o *IPSecSingleTunnel) SetPhase2(v IPSecPhaseConfig) {
	o.Phase2 = v
}

// GetPassphrase returns the Passphrase field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetPassphrase() string {
	if o == nil || IsNil(o.Passphrase) {
		var ret string
		return ret
	}
	return *o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetPassphraseOk() (*string, bool) {
	if o == nil || IsNil(o.Passphrase) {
		return nil, false
	}
	return o.Passphrase, true
}

// HasPassphrase returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasPassphrase() bool {
	if o != nil && !IsNil(o.Passphrase) {
		return true
	}

	return false
}

// SetPassphrase gets a reference to the given string and assigns it to the Passphrase field.
func (o *IPSecSingleTunnel) SetPassphrase(v string) {
	o.Passphrase = &v
}

// GetRemotePublicIP returns the RemotePublicIP field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetRemotePublicIP() string {
	if o == nil || IsNil(o.RemotePublicIP) {
		var ret string
		return ret
	}
	return *o.RemotePublicIP
}

// GetRemotePublicIPOk returns a tuple with the RemotePublicIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetRemotePublicIPOk() (*string, bool) {
	if o == nil || IsNil(o.RemotePublicIP) {
		return nil, false
	}
	return o.RemotePublicIP, true
}

// HasRemotePublicIP returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasRemotePublicIP() bool {
	if o != nil && !IsNil(o.RemotePublicIP) {
		return true
	}

	return false
}

// SetRemotePublicIP gets a reference to the given string and assigns it to the RemotePublicIP field.
func (o *IPSecSingleTunnel) SetRemotePublicIP(v string) {
	o.RemotePublicIP = &v
}

// GetRemoteID returns the RemoteID field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetRemoteID() RemoteID {
	if o == nil || IsNil(o.RemoteID) {
		var ret RemoteID
		return ret
	}
	return *o.RemoteID
}

// GetRemoteIDOk returns a tuple with the RemoteID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetRemoteIDOk() (*RemoteID, bool) {
	if o == nil || IsNil(o.RemoteID) {
		return nil, false
	}
	return o.RemoteID, true
}

// HasRemoteID returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasRemoteID() bool {
	if o != nil && !IsNil(o.RemoteID) {
		return true
	}

	return false
}

// SetRemoteID gets a reference to the given RemoteID and assigns it to the RemoteID field.
func (o *IPSecSingleTunnel) SetRemoteID(v RemoteID) {
	o.RemoteID = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IPSecSingleTunnel) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IPSecSingleTunnel) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IPSecSingleTunnel) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *IPSecSingleTunnel) SetType(v string) {
	o.Type = &v
}

// GetTunnelID returns the TunnelID field value if set, zero value otherwise.
func (o *IPSecSingleTunnel) GetTunnelID() string {
	if o == nil || IsNil(o.TunnelID) {
		var ret string
		return ret
	}
	return *o.TunnelID
}

// GetTunnelIDOk returns a tuple with the TunnelID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSingleTunnel) GetTunnelIDOk() (*string, bool) {
	if o == nil || IsNil(o.TunnelID) {
		return nil, false
	}
	return o.TunnelID, true
}

// HasTunnelID returns a boolean if a field has been set.
func (o *IPSecSingleTunnel) HasTunnelID() bool {
	if o != nil && !IsNil(o.TunnelID) {
		return true
	}

	return false
}

// SetTunnelID gets a reference to the given string and assigns it to the TunnelID field.
func (o *IPSecSingleTunnel) SetTunnelID(v string) {
	o.TunnelID = &v
}

func (o IPSecSingleTunnel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecSingleTunnel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionID"] = o.RegionID
	toSerialize["gatewayID"] = o.GatewayID
	toSerialize["tunnelName"] = o.TunnelName
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	if !IsNil(o.PeakBandwidth) {
		toSerialize["peakBandwidth"] = o.PeakBandwidth
	}
	if !IsNil(o.P81ASN) {
		toSerialize["p81ASN"] = o.P81ASN
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	toSerialize["keyExchange"] = o.KeyExchange
	toSerialize["ikeLifeTime"] = o.IkeLifeTime
	toSerialize["lifetime"] = o.Lifetime
	toSerialize["dpdDelay"] = o.DpdDelay
	toSerialize["dpdTimeout"] = o.DpdTimeout
	toSerialize["phase1"] = o.Phase1
	toSerialize["phase2"] = o.Phase2
	if !IsNil(o.Passphrase) {
		toSerialize["passphrase"] = o.Passphrase
	}
	if !IsNil(o.RemotePublicIP) {
		toSerialize["remotePublicIP"] = o.RemotePublicIP
	}
	if !IsNil(o.RemoteID) {
		toSerialize["remoteID"] = o.RemoteID
	}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.TunnelID) {
		toSerialize["tunnelID"] = o.TunnelID
	}
	return toSerialize, nil
}

func (o *IPSecSingleTunnel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionID",
		"gatewayID",
		"tunnelName",
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"keyExchange",
		"ikeLifeTime",
		"lifetime",
		"dpdDelay",
		"dpdTimeout",
		"phase1",
		"phase2",
		"createdAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecSingleTunnel := _IPSecSingleTunnel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varIPSecSingleTunnel)

	if err != nil {
		return err
	}

	*o = IPSecSingleTunnel(varIPSecSingleTunnel)

	return err
}

type NullableIPSecSingleTunnel struct {
	value *IPSecSingleTunnel
	isSet bool
}

func (v NullableIPSecSingleTunnel) Get() *IPSecSingleTunnel {
	return v.value
}

func (v *NullableIPSecSingleTunnel) Set(val *IPSecSingleTunnel) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecSingleTunnel) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecSingleTunnel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecSingleTunnel(val *IPSecSingleTunnel) *NullableIPSecSingleTunnel {
	return &NullableIPSecSingleTunnel{value: val, isSet: true}
}

func (v NullableIPSecSingleTunnel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecSingleTunnel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


