/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectServiceProtocolICMPRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectServiceProtocolICMPRequest{}

// ObjectServiceProtocolICMPRequest struct for ObjectServiceProtocolICMPRequest
type ObjectServiceProtocolICMPRequest struct {
	Protocol string `json:"protocol"`
	ProtocolOptions ObjectServiceProtocolOptionsICMPrequest `json:"protocolOptions"`
}

type _ObjectServiceProtocolICMPRequest ObjectServiceProtocolICMPRequest

// NewObjectServiceProtocolICMPRequest instantiates a new ObjectServiceProtocolICMPRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectServiceProtocolICMPRequest(protocol string, protocolOptions ObjectServiceProtocolOptionsICMPrequest) *ObjectServiceProtocolICMPRequest {
	this := ObjectServiceProtocolICMPRequest{}
	this.Protocol = protocol
	this.ProtocolOptions = protocolOptions
	return &this
}

// NewObjectServiceProtocolICMPRequestWithDefaults instantiates a new ObjectServiceProtocolICMPRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectServiceProtocolICMPRequestWithDefaults() *ObjectServiceProtocolICMPRequest {
	this := ObjectServiceProtocolICMPRequest{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *ObjectServiceProtocolICMPRequest) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *ObjectServiceProtocolICMPRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *ObjectServiceProtocolICMPRequest) SetProtocol(v string) {
	o.Protocol = v
}

// GetProtocolOptions returns the ProtocolOptions field value
func (o *ObjectServiceProtocolICMPRequest) GetProtocolOptions() ObjectServiceProtocolOptionsICMPrequest {
	if o == nil {
		var ret ObjectServiceProtocolOptionsICMPrequest
		return ret
	}

	return o.ProtocolOptions
}

// GetProtocolOptionsOk returns a tuple with the ProtocolOptions field value
// and a boolean to check if the value has been set.
func (o *ObjectServiceProtocolICMPRequest) GetProtocolOptionsOk() (*ObjectServiceProtocolOptionsICMPrequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolOptions, true
}

// SetProtocolOptions sets field value
func (o *ObjectServiceProtocolICMPRequest) SetProtocolOptions(v ObjectServiceProtocolOptionsICMPrequest) {
	o.ProtocolOptions = v
}

func (o ObjectServiceProtocolICMPRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectServiceProtocolICMPRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["protocolOptions"] = o.ProtocolOptions
	return toSerialize, nil
}

func (o *ObjectServiceProtocolICMPRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"protocolOptions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectServiceProtocolICMPRequest := _ObjectServiceProtocolICMPRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varObjectServiceProtocolICMPRequest)

	if err != nil {
		return err
	}

	*o = ObjectServiceProtocolICMPRequest(varObjectServiceProtocolICMPRequest)

	return err
}

type NullableObjectServiceProtocolICMPRequest struct {
	value *ObjectServiceProtocolICMPRequest
	isSet bool
}

func (v NullableObjectServiceProtocolICMPRequest) Get() *ObjectServiceProtocolICMPRequest {
	return v.value
}

func (v *NullableObjectServiceProtocolICMPRequest) Set(val *ObjectServiceProtocolICMPRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectServiceProtocolICMPRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectServiceProtocolICMPRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectServiceProtocolICMPRequest(val *ObjectServiceProtocolICMPRequest) *NullableObjectServiceProtocolICMPRequest {
	return &NullableObjectServiceProtocolICMPRequest{value: val, isSet: true}
}

func (v NullableObjectServiceProtocolICMPRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectServiceProtocolICMPRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


