/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IPSecPhaseCommon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecPhaseCommon{}

// IPSecPhaseCommon struct for IPSecPhaseCommon
type IPSecPhaseCommon struct {
	// Diffie Helman encryption
	Dh []int32 `json:"dh"`
}

type _IPSecPhaseCommon IPSecPhaseCommon

// NewIPSecPhaseCommon instantiates a new IPSecPhaseCommon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecPhaseCommon(dh []int32) *IPSecPhaseCommon {
	this := IPSecPhaseCommon{}
	this.Dh = dh
	return &this
}

// NewIPSecPhaseCommonWithDefaults instantiates a new IPSecPhaseCommon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecPhaseCommonWithDefaults() *IPSecPhaseCommon {
	this := IPSecPhaseCommon{}
	return &this
}

// GetDh returns the Dh field value
func (o *IPSecPhaseCommon) GetDh() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Dh
}

// GetDhOk returns a tuple with the Dh field value
// and a boolean to check if the value has been set.
func (o *IPSecPhaseCommon) GetDhOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dh, true
}

// SetDh sets field value
func (o *IPSecPhaseCommon) SetDh(v []int32) {
	o.Dh = v
}

func (o IPSecPhaseCommon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecPhaseCommon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dh"] = o.Dh
	return toSerialize, nil
}

func (o *IPSecPhaseCommon) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dh",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecPhaseCommon := _IPSecPhaseCommon{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIPSecPhaseCommon)

	if err != nil {
		return err
	}

	*o = IPSecPhaseCommon(varIPSecPhaseCommon)

	return err
}

type NullableIPSecPhaseCommon struct {
	value *IPSecPhaseCommon
	isSet bool
}

func (v NullableIPSecPhaseCommon) Get() *IPSecPhaseCommon {
	return v.value
}

func (v *NullableIPSecPhaseCommon) Set(val *IPSecPhaseCommon) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecPhaseCommon) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecPhaseCommon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecPhaseCommon(val *IPSecPhaseCommon) *NullableIPSecPhaseCommon {
	return &NullableIPSecPhaseCommon{value: val, isSet: true}
}

func (v NullableIPSecPhaseCommon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecPhaseCommon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


