/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the RemoteASN type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoteASN{}

// RemoteASN struct for RemoteASN
type RemoteASN struct {
}

// NewRemoteASN instantiates a new RemoteASN object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoteASN() *RemoteASN {
	this := RemoteASN{}
	return &this
}

// NewRemoteASNWithDefaults instantiates a new RemoteASN object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoteASNWithDefaults() *RemoteASN {
	this := RemoteASN{}
	return &this
}

func (o RemoteASN) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoteASN) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableRemoteASN struct {
	value *RemoteASN
	isSet bool
}

func (v NullableRemoteASN) Get() *RemoteASN {
	return v.value
}

func (v *NullableRemoteASN) Set(val *RemoteASN) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoteASN) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoteASN) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoteASN(val *RemoteASN) *NullableRemoteASN {
	return &NullableRemoteASN{value: val, isSet: true}
}

func (v NullableRemoteASN) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoteASN) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


