/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
)


// NetworkTunnel struct for NetworkTunnel
type NetworkTunnel struct {
	NetworkTunnelIpsecRedundant *NetworkTunnelIpsecRedundant
	NetworkTunnelIpsecSingle *NetworkTunnelIpsecSingle
	NetworkTunnelOpenvpn *NetworkTunnelOpenvpn
	NetworkTunnelWireguard *NetworkTunnelWireguard
	// Fallback for tunnel types not covered by the anyOf variants (e.g. "connector").
	NetworkTunnelBase *NetworkTunnelBase
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *NetworkTunnel) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into NetworkTunnelIpsecRedundant
	err = json.Unmarshal(data, &dst.NetworkTunnelIpsecRedundant);
	if err == nil {
		jsonNetworkTunnelIpsecRedundant, _ := json.Marshal(dst.NetworkTunnelIpsecRedundant)
		if string(jsonNetworkTunnelIpsecRedundant) == "{}" { // empty struct
			dst.NetworkTunnelIpsecRedundant = nil
		} else {
			return nil // data stored in dst.NetworkTunnelIpsecRedundant, return on the first match
		}
	} else {
		dst.NetworkTunnelIpsecRedundant = nil
	}

	// try to unmarshal JSON data into NetworkTunnelIpsecSingle
	err = json.Unmarshal(data, &dst.NetworkTunnelIpsecSingle);
	if err == nil {
		jsonNetworkTunnelIpsecSingle, _ := json.Marshal(dst.NetworkTunnelIpsecSingle)
		if string(jsonNetworkTunnelIpsecSingle) == "{}" { // empty struct
			dst.NetworkTunnelIpsecSingle = nil
		} else {
			return nil // data stored in dst.NetworkTunnelIpsecSingle, return on the first match
		}
	} else {
		dst.NetworkTunnelIpsecSingle = nil
	}

	// try to unmarshal JSON data into NetworkTunnelOpenvpn
	err = json.Unmarshal(data, &dst.NetworkTunnelOpenvpn);
	if err == nil {
		jsonNetworkTunnelOpenvpn, _ := json.Marshal(dst.NetworkTunnelOpenvpn)
		if string(jsonNetworkTunnelOpenvpn) == "{}" { // empty struct
			dst.NetworkTunnelOpenvpn = nil
		} else {
			return nil // data stored in dst.NetworkTunnelOpenvpn, return on the first match
		}
	} else {
		dst.NetworkTunnelOpenvpn = nil
	}

	// try to unmarshal JSON data into NetworkTunnelWireguard
	err = json.Unmarshal(data, &dst.NetworkTunnelWireguard);
	if err == nil {
		jsonNetworkTunnelWireguard, _ := json.Marshal(dst.NetworkTunnelWireguard)
		if string(jsonNetworkTunnelWireguard) == "{}" { // empty struct
			dst.NetworkTunnelWireguard = nil
		} else {
			return nil // data stored in dst.NetworkTunnelWireguard, return on the first match
		}
	} else {
		dst.NetworkTunnelWireguard = nil
	}

	// None of the specific tunnel types matched — fall back to the base tunnel type
	// which captures common fields (id, network, region, instance, type, etc.).
	// Use a plain struct (not the generated one) to avoid DisallowUnknownFields rejection.
	var raw struct {
		Id            string `json:"id"`
		Network       string `json:"network"`
		Region        string `json:"region"`
		Instance      string `json:"instance"`
		InterfaceName string `json:"interfaceName"`
		Type          string `json:"type"`
		IsHA          bool   `json:"isHA"`
		TenantId      string `json:"tenantId"`
	}
	if err = json.Unmarshal(data, &raw); err == nil && raw.Id != "" {
		dst.NetworkTunnelBase = &NetworkTunnelBase{
			Id:            raw.Id,
			Network:       raw.Network,
			Region:        raw.Region,
			Instance:      raw.Instance,
			InterfaceName: raw.InterfaceName,
			Type:          raw.Type,
			IsHA:          raw.IsHA,
			TenantId:      raw.TenantId,
		}
		return nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(NetworkTunnel)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NetworkTunnel) MarshalJSON() ([]byte, error) {
	if src.NetworkTunnelIpsecRedundant != nil {
		return json.Marshal(&src.NetworkTunnelIpsecRedundant)
	}

	if src.NetworkTunnelIpsecSingle != nil {
		return json.Marshal(&src.NetworkTunnelIpsecSingle)
	}

	if src.NetworkTunnelOpenvpn != nil {
		return json.Marshal(&src.NetworkTunnelOpenvpn)
	}

	if src.NetworkTunnelWireguard != nil {
		return json.Marshal(&src.NetworkTunnelWireguard)
	}

	if src.NetworkTunnelBase != nil {
		return json.Marshal(&src.NetworkTunnelBase)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableNetworkTunnel struct {
	value *NetworkTunnel
	isSet bool
}

func (v NullableNetworkTunnel) Get() *NetworkTunnel {
	return v.value
}

func (v *NullableNetworkTunnel) Set(val *NetworkTunnel) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkTunnel) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkTunnel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkTunnel(val *NetworkTunnel) *NullableNetworkTunnel {
	return &NullableNetworkTunnel{value: val, isSet: true}
}

func (v NullableNetworkTunnel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkTunnel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


