/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommonApplicationPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonApplicationPolicy{}

// CommonApplicationPolicy Application related Policy data
type CommonApplicationPolicy struct {
	// Policy Id
	Id string `json:"id"`
	// Policy name
	Name string `json:"name"`
}

type _CommonApplicationPolicy CommonApplicationPolicy

// NewCommonApplicationPolicy instantiates a new CommonApplicationPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonApplicationPolicy(id string, name string) *CommonApplicationPolicy {
	this := CommonApplicationPolicy{}
	this.Id = id
	this.Name = name
	return &this
}

// NewCommonApplicationPolicyWithDefaults instantiates a new CommonApplicationPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonApplicationPolicyWithDefaults() *CommonApplicationPolicy {
	this := CommonApplicationPolicy{}
	return &this
}

// GetId returns the Id field value
func (o *CommonApplicationPolicy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CommonApplicationPolicy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CommonApplicationPolicy) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CommonApplicationPolicy) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CommonApplicationPolicy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CommonApplicationPolicy) SetName(v string) {
	o.Name = v
}

func (o CommonApplicationPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonApplicationPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CommonApplicationPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonApplicationPolicy := _CommonApplicationPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCommonApplicationPolicy)

	if err != nil {
		return err
	}

	*o = CommonApplicationPolicy(varCommonApplicationPolicy)

	return err
}

type NullableCommonApplicationPolicy struct {
	value *CommonApplicationPolicy
	isSet bool
}

func (v NullableCommonApplicationPolicy) Get() *CommonApplicationPolicy {
	return v.value
}

func (v *NullableCommonApplicationPolicy) Set(val *CommonApplicationPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonApplicationPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonApplicationPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonApplicationPolicy(val *CommonApplicationPolicy) *NullableCommonApplicationPolicy {
	return &NullableCommonApplicationPolicy{value: val, isSet: true}
}

func (v NullableCommonApplicationPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonApplicationPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


