/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NetworkInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkInstance{}

// NetworkInstance struct for NetworkInstance
type NetworkInstance struct {
	// The date when this record was created.
	CreatedAt time.Time `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// ID of the network.
	Network string `json:"network"`
	// ID of the network region.
	Region string `json:"region"`
	InstanceType string `json:"instanceType"`
	ImageType string `json:"imageType"`
	ImageVersion string `json:"imageVersion"`
	Dns string `json:"dns"`
	Ip string `json:"ip"`
	// List of network tunnels.
	Tunnels []NetworkTunnel `json:"tunnels"`
	// Unique ID.
	Id string `json:"id"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
}

type _NetworkInstance NetworkInstance

// NewNetworkInstance instantiates a new NetworkInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkInstance(createdAt time.Time, network string, region string, instanceType string, imageType string, imageVersion string, dns string, ip string, tunnels []NetworkTunnel, id string, tenantId string) *NetworkInstance {
	this := NetworkInstance{}
	this.CreatedAt = createdAt
	this.Network = network
	this.Region = region
	this.InstanceType = instanceType
	this.ImageType = imageType
	this.ImageVersion = imageVersion
	this.Dns = dns
	this.Ip = ip
	this.Tunnels = tunnels
	this.Id = id
	this.TenantId = tenantId
	return &this
}

// NewNetworkInstanceWithDefaults instantiates a new NetworkInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkInstanceWithDefaults() *NetworkInstance {
	this := NetworkInstance{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *NetworkInstance) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NetworkInstance) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *NetworkInstance) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *NetworkInstance) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *NetworkInstance) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetNetwork returns the Network field value
func (o *NetworkInstance) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NetworkInstance) SetNetwork(v string) {
	o.Network = v
}

// GetRegion returns the Region field value
func (o *NetworkInstance) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *NetworkInstance) SetRegion(v string) {
	o.Region = v
}

// GetInstanceType returns the InstanceType field value
func (o *NetworkInstance) GetInstanceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetInstanceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InstanceType, true
}

// SetInstanceType sets field value
func (o *NetworkInstance) SetInstanceType(v string) {
	o.InstanceType = v
}

// GetImageType returns the ImageType field value
func (o *NetworkInstance) GetImageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageType
}

// GetImageTypeOk returns a tuple with the ImageType field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetImageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageType, true
}

// SetImageType sets field value
func (o *NetworkInstance) SetImageType(v string) {
	o.ImageType = v
}

// GetImageVersion returns the ImageVersion field value
func (o *NetworkInstance) GetImageVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageVersion
}

// GetImageVersionOk returns a tuple with the ImageVersion field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetImageVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageVersion, true
}

// SetImageVersion sets field value
func (o *NetworkInstance) SetImageVersion(v string) {
	o.ImageVersion = v
}

// GetDns returns the Dns field value
func (o *NetworkInstance) GetDns() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dns
}

// GetDnsOk returns a tuple with the Dns field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetDnsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dns, true
}

// SetDns sets field value
func (o *NetworkInstance) SetDns(v string) {
	o.Dns = v
}

// GetIp returns the Ip field value
func (o *NetworkInstance) GetIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ip
}

// GetIpOk returns a tuple with the Ip field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ip, true
}

// SetIp sets field value
func (o *NetworkInstance) SetIp(v string) {
	o.Ip = v
}

// GetTunnels returns the Tunnels field value
func (o *NetworkInstance) GetTunnels() []NetworkTunnel {
	if o == nil {
		var ret []NetworkTunnel
		return ret
	}

	return o.Tunnels
}

// GetTunnelsOk returns a tuple with the Tunnels field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetTunnelsOk() ([]NetworkTunnel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tunnels, true
}

// SetTunnels sets field value
func (o *NetworkInstance) SetTunnels(v []NetworkTunnel) {
	o.Tunnels = v
}

// GetId returns the Id field value
func (o *NetworkInstance) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkInstance) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *NetworkInstance) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *NetworkInstance) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *NetworkInstance) SetTenantId(v string) {
	o.TenantId = v
}

func (o NetworkInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["network"] = o.Network
	toSerialize["region"] = o.Region
	toSerialize["instanceType"] = o.InstanceType
	toSerialize["imageType"] = o.ImageType
	toSerialize["imageVersion"] = o.ImageVersion
	toSerialize["dns"] = o.Dns
	toSerialize["ip"] = o.Ip
	toSerialize["tunnels"] = o.Tunnels
	toSerialize["id"] = o.Id
	toSerialize["tenantId"] = o.TenantId
	return toSerialize, nil
}

func (o *NetworkInstance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"network",
		"region",
		"instanceType",
		"imageType",
		"imageVersion",
		"dns",
		"ip",
		"tunnels",
		"id",
		"tenantId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkInstance := _NetworkInstance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varNetworkInstance)

	if err != nil {
		return err
	}

	*o = NetworkInstance(varNetworkInstance)

	return err
}

type NullableNetworkInstance struct {
	value *NetworkInstance
	isSet bool
}

func (v NullableNetworkInstance) Get() *NetworkInstance {
	return v.value
}

func (v *NullableNetworkInstance) Set(val *NetworkInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkInstance(val *NetworkInstance) *NullableNetworkInstance {
	return &NullableNetworkInstance{value: val, isSet: true}
}

func (v NullableNetworkInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


