/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationHost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationHost{}

// ApplicationHost Application host settings
type ApplicationHost struct {
	Value string `json:"value"`
	Source string `json:"source"`
}

type _ApplicationHost ApplicationHost

// NewApplicationHost instantiates a new ApplicationHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationHost(value string, source string) *ApplicationHost {
	this := ApplicationHost{}
	this.Value = value
	this.Source = source
	return &this
}

// NewApplicationHostWithDefaults instantiates a new ApplicationHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationHostWithDefaults() *ApplicationHost {
	this := ApplicationHost{}
	return &this
}

// GetValue returns the Value field value
func (o *ApplicationHost) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ApplicationHost) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApplicationHost) SetValue(v string) {
	o.Value = v
}

// GetSource returns the Source field value
func (o *ApplicationHost) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *ApplicationHost) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *ApplicationHost) SetSource(v string) {
	o.Source = v
}

func (o ApplicationHost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationHost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *ApplicationHost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationHost := _ApplicationHost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApplicationHost)

	if err != nil {
		return err
	}

	*o = ApplicationHost(varApplicationHost)

	return err
}

type NullableApplicationHost struct {
	value *ApplicationHost
	isSet bool
}

func (v NullableApplicationHost) Get() *ApplicationHost {
	return v.value
}

func (v *NullableApplicationHost) Set(val *ApplicationHost) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationHost) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationHost(val *ApplicationHost) *NullableApplicationHost {
	return &NullableApplicationHost{value: val, isSet: true}
}

func (v NullableApplicationHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


