/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the IPSecAdvancedSettingsUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecAdvancedSettingsUpdate{}

// IPSecAdvancedSettingsUpdate struct for IPSecAdvancedSettingsUpdate
type IPSecAdvancedSettingsUpdate struct {
	KeyExchange *string `json:"keyExchange,omitempty"`
	IkeLifeTime *string `json:"ikeLifeTime,omitempty" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime *string `json:"lifetime,omitempty" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay *string `json:"dpdDelay,omitempty" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout *string `json:"dpdTimeout,omitempty" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 *IPSecPhaseConfig `json:"phase1,omitempty"`
	Phase2 *IPSecPhaseConfig `json:"phase2,omitempty"`
}

// NewIPSecAdvancedSettingsUpdate instantiates a new IPSecAdvancedSettingsUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecAdvancedSettingsUpdate() *IPSecAdvancedSettingsUpdate {
	this := IPSecAdvancedSettingsUpdate{}
	return &this
}

// NewIPSecAdvancedSettingsUpdateWithDefaults instantiates a new IPSecAdvancedSettingsUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecAdvancedSettingsUpdateWithDefaults() *IPSecAdvancedSettingsUpdate {
	this := IPSecAdvancedSettingsUpdate{}
	return &this
}

// GetKeyExchange returns the KeyExchange field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetKeyExchange() string {
	if o == nil || IsNil(o.KeyExchange) {
		var ret string
		return ret
	}
	return *o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetKeyExchangeOk() (*string, bool) {
	if o == nil || IsNil(o.KeyExchange) {
		return nil, false
	}
	return o.KeyExchange, true
}

// HasKeyExchange returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasKeyExchange() bool {
	if o != nil && !IsNil(o.KeyExchange) {
		return true
	}

	return false
}

// SetKeyExchange gets a reference to the given string and assigns it to the KeyExchange field.
func (o *IPSecAdvancedSettingsUpdate) SetKeyExchange(v string) {
	o.KeyExchange = &v
}

// GetIkeLifeTime returns the IkeLifeTime field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetIkeLifeTime() string {
	if o == nil || IsNil(o.IkeLifeTime) {
		var ret string
		return ret
	}
	return *o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil || IsNil(o.IkeLifeTime) {
		return nil, false
	}
	return o.IkeLifeTime, true
}

// HasIkeLifeTime returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasIkeLifeTime() bool {
	if o != nil && !IsNil(o.IkeLifeTime) {
		return true
	}

	return false
}

// SetIkeLifeTime gets a reference to the given string and assigns it to the IkeLifeTime field.
func (o *IPSecAdvancedSettingsUpdate) SetIkeLifeTime(v string) {
	o.IkeLifeTime = &v
}

// GetLifetime returns the Lifetime field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetLifetime() string {
	if o == nil || IsNil(o.Lifetime) {
		var ret string
		return ret
	}
	return *o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.Lifetime) {
		return nil, false
	}
	return o.Lifetime, true
}

// HasLifetime returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasLifetime() bool {
	if o != nil && !IsNil(o.Lifetime) {
		return true
	}

	return false
}

// SetLifetime gets a reference to the given string and assigns it to the Lifetime field.
func (o *IPSecAdvancedSettingsUpdate) SetLifetime(v string) {
	o.Lifetime = &v
}

// GetDpdDelay returns the DpdDelay field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetDpdDelay() string {
	if o == nil || IsNil(o.DpdDelay) {
		var ret string
		return ret
	}
	return *o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetDpdDelayOk() (*string, bool) {
	if o == nil || IsNil(o.DpdDelay) {
		return nil, false
	}
	return o.DpdDelay, true
}

// HasDpdDelay returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasDpdDelay() bool {
	if o != nil && !IsNil(o.DpdDelay) {
		return true
	}

	return false
}

// SetDpdDelay gets a reference to the given string and assigns it to the DpdDelay field.
func (o *IPSecAdvancedSettingsUpdate) SetDpdDelay(v string) {
	o.DpdDelay = &v
}

// GetDpdTimeout returns the DpdTimeout field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetDpdTimeout() string {
	if o == nil || IsNil(o.DpdTimeout) {
		var ret string
		return ret
	}
	return *o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetDpdTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.DpdTimeout) {
		return nil, false
	}
	return o.DpdTimeout, true
}

// HasDpdTimeout returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasDpdTimeout() bool {
	if o != nil && !IsNil(o.DpdTimeout) {
		return true
	}

	return false
}

// SetDpdTimeout gets a reference to the given string and assigns it to the DpdTimeout field.
func (o *IPSecAdvancedSettingsUpdate) SetDpdTimeout(v string) {
	o.DpdTimeout = &v
}

// GetPhase1 returns the Phase1 field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetPhase1() IPSecPhaseConfig {
	if o == nil || IsNil(o.Phase1) {
		var ret IPSecPhaseConfig
		return ret
	}
	return *o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetPhase1Ok() (*IPSecPhaseConfig, bool) {
	if o == nil || IsNil(o.Phase1) {
		return nil, false
	}
	return o.Phase1, true
}

// HasPhase1 returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasPhase1() bool {
	if o != nil && !IsNil(o.Phase1) {
		return true
	}

	return false
}

// SetPhase1 gets a reference to the given IPSecPhaseConfig and assigns it to the Phase1 field.
func (o *IPSecAdvancedSettingsUpdate) SetPhase1(v IPSecPhaseConfig) {
	o.Phase1 = &v
}

// GetPhase2 returns the Phase2 field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdate) GetPhase2() IPSecPhaseConfig {
	if o == nil || IsNil(o.Phase2) {
		var ret IPSecPhaseConfig
		return ret
	}
	return *o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdate) GetPhase2Ok() (*IPSecPhaseConfig, bool) {
	if o == nil || IsNil(o.Phase2) {
		return nil, false
	}
	return o.Phase2, true
}

// HasPhase2 returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdate) HasPhase2() bool {
	if o != nil && !IsNil(o.Phase2) {
		return true
	}

	return false
}

// SetPhase2 gets a reference to the given IPSecPhaseConfig and assigns it to the Phase2 field.
func (o *IPSecAdvancedSettingsUpdate) SetPhase2(v IPSecPhaseConfig) {
	o.Phase2 = &v
}

func (o IPSecAdvancedSettingsUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecAdvancedSettingsUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyExchange) {
		toSerialize["keyExchange"] = o.KeyExchange
	}
	if !IsNil(o.IkeLifeTime) {
		toSerialize["ikeLifeTime"] = o.IkeLifeTime
	}
	if !IsNil(o.Lifetime) {
		toSerialize["lifetime"] = o.Lifetime
	}
	if !IsNil(o.DpdDelay) {
		toSerialize["dpdDelay"] = o.DpdDelay
	}
	if !IsNil(o.DpdTimeout) {
		toSerialize["dpdTimeout"] = o.DpdTimeout
	}
	if !IsNil(o.Phase1) {
		toSerialize["phase1"] = o.Phase1
	}
	if !IsNil(o.Phase2) {
		toSerialize["phase2"] = o.Phase2
	}
	return toSerialize, nil
}

type NullableIPSecAdvancedSettingsUpdate struct {
	value *IPSecAdvancedSettingsUpdate
	isSet bool
}

func (v NullableIPSecAdvancedSettingsUpdate) Get() *IPSecAdvancedSettingsUpdate {
	return v.value
}

func (v *NullableIPSecAdvancedSettingsUpdate) Set(val *IPSecAdvancedSettingsUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecAdvancedSettingsUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecAdvancedSettingsUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecAdvancedSettingsUpdate(val *IPSecAdvancedSettingsUpdate) *NullableIPSecAdvancedSettingsUpdate {
	return &NullableIPSecAdvancedSettingsUpdate{value: val, isSet: true}
}

func (v NullableIPSecAdvancedSettingsUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecAdvancedSettingsUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


