/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectsAddressObj type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectsAddressObj{}

// ObjectsAddressObj struct for ObjectsAddressObj
type ObjectsAddressObj struct {
	// Unique Address ID
	Id *string `json:"id,omitempty"`
	// The name of the Objects
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9_ ]+$"`
	Description *string `json:"description,omitempty"`
	ValueType string `json:"valueType"`
	Value []string `json:"value"`
}

type _ObjectsAddressObj ObjectsAddressObj

// NewObjectsAddressObj instantiates a new ObjectsAddressObj object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectsAddressObj(name string, valueType string, value []string) *ObjectsAddressObj {
	this := ObjectsAddressObj{}
	this.Name = name
	this.ValueType = valueType
	this.Value = value
	return &this
}

// NewObjectsAddressObjWithDefaults instantiates a new ObjectsAddressObj object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectsAddressObjWithDefaults() *ObjectsAddressObj {
	this := ObjectsAddressObj{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ObjectsAddressObj) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectsAddressObj) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ObjectsAddressObj) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ObjectsAddressObj) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *ObjectsAddressObj) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectsAddressObj) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectsAddressObj) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ObjectsAddressObj) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectsAddressObj) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ObjectsAddressObj) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ObjectsAddressObj) SetDescription(v string) {
	o.Description = &v
}

// GetValueType returns the ValueType field value
func (o *ObjectsAddressObj) GetValueType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValueType
}

// GetValueTypeOk returns a tuple with the ValueType field value
// and a boolean to check if the value has been set.
func (o *ObjectsAddressObj) GetValueTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValueType, true
}

// SetValueType sets field value
func (o *ObjectsAddressObj) SetValueType(v string) {
	o.ValueType = v
}

// GetValue returns the Value field value
func (o *ObjectsAddressObj) GetValue() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ObjectsAddressObj) GetValueOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *ObjectsAddressObj) SetValue(v []string) {
	o.Value = v
}

func (o ObjectsAddressObj) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectsAddressObj) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["valueType"] = o.ValueType
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ObjectsAddressObj) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"valueType",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectsAddressObj := _ObjectsAddressObj{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectsAddressObj)

	if err != nil {
		return err
	}

	*o = ObjectsAddressObj(varObjectsAddressObj)

	return err
}

type NullableObjectsAddressObj struct {
	value *ObjectsAddressObj
	isSet bool
}

func (v NullableObjectsAddressObj) Get() *ObjectsAddressObj {
	return v.value
}

func (v *NullableObjectsAddressObj) Set(val *ObjectsAddressObj) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectsAddressObj) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectsAddressObj) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectsAddressObj(val *ObjectsAddressObj) *NullableObjectsAddressObj {
	return &NullableObjectsAddressObj{value: val, isSet: true}
}

func (v NullableObjectsAddressObj) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectsAddressObj) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


