/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NetworkHaTunnelID type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkHaTunnelID{}

// NetworkHaTunnelID struct for NetworkHaTunnelID
type NetworkHaTunnelID struct {
	// The date when this record was created.
	CreatedAt time.Time `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// ID of the network.
	Network string `json:"network"`
	Tunnels []string `json:"tunnels"`
	Type string `json:"type" validate:"regexp=ipsec"`
	// tenantId.
	TenantId string `json:"tenantId"`
	// id.
	Id string `json:"id"`
}

type _NetworkHaTunnelID NetworkHaTunnelID

// NewNetworkHaTunnelID instantiates a new NetworkHaTunnelID object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkHaTunnelID(createdAt time.Time, network string, tunnels []string, type_ string, tenantId string, id string) *NetworkHaTunnelID {
	this := NetworkHaTunnelID{}
	this.CreatedAt = createdAt
	this.Network = network
	this.Tunnels = tunnels
	this.Type = type_
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewNetworkHaTunnelIDWithDefaults instantiates a new NetworkHaTunnelID object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkHaTunnelIDWithDefaults() *NetworkHaTunnelID {
	this := NetworkHaTunnelID{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *NetworkHaTunnelID) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NetworkHaTunnelID) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *NetworkHaTunnelID) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *NetworkHaTunnelID) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *NetworkHaTunnelID) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetNetwork returns the Network field value
func (o *NetworkHaTunnelID) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NetworkHaTunnelID) SetNetwork(v string) {
	o.Network = v
}

// GetTunnels returns the Tunnels field value
func (o *NetworkHaTunnelID) GetTunnels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tunnels
}

// GetTunnelsOk returns a tuple with the Tunnels field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetTunnelsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tunnels, true
}

// SetTunnels sets field value
func (o *NetworkHaTunnelID) SetTunnels(v []string) {
	o.Tunnels = v
}

// GetType returns the Type field value
func (o *NetworkHaTunnelID) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NetworkHaTunnelID) SetType(v string) {
	o.Type = v
}

// GetTenantId returns the TenantId field value
func (o *NetworkHaTunnelID) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *NetworkHaTunnelID) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *NetworkHaTunnelID) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkHaTunnelID) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkHaTunnelID) SetId(v string) {
	o.Id = v
}

func (o NetworkHaTunnelID) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkHaTunnelID) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["network"] = o.Network
	toSerialize["tunnels"] = o.Tunnels
	toSerialize["type"] = o.Type
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *NetworkHaTunnelID) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"createdAt",
		"network",
		"tunnels",
		"type",
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkHaTunnelID := _NetworkHaTunnelID{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varNetworkHaTunnelID)

	if err != nil {
		return err
	}

	*o = NetworkHaTunnelID(varNetworkHaTunnelID)

	return err
}

type NullableNetworkHaTunnelID struct {
	value *NetworkHaTunnelID
	isSet bool
}

func (v NullableNetworkHaTunnelID) Get() *NetworkHaTunnelID {
	return v.value
}

func (v *NullableNetworkHaTunnelID) Set(val *NetworkHaTunnelID) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkHaTunnelID) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkHaTunnelID) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkHaTunnelID(val *NetworkHaTunnelID) *NullableNetworkHaTunnelID {
	return &NullableNetworkHaTunnelID{value: val, isSet: true}
}

func (v NullableNetworkHaTunnelID) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkHaTunnelID) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


