/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateInstancesInNetworkPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateInstancesInNetworkPayload{}

// CreateInstancesInNetworkPayload struct for CreateInstancesInNetworkPayload
type CreateInstancesInNetworkPayload struct {
	// Region ID.
	RegionId string `json:"regionId"`
	// Create the gateway as disabled if true.
	Idle bool `json:"idle"`
}

type _CreateInstancesInNetworkPayload CreateInstancesInNetworkPayload

// NewCreateInstancesInNetworkPayload instantiates a new CreateInstancesInNetworkPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInstancesInNetworkPayload(regionId string, idle bool) *CreateInstancesInNetworkPayload {
	this := CreateInstancesInNetworkPayload{}
	this.RegionId = regionId
	this.Idle = idle
	return &this
}

// NewCreateInstancesInNetworkPayloadWithDefaults instantiates a new CreateInstancesInNetworkPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInstancesInNetworkPayloadWithDefaults() *CreateInstancesInNetworkPayload {
	this := CreateInstancesInNetworkPayload{}
	var idle bool = true
	this.Idle = idle
	return &this
}

// GetRegionId returns the RegionId field value
func (o *CreateInstancesInNetworkPayload) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *CreateInstancesInNetworkPayload) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *CreateInstancesInNetworkPayload) SetRegionId(v string) {
	o.RegionId = v
}

// GetIdle returns the Idle field value
func (o *CreateInstancesInNetworkPayload) GetIdle() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Idle
}

// GetIdleOk returns a tuple with the Idle field value
// and a boolean to check if the value has been set.
func (o *CreateInstancesInNetworkPayload) GetIdleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Idle, true
}

// SetIdle sets field value
func (o *CreateInstancesInNetworkPayload) SetIdle(v bool) {
	o.Idle = v
}

func (o CreateInstancesInNetworkPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateInstancesInNetworkPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionId"] = o.RegionId
	toSerialize["idle"] = o.Idle
	return toSerialize, nil
}

func (o *CreateInstancesInNetworkPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionId",
		"idle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateInstancesInNetworkPayload := _CreateInstancesInNetworkPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCreateInstancesInNetworkPayload)

	if err != nil {
		return err
	}

	*o = CreateInstancesInNetworkPayload(varCreateInstancesInNetworkPayload)

	return err
}

type NullableCreateInstancesInNetworkPayload struct {
	value *CreateInstancesInNetworkPayload
	isSet bool
}

func (v NullableCreateInstancesInNetworkPayload) Get() *CreateInstancesInNetworkPayload {
	return v.value
}

func (v *NullableCreateInstancesInNetworkPayload) Set(val *CreateInstancesInNetworkPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInstancesInNetworkPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInstancesInNetworkPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInstancesInNetworkPayload(val *CreateInstancesInNetworkPayload) *NullableCreateInstancesInNetworkPayload {
	return &NullableCreateInstancesInNetworkPayload{value: val, isSet: true}
}

func (v NullableCreateInstancesInNetworkPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInstancesInNetworkPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


