/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the IPSecAdvancedSettingsUpdateV23 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecAdvancedSettingsUpdateV23{}

// IPSecAdvancedSettingsUpdateV23 struct for IPSecAdvancedSettingsUpdateV23
type IPSecAdvancedSettingsUpdateV23 struct {
	KeyExchange *string `json:"keyExchange,omitempty"`
	IkeLifeTime *string `json:"ikeLifeTime,omitempty" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime *string `json:"lifetime,omitempty" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay *string `json:"dpdDelay,omitempty" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout *string `json:"dpdTimeout,omitempty" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 *IPSecPhaseConfigV23 `json:"phase1,omitempty"`
	Phase2 *IPSecPhaseConfigV23 `json:"phase2,omitempty"`
}

// NewIPSecAdvancedSettingsUpdateV23 instantiates a new IPSecAdvancedSettingsUpdateV23 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecAdvancedSettingsUpdateV23() *IPSecAdvancedSettingsUpdateV23 {
	this := IPSecAdvancedSettingsUpdateV23{}
	return &this
}

// NewIPSecAdvancedSettingsUpdateV23WithDefaults instantiates a new IPSecAdvancedSettingsUpdateV23 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecAdvancedSettingsUpdateV23WithDefaults() *IPSecAdvancedSettingsUpdateV23 {
	this := IPSecAdvancedSettingsUpdateV23{}
	return &this
}

// GetKeyExchange returns the KeyExchange field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetKeyExchange() string {
	if o == nil || IsNil(o.KeyExchange) {
		var ret string
		return ret
	}
	return *o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetKeyExchangeOk() (*string, bool) {
	if o == nil || IsNil(o.KeyExchange) {
		return nil, false
	}
	return o.KeyExchange, true
}

// HasKeyExchange returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasKeyExchange() bool {
	if o != nil && !IsNil(o.KeyExchange) {
		return true
	}

	return false
}

// SetKeyExchange gets a reference to the given string and assigns it to the KeyExchange field.
func (o *IPSecAdvancedSettingsUpdateV23) SetKeyExchange(v string) {
	o.KeyExchange = &v
}

// GetIkeLifeTime returns the IkeLifeTime field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetIkeLifeTime() string {
	if o == nil || IsNil(o.IkeLifeTime) {
		var ret string
		return ret
	}
	return *o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil || IsNil(o.IkeLifeTime) {
		return nil, false
	}
	return o.IkeLifeTime, true
}

// HasIkeLifeTime returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasIkeLifeTime() bool {
	if o != nil && !IsNil(o.IkeLifeTime) {
		return true
	}

	return false
}

// SetIkeLifeTime gets a reference to the given string and assigns it to the IkeLifeTime field.
func (o *IPSecAdvancedSettingsUpdateV23) SetIkeLifeTime(v string) {
	o.IkeLifeTime = &v
}

// GetLifetime returns the Lifetime field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetLifetime() string {
	if o == nil || IsNil(o.Lifetime) {
		var ret string
		return ret
	}
	return *o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.Lifetime) {
		return nil, false
	}
	return o.Lifetime, true
}

// HasLifetime returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasLifetime() bool {
	if o != nil && !IsNil(o.Lifetime) {
		return true
	}

	return false
}

// SetLifetime gets a reference to the given string and assigns it to the Lifetime field.
func (o *IPSecAdvancedSettingsUpdateV23) SetLifetime(v string) {
	o.Lifetime = &v
}

// GetDpdDelay returns the DpdDelay field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetDpdDelay() string {
	if o == nil || IsNil(o.DpdDelay) {
		var ret string
		return ret
	}
	return *o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetDpdDelayOk() (*string, bool) {
	if o == nil || IsNil(o.DpdDelay) {
		return nil, false
	}
	return o.DpdDelay, true
}

// HasDpdDelay returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasDpdDelay() bool {
	if o != nil && !IsNil(o.DpdDelay) {
		return true
	}

	return false
}

// SetDpdDelay gets a reference to the given string and assigns it to the DpdDelay field.
func (o *IPSecAdvancedSettingsUpdateV23) SetDpdDelay(v string) {
	o.DpdDelay = &v
}

// GetDpdTimeout returns the DpdTimeout field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetDpdTimeout() string {
	if o == nil || IsNil(o.DpdTimeout) {
		var ret string
		return ret
	}
	return *o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetDpdTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.DpdTimeout) {
		return nil, false
	}
	return o.DpdTimeout, true
}

// HasDpdTimeout returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasDpdTimeout() bool {
	if o != nil && !IsNil(o.DpdTimeout) {
		return true
	}

	return false
}

// SetDpdTimeout gets a reference to the given string and assigns it to the DpdTimeout field.
func (o *IPSecAdvancedSettingsUpdateV23) SetDpdTimeout(v string) {
	o.DpdTimeout = &v
}

// GetPhase1 returns the Phase1 field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetPhase1() IPSecPhaseConfigV23 {
	if o == nil || IsNil(o.Phase1) {
		var ret IPSecPhaseConfigV23
		return ret
	}
	return *o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetPhase1Ok() (*IPSecPhaseConfigV23, bool) {
	if o == nil || IsNil(o.Phase1) {
		return nil, false
	}
	return o.Phase1, true
}

// HasPhase1 returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasPhase1() bool {
	if o != nil && !IsNil(o.Phase1) {
		return true
	}

	return false
}

// SetPhase1 gets a reference to the given IPSecPhaseConfigV23 and assigns it to the Phase1 field.
func (o *IPSecAdvancedSettingsUpdateV23) SetPhase1(v IPSecPhaseConfigV23) {
	o.Phase1 = &v
}

// GetPhase2 returns the Phase2 field value if set, zero value otherwise.
func (o *IPSecAdvancedSettingsUpdateV23) GetPhase2() IPSecPhaseConfigV23 {
	if o == nil || IsNil(o.Phase2) {
		var ret IPSecPhaseConfigV23
		return ret
	}
	return *o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecAdvancedSettingsUpdateV23) GetPhase2Ok() (*IPSecPhaseConfigV23, bool) {
	if o == nil || IsNil(o.Phase2) {
		return nil, false
	}
	return o.Phase2, true
}

// HasPhase2 returns a boolean if a field has been set.
func (o *IPSecAdvancedSettingsUpdateV23) HasPhase2() bool {
	if o != nil && !IsNil(o.Phase2) {
		return true
	}

	return false
}

// SetPhase2 gets a reference to the given IPSecPhaseConfigV23 and assigns it to the Phase2 field.
func (o *IPSecAdvancedSettingsUpdateV23) SetPhase2(v IPSecPhaseConfigV23) {
	o.Phase2 = &v
}

func (o IPSecAdvancedSettingsUpdateV23) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecAdvancedSettingsUpdateV23) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyExchange) {
		toSerialize["keyExchange"] = o.KeyExchange
	}
	if !IsNil(o.IkeLifeTime) {
		toSerialize["ikeLifeTime"] = o.IkeLifeTime
	}
	if !IsNil(o.Lifetime) {
		toSerialize["lifetime"] = o.Lifetime
	}
	if !IsNil(o.DpdDelay) {
		toSerialize["dpdDelay"] = o.DpdDelay
	}
	if !IsNil(o.DpdTimeout) {
		toSerialize["dpdTimeout"] = o.DpdTimeout
	}
	if !IsNil(o.Phase1) {
		toSerialize["phase1"] = o.Phase1
	}
	if !IsNil(o.Phase2) {
		toSerialize["phase2"] = o.Phase2
	}
	return toSerialize, nil
}

type NullableIPSecAdvancedSettingsUpdateV23 struct {
	value *IPSecAdvancedSettingsUpdateV23
	isSet bool
}

func (v NullableIPSecAdvancedSettingsUpdateV23) Get() *IPSecAdvancedSettingsUpdateV23 {
	return v.value
}

func (v *NullableIPSecAdvancedSettingsUpdateV23) Set(val *IPSecAdvancedSettingsUpdateV23) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecAdvancedSettingsUpdateV23) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecAdvancedSettingsUpdateV23) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecAdvancedSettingsUpdateV23(val *IPSecAdvancedSettingsUpdateV23) *NullableIPSecAdvancedSettingsUpdateV23 {
	return &NullableIPSecAdvancedSettingsUpdateV23{value: val, isSet: true}
}

func (v NullableIPSecAdvancedSettingsUpdateV23) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecAdvancedSettingsUpdateV23) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


