/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StandardHealthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardHealthResponse{}

// StandardHealthResponse struct for StandardHealthResponse
type StandardHealthResponse struct {
	// List of health checks for standard networks (includes gateways and tunnels)
	Data []StandardHealthCheck `json:"data"`
}

type _StandardHealthResponse StandardHealthResponse

// NewStandardHealthResponse instantiates a new StandardHealthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardHealthResponse(data []StandardHealthCheck) *StandardHealthResponse {
	this := StandardHealthResponse{}
	this.Data = data
	return &this
}

// NewStandardHealthResponseWithDefaults instantiates a new StandardHealthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardHealthResponseWithDefaults() *StandardHealthResponse {
	this := StandardHealthResponse{}
	return &this
}

// GetData returns the Data field value
func (o *StandardHealthResponse) GetData() []StandardHealthCheck {
	if o == nil {
		var ret []StandardHealthCheck
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *StandardHealthResponse) GetDataOk() ([]StandardHealthCheck, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *StandardHealthResponse) SetData(v []StandardHealthCheck) {
	o.Data = v
}

func (o StandardHealthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardHealthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *StandardHealthResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardHealthResponse := _StandardHealthResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStandardHealthResponse)

	if err != nil {
		return err
	}

	*o = StandardHealthResponse(varStandardHealthResponse)

	return err
}

type NullableStandardHealthResponse struct {
	value *StandardHealthResponse
	isSet bool
}

func (v NullableStandardHealthResponse) Get() *StandardHealthResponse {
	return v.value
}

func (v *NullableStandardHealthResponse) Set(val *StandardHealthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardHealthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardHealthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardHealthResponse(val *StandardHealthResponse) *NullableStandardHealthResponse {
	return &NullableStandardHealthResponse{value: val, isSet: true}
}

func (v NullableStandardHealthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardHealthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


