/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IPSecSharedSettingsCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecSharedSettingsCreate{}

// IPSecSharedSettingsCreate struct for IPSecSharedSettingsCreate
type IPSecSharedSettingsCreate struct {
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidth *int32 `json:"peakBandwidth,omitempty"`
	P81ASN RemoteASN `json:"p81ASN"`
	Features *IPSecSharedSettingsFeatures `json:"features,omitempty"`
}

type _IPSecSharedSettingsCreate IPSecSharedSettingsCreate

// NewIPSecSharedSettingsCreate instantiates a new IPSecSharedSettingsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecSharedSettingsCreate(p81GatewaySubnets []string, remoteGatewaySubnets []string, p81ASN RemoteASN) *IPSecSharedSettingsCreate {
	this := IPSecSharedSettingsCreate{}
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	this.P81ASN = p81ASN
	return &this
}

// NewIPSecSharedSettingsCreateWithDefaults instantiates a new IPSecSharedSettingsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecSharedSettingsCreateWithDefaults() *IPSecSharedSettingsCreate {
	this := IPSecSharedSettingsCreate{}
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	return &this
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *IPSecSharedSettingsCreate) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsCreate) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *IPSecSharedSettingsCreate) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *IPSecSharedSettingsCreate) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsCreate) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *IPSecSharedSettingsCreate) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetPeakBandwidth returns the PeakBandwidth field value if set, zero value otherwise.
func (o *IPSecSharedSettingsCreate) GetPeakBandwidth() int32 {
	if o == nil || IsNil(o.PeakBandwidth) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidth
}

// GetPeakBandwidthOk returns a tuple with the PeakBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsCreate) GetPeakBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidth) {
		return nil, false
	}
	return o.PeakBandwidth, true
}

// HasPeakBandwidth returns a boolean if a field has been set.
func (o *IPSecSharedSettingsCreate) HasPeakBandwidth() bool {
	if o != nil && !IsNil(o.PeakBandwidth) {
		return true
	}

	return false
}

// SetPeakBandwidth gets a reference to the given int32 and assigns it to the PeakBandwidth field.
func (o *IPSecSharedSettingsCreate) SetPeakBandwidth(v int32) {
	o.PeakBandwidth = &v
}

// GetP81ASN returns the P81ASN field value
func (o *IPSecSharedSettingsCreate) GetP81ASN() RemoteASN {
	if o == nil {
		var ret RemoteASN
		return ret
	}

	return o.P81ASN
}

// GetP81ASNOk returns a tuple with the P81ASN field value
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsCreate) GetP81ASNOk() (*RemoteASN, bool) {
	if o == nil {
		return nil, false
	}
	return &o.P81ASN, true
}

// SetP81ASN sets field value
func (o *IPSecSharedSettingsCreate) SetP81ASN(v RemoteASN) {
	o.P81ASN = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *IPSecSharedSettingsCreate) GetFeatures() IPSecSharedSettingsFeatures {
	if o == nil || IsNil(o.Features) {
		var ret IPSecSharedSettingsFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IPSecSharedSettingsCreate) GetFeaturesOk() (*IPSecSharedSettingsFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *IPSecSharedSettingsCreate) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given IPSecSharedSettingsFeatures and assigns it to the Features field.
func (o *IPSecSharedSettingsCreate) SetFeatures(v IPSecSharedSettingsFeatures) {
	o.Features = &v
}

func (o IPSecSharedSettingsCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecSharedSettingsCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	if !IsNil(o.PeakBandwidth) {
		toSerialize["peakBandwidth"] = o.PeakBandwidth
	}
	toSerialize["p81ASN"] = o.P81ASN
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	return toSerialize, nil
}

func (o *IPSecSharedSettingsCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"p81ASN",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecSharedSettingsCreate := _IPSecSharedSettingsCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varIPSecSharedSettingsCreate)

	if err != nil {
		return err
	}

	*o = IPSecSharedSettingsCreate(varIPSecSharedSettingsCreate)

	return err
}

type NullableIPSecSharedSettingsCreate struct {
	value *IPSecSharedSettingsCreate
	isSet bool
}

func (v NullableIPSecSharedSettingsCreate) Get() *IPSecSharedSettingsCreate {
	return v.value
}

func (v *NullableIPSecSharedSettingsCreate) Set(val *IPSecSharedSettingsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecSharedSettingsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecSharedSettingsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecSharedSettingsCreate(val *IPSecSharedSettingsCreate) *NullableIPSecSharedSettingsCreate {
	return &NullableIPSecSharedSettingsCreate{value: val, isSet: true}
}

func (v NullableIPSecSharedSettingsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecSharedSettingsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


