/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type HaTunnelId struct {
	// Id of hatunnel.
	Id string `json:"id"`
	// tunnels in the hatunnel.
	Tunnels []string `json:"tunnels"`
	// hatunnel createdAt.
	CreatedAt []string `json:"createdAt"`
	// hatunnel updatedAt.
	UpdatedAt []string `json:"updatedAt"`
}
