/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DynamicTunnelCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicTunnelCreate{}

// DynamicTunnelCreate struct for DynamicTunnelCreate
type DynamicTunnelCreate struct {
	// Name of the tunnel
	TunnelName string `json:"tunnelName"`
	// Optional description for the tunnel
	Description *string `json:"description,omitempty"`
	// List of tunnels
	Tunnels []DynamicTunnelDetails `json:"tunnels"`
	SharedSettings EnhancedIPSecSharedSettingsCreate `json:"sharedSettings"`
	AdvancedSettings IPSecAdvancedSettingsV23 `json:"advancedSettings"`
}

type _DynamicTunnelCreate DynamicTunnelCreate

// NewDynamicTunnelCreate instantiates a new DynamicTunnelCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicTunnelCreate(tunnelName string, tunnels []DynamicTunnelDetails, sharedSettings EnhancedIPSecSharedSettingsCreate, advancedSettings IPSecAdvancedSettingsV23) *DynamicTunnelCreate {
	this := DynamicTunnelCreate{}
	this.TunnelName = tunnelName
	this.Tunnels = tunnels
	this.SharedSettings = sharedSettings
	this.AdvancedSettings = advancedSettings
	return &this
}

// NewDynamicTunnelCreateWithDefaults instantiates a new DynamicTunnelCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicTunnelCreateWithDefaults() *DynamicTunnelCreate {
	this := DynamicTunnelCreate{}
	return &this
}

// GetTunnelName returns the TunnelName field value
func (o *DynamicTunnelCreate) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelCreate) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *DynamicTunnelCreate) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *DynamicTunnelCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicTunnelCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *DynamicTunnelCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *DynamicTunnelCreate) SetDescription(v string) {
	o.Description = &v
}

// GetTunnels returns the Tunnels field value
func (o *DynamicTunnelCreate) GetTunnels() []DynamicTunnelDetails {
	if o == nil {
		var ret []DynamicTunnelDetails
		return ret
	}

	return o.Tunnels
}

// GetTunnelsOk returns a tuple with the Tunnels field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelCreate) GetTunnelsOk() ([]DynamicTunnelDetails, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tunnels, true
}

// SetTunnels sets field value
func (o *DynamicTunnelCreate) SetTunnels(v []DynamicTunnelDetails) {
	o.Tunnels = v
}

// GetSharedSettings returns the SharedSettings field value
func (o *DynamicTunnelCreate) GetSharedSettings() EnhancedIPSecSharedSettingsCreate {
	if o == nil {
		var ret EnhancedIPSecSharedSettingsCreate
		return ret
	}

	return o.SharedSettings
}

// GetSharedSettingsOk returns a tuple with the SharedSettings field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelCreate) GetSharedSettingsOk() (*EnhancedIPSecSharedSettingsCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SharedSettings, true
}

// SetSharedSettings sets field value
func (o *DynamicTunnelCreate) SetSharedSettings(v EnhancedIPSecSharedSettingsCreate) {
	o.SharedSettings = v
}

// GetAdvancedSettings returns the AdvancedSettings field value
func (o *DynamicTunnelCreate) GetAdvancedSettings() IPSecAdvancedSettingsV23 {
	if o == nil {
		var ret IPSecAdvancedSettingsV23
		return ret
	}

	return o.AdvancedSettings
}

// GetAdvancedSettingsOk returns a tuple with the AdvancedSettings field value
// and a boolean to check if the value has been set.
func (o *DynamicTunnelCreate) GetAdvancedSettingsOk() (*IPSecAdvancedSettingsV23, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdvancedSettings, true
}

// SetAdvancedSettings sets field value
func (o *DynamicTunnelCreate) SetAdvancedSettings(v IPSecAdvancedSettingsV23) {
	o.AdvancedSettings = v
}

func (o DynamicTunnelCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicTunnelCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tunnelName"] = o.TunnelName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["tunnels"] = o.Tunnels
	toSerialize["sharedSettings"] = o.SharedSettings
	toSerialize["advancedSettings"] = o.AdvancedSettings
	return toSerialize, nil
}

func (o *DynamicTunnelCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tunnelName",
		"tunnels",
		"sharedSettings",
		"advancedSettings",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDynamicTunnelCreate := _DynamicTunnelCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDynamicTunnelCreate)

	if err != nil {
		return err
	}

	*o = DynamicTunnelCreate(varDynamicTunnelCreate)

	return err
}

type NullableDynamicTunnelCreate struct {
	value *DynamicTunnelCreate
	isSet bool
}

func (v NullableDynamicTunnelCreate) Get() *DynamicTunnelCreate {
	return v.value
}

func (v *NullableDynamicTunnelCreate) Set(val *DynamicTunnelCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicTunnelCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicTunnelCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicTunnelCreate(val *DynamicTunnelCreate) *NullableDynamicTunnelCreate {
	return &NullableDynamicTunnelCreate{value: val, isSet: true}
}

func (v NullableDynamicTunnelCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicTunnelCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


