/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedRegionAttributesRunningMode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedRegionAttributesRunningMode{}

// EnhancedRegionAttributesRunningMode struct for EnhancedRegionAttributesRunningMode
type EnhancedRegionAttributesRunningMode struct {
	// Indicates if the region is currently active or disabled
	Idle bool `json:"idle"`
}

type _EnhancedRegionAttributesRunningMode EnhancedRegionAttributesRunningMode

// NewEnhancedRegionAttributesRunningMode instantiates a new EnhancedRegionAttributesRunningMode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedRegionAttributesRunningMode(idle bool) *EnhancedRegionAttributesRunningMode {
	this := EnhancedRegionAttributesRunningMode{}
	this.Idle = idle
	return &this
}

// NewEnhancedRegionAttributesRunningModeWithDefaults instantiates a new EnhancedRegionAttributesRunningMode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedRegionAttributesRunningModeWithDefaults() *EnhancedRegionAttributesRunningMode {
	this := EnhancedRegionAttributesRunningMode{}
	return &this
}

// GetIdle returns the Idle field value
func (o *EnhancedRegionAttributesRunningMode) GetIdle() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Idle
}

// GetIdleOk returns a tuple with the Idle field value
// and a boolean to check if the value has been set.
func (o *EnhancedRegionAttributesRunningMode) GetIdleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Idle, true
}

// SetIdle sets field value
func (o *EnhancedRegionAttributesRunningMode) SetIdle(v bool) {
	o.Idle = v
}

func (o EnhancedRegionAttributesRunningMode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedRegionAttributesRunningMode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["idle"] = o.Idle
	return toSerialize, nil
}

func (o *EnhancedRegionAttributesRunningMode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"idle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedRegionAttributesRunningMode := _EnhancedRegionAttributesRunningMode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEnhancedRegionAttributesRunningMode)

	if err != nil {
		return err
	}

	*o = EnhancedRegionAttributesRunningMode(varEnhancedRegionAttributesRunningMode)

	return err
}

type NullableEnhancedRegionAttributesRunningMode struct {
	value *EnhancedRegionAttributesRunningMode
	isSet bool
}

func (v NullableEnhancedRegionAttributesRunningMode) Get() *EnhancedRegionAttributesRunningMode {
	return v.value
}

func (v *NullableEnhancedRegionAttributesRunningMode) Set(val *EnhancedRegionAttributesRunningMode) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedRegionAttributesRunningMode) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedRegionAttributesRunningMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedRegionAttributesRunningMode(val *EnhancedRegionAttributesRunningMode) *NullableEnhancedRegionAttributesRunningMode {
	return &NullableEnhancedRegionAttributesRunningMode{value: val, isSet: true}
}

func (v NullableEnhancedRegionAttributesRunningMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedRegionAttributesRunningMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


