/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedHealthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedHealthResponse{}

// EnhancedHealthResponse struct for EnhancedHealthResponse
type EnhancedHealthResponse struct {
	// List of health checks for enhanced networks (tunnels only)
	Data []EnhancedHealthCheck `json:"data"`
}

type _EnhancedHealthResponse EnhancedHealthResponse

// NewEnhancedHealthResponse instantiates a new EnhancedHealthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedHealthResponse(data []EnhancedHealthCheck) *EnhancedHealthResponse {
	this := EnhancedHealthResponse{}
	this.Data = data
	return &this
}

// NewEnhancedHealthResponseWithDefaults instantiates a new EnhancedHealthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedHealthResponseWithDefaults() *EnhancedHealthResponse {
	this := EnhancedHealthResponse{}
	return &this
}

// GetData returns the Data field value
func (o *EnhancedHealthResponse) GetData() []EnhancedHealthCheck {
	if o == nil {
		var ret []EnhancedHealthCheck
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EnhancedHealthResponse) GetDataOk() ([]EnhancedHealthCheck, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *EnhancedHealthResponse) SetData(v []EnhancedHealthCheck) {
	o.Data = v
}

func (o EnhancedHealthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedHealthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *EnhancedHealthResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedHealthResponse := _EnhancedHealthResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnhancedHealthResponse)

	if err != nil {
		return err
	}

	*o = EnhancedHealthResponse(varEnhancedHealthResponse)

	return err
}

type NullableEnhancedHealthResponse struct {
	value *EnhancedHealthResponse
	isSet bool
}

func (v NullableEnhancedHealthResponse) Get() *EnhancedHealthResponse {
	return v.value
}

func (v *NullableEnhancedHealthResponse) Set(val *EnhancedHealthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedHealthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedHealthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedHealthResponse(val *EnhancedHealthResponse) *NullableEnhancedHealthResponse {
	return &NullableEnhancedHealthResponse{value: val, isSet: true}
}

func (v NullableEnhancedHealthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedHealthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


