/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VncApplication type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VncApplication{}

// VncApplication struct for VncApplication
type VncApplication struct {
	// Unique application ID
	Id string `json:"id"`
	// Application name
	Name string `json:"name"`
	// Application type
	Type string `json:"type"`
	// Application enabling status
	Enabled *bool `json:"enabled,omitempty"`
	Policy *CommonApplicationPolicy `json:"policy,omitempty"`
	// Application create date
	CreatedAt *string `json:"createdAt,omitempty"`
	Network BasicApplicationAllOfNetwork `json:"network"`
	Icon *BasicApplicationAllOfIcon `json:"icon,omitempty"`
	// List of IDs of assigned users
	Users []BasicApplicationAllOfUsers `json:"users,omitempty"`
	// List of IDs of assigned groups
	Groups []BasicApplicationAllOfGroups `json:"groups,omitempty"`
	Auth ApplicationAuth `json:"auth"`
	Alias ApplicationAlias `json:"alias"`
	// Determines if the application icon is displayed during user login
	DisplayIconAtLogin bool `json:"displayIconAtLogin"`
	// Fully qualified domain name (FQDN) associated with the application
	Fqdn string `json:"fqdn"`
	Host ApplicationHost `json:"host"`
	Port ApplicationPort `json:"port"`
	// Application update date
	UpdatedAt *string `json:"updatedAt,omitempty"`
	Attributes *VncAttributes `json:"attributes,omitempty"`
}

type _VncApplication VncApplication

// NewVncApplication instantiates a new VncApplication object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVncApplication(id string, name string, type_ string, network BasicApplicationAllOfNetwork, auth ApplicationAuth, alias ApplicationAlias, displayIconAtLogin bool, fqdn string, host ApplicationHost, port ApplicationPort) *VncApplication {
	this := VncApplication{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Network = network
	this.Auth = auth
	this.Alias = alias
	this.DisplayIconAtLogin = displayIconAtLogin
	this.Fqdn = fqdn
	this.Host = host
	this.Port = port
	return &this
}

// NewVncApplicationWithDefaults instantiates a new VncApplication object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVncApplicationWithDefaults() *VncApplication {
	this := VncApplication{}
	return &this
}

// GetId returns the Id field value
func (o *VncApplication) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VncApplication) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *VncApplication) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VncApplication) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *VncApplication) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VncApplication) SetType(v string) {
	o.Type = v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *VncApplication) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *VncApplication) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *VncApplication) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *VncApplication) GetPolicy() CommonApplicationPolicy {
	if o == nil || IsNil(o.Policy) {
		var ret CommonApplicationPolicy
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetPolicyOk() (*CommonApplicationPolicy, bool) {
	if o == nil || IsNil(o.Policy) {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *VncApplication) HasPolicy() bool {
	if o != nil && !IsNil(o.Policy) {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given CommonApplicationPolicy and assigns it to the Policy field.
func (o *VncApplication) SetPolicy(v CommonApplicationPolicy) {
	o.Policy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *VncApplication) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *VncApplication) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *VncApplication) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetNetwork returns the Network field value
func (o *VncApplication) GetNetwork() BasicApplicationAllOfNetwork {
	if o == nil {
		var ret BasicApplicationAllOfNetwork
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetNetworkOk() (*BasicApplicationAllOfNetwork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *VncApplication) SetNetwork(v BasicApplicationAllOfNetwork) {
	o.Network = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *VncApplication) GetIcon() BasicApplicationAllOfIcon {
	if o == nil || IsNil(o.Icon) {
		var ret BasicApplicationAllOfIcon
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetIconOk() (*BasicApplicationAllOfIcon, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *VncApplication) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given BasicApplicationAllOfIcon and assigns it to the Icon field.
func (o *VncApplication) SetIcon(v BasicApplicationAllOfIcon) {
	o.Icon = &v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *VncApplication) GetUsers() []BasicApplicationAllOfUsers {
	if o == nil || IsNil(o.Users) {
		var ret []BasicApplicationAllOfUsers
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetUsersOk() ([]BasicApplicationAllOfUsers, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *VncApplication) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []BasicApplicationAllOfUsers and assigns it to the Users field.
func (o *VncApplication) SetUsers(v []BasicApplicationAllOfUsers) {
	o.Users = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *VncApplication) GetGroups() []BasicApplicationAllOfGroups {
	if o == nil || IsNil(o.Groups) {
		var ret []BasicApplicationAllOfGroups
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetGroupsOk() ([]BasicApplicationAllOfGroups, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *VncApplication) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []BasicApplicationAllOfGroups and assigns it to the Groups field.
func (o *VncApplication) SetGroups(v []BasicApplicationAllOfGroups) {
	o.Groups = v
}

// GetAuth returns the Auth field value
func (o *VncApplication) GetAuth() ApplicationAuth {
	if o == nil {
		var ret ApplicationAuth
		return ret
	}

	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetAuthOk() (*ApplicationAuth, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auth, true
}

// SetAuth sets field value
func (o *VncApplication) SetAuth(v ApplicationAuth) {
	o.Auth = v
}

// GetAlias returns the Alias field value
func (o *VncApplication) GetAlias() ApplicationAlias {
	if o == nil {
		var ret ApplicationAlias
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetAliasOk() (*ApplicationAlias, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *VncApplication) SetAlias(v ApplicationAlias) {
	o.Alias = v
}

// GetDisplayIconAtLogin returns the DisplayIconAtLogin field value
func (o *VncApplication) GetDisplayIconAtLogin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DisplayIconAtLogin
}

// GetDisplayIconAtLoginOk returns a tuple with the DisplayIconAtLogin field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetDisplayIconAtLoginOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayIconAtLogin, true
}

// SetDisplayIconAtLogin sets field value
func (o *VncApplication) SetDisplayIconAtLogin(v bool) {
	o.DisplayIconAtLogin = v
}

// GetFqdn returns the Fqdn field value
func (o *VncApplication) GetFqdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fqdn
}

// GetFqdnOk returns a tuple with the Fqdn field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetFqdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fqdn, true
}

// SetFqdn sets field value
func (o *VncApplication) SetFqdn(v string) {
	o.Fqdn = v
}

// GetHost returns the Host field value
func (o *VncApplication) GetHost() ApplicationHost {
	if o == nil {
		var ret ApplicationHost
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetHostOk() (*ApplicationHost, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *VncApplication) SetHost(v ApplicationHost) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *VncApplication) GetPort() ApplicationPort {
	if o == nil {
		var ret ApplicationPort
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *VncApplication) GetPortOk() (*ApplicationPort, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *VncApplication) SetPort(v ApplicationPort) {
	o.Port = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *VncApplication) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *VncApplication) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *VncApplication) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *VncApplication) GetAttributes() VncAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret VncAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VncApplication) GetAttributesOk() (*VncAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *VncApplication) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given VncAttributes and assigns it to the Attributes field.
func (o *VncApplication) SetAttributes(v VncAttributes) {
	o.Attributes = &v
}

func (o VncApplication) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VncApplication) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Policy) {
		toSerialize["policy"] = o.Policy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	toSerialize["network"] = o.Network
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	toSerialize["auth"] = o.Auth
	toSerialize["alias"] = o.Alias
	toSerialize["displayIconAtLogin"] = o.DisplayIconAtLogin
	toSerialize["fqdn"] = o.Fqdn
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

func (o *VncApplication) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"network",
		"auth",
		"alias",
		"displayIconAtLogin",
		"fqdn",
		"host",
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVncApplication := _VncApplication{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVncApplication)

	if err != nil {
		return err
	}

	*o = VncApplication(varVncApplication)

	return err
}

type NullableVncApplication struct {
	value *VncApplication
	isSet bool
}

func (v NullableVncApplication) Get() *VncApplication {
	return v.value
}

func (v *NullableVncApplication) Set(val *VncApplication) {
	v.value = val
	v.isSet = true
}

func (v NullableVncApplication) IsSet() bool {
	return v.isSet
}

func (v *NullableVncApplication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVncApplication(val *VncApplication) *NullableVncApplication {
	return &NullableVncApplication{value: val, isSet: true}
}

func (v NullableVncApplication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVncApplication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


