/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FirewallPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FirewallPolicy{}

// FirewallPolicy struct for FirewallPolicy
type FirewallPolicy struct {
	// whether the policy is enabled.
	Enabled bool `json:"enabled"`
	// whether the policy is accept or drop.
	Allowed bool `json:"allowed"`
	// network policy id
	Id string `json:"id" validate:"regexp=^[a-zA-Z0-9]+$"`
	// an array of policy rules.
	PolicyRules []FirewallPolicyRule `json:"policyRules"`
	// whether the policy is traced.
	Trace *bool `json:"trace,omitempty"`
}

type _FirewallPolicy FirewallPolicy

// NewFirewallPolicy instantiates a new FirewallPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFirewallPolicy(enabled bool, allowed bool, id string, policyRules []FirewallPolicyRule) *FirewallPolicy {
	this := FirewallPolicy{}
	this.Enabled = enabled
	this.Allowed = allowed
	this.Id = id
	this.PolicyRules = policyRules
	return &this
}

// NewFirewallPolicyWithDefaults instantiates a new FirewallPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFirewallPolicyWithDefaults() *FirewallPolicy {
	this := FirewallPolicy{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *FirewallPolicy) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *FirewallPolicy) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *FirewallPolicy) SetEnabled(v bool) {
	o.Enabled = v
}

// GetAllowed returns the Allowed field value
func (o *FirewallPolicy) GetAllowed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Allowed
}

// GetAllowedOk returns a tuple with the Allowed field value
// and a boolean to check if the value has been set.
func (o *FirewallPolicy) GetAllowedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Allowed, true
}

// SetAllowed sets field value
func (o *FirewallPolicy) SetAllowed(v bool) {
	o.Allowed = v
}

// GetId returns the Id field value
func (o *FirewallPolicy) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FirewallPolicy) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FirewallPolicy) SetId(v string) {
	o.Id = v
}

// GetPolicyRules returns the PolicyRules field value
func (o *FirewallPolicy) GetPolicyRules() []FirewallPolicyRule {
	if o == nil {
		var ret []FirewallPolicyRule
		return ret
	}

	return o.PolicyRules
}

// GetPolicyRulesOk returns a tuple with the PolicyRules field value
// and a boolean to check if the value has been set.
func (o *FirewallPolicy) GetPolicyRulesOk() ([]FirewallPolicyRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyRules, true
}

// SetPolicyRules sets field value
func (o *FirewallPolicy) SetPolicyRules(v []FirewallPolicyRule) {
	o.PolicyRules = v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *FirewallPolicy) GetTrace() bool {
	if o == nil || IsNil(o.Trace) {
		var ret bool
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FirewallPolicy) GetTraceOk() (*bool, bool) {
	if o == nil || IsNil(o.Trace) {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *FirewallPolicy) HasTrace() bool {
	if o != nil && !IsNil(o.Trace) {
		return true
	}

	return false
}

// SetTrace gets a reference to the given bool and assigns it to the Trace field.
func (o *FirewallPolicy) SetTrace(v bool) {
	o.Trace = &v
}

func (o FirewallPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FirewallPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["allowed"] = o.Allowed
	toSerialize["id"] = o.Id
	toSerialize["policyRules"] = o.PolicyRules
	if !IsNil(o.Trace) {
		toSerialize["trace"] = o.Trace
	}
	return toSerialize, nil
}

func (o *FirewallPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"allowed",
		"id",
		"policyRules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFirewallPolicy := _FirewallPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varFirewallPolicy)

	if err != nil {
		return err
	}

	*o = FirewallPolicy(varFirewallPolicy)

	return err
}

type NullableFirewallPolicy struct {
	value *FirewallPolicy
	isSet bool
}

func (v NullableFirewallPolicy) Get() *FirewallPolicy {
	return v.value
}

func (v *NullableFirewallPolicy) Set(val *FirewallPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableFirewallPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableFirewallPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirewallPolicy(val *FirewallPolicy) *NullableFirewallPolicy {
	return &NullableFirewallPolicy{value: val, isSet: true}
}

func (v NullableFirewallPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirewallPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


