/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveRegionInstance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveRegionInstance{}

// RemoveRegionInstance struct for RemoveRegionInstance
type RemoveRegionInstance struct {
	// Region list.
	Regions []RemoveRegionPayload `json:"regions"`
}

type _RemoveRegionInstance RemoveRegionInstance

// NewRemoveRegionInstance instantiates a new RemoveRegionInstance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveRegionInstance(regions []RemoveRegionPayload) *RemoveRegionInstance {
	this := RemoveRegionInstance{}
	this.Regions = regions
	return &this
}

// NewRemoveRegionInstanceWithDefaults instantiates a new RemoveRegionInstance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveRegionInstanceWithDefaults() *RemoveRegionInstance {
	this := RemoveRegionInstance{}
	return &this
}

// GetRegions returns the Regions field value
func (o *RemoveRegionInstance) GetRegions() []RemoveRegionPayload {
	if o == nil {
		var ret []RemoveRegionPayload
		return ret
	}

	return o.Regions
}

// GetRegionsOk returns a tuple with the Regions field value
// and a boolean to check if the value has been set.
func (o *RemoveRegionInstance) GetRegionsOk() ([]RemoveRegionPayload, bool) {
	if o == nil {
		return nil, false
	}
	return o.Regions, true
}

// SetRegions sets field value
func (o *RemoveRegionInstance) SetRegions(v []RemoveRegionPayload) {
	o.Regions = v
}

func (o RemoveRegionInstance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveRegionInstance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regions"] = o.Regions
	return toSerialize, nil
}

func (o *RemoveRegionInstance) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveRegionInstance := _RemoveRegionInstance{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varRemoveRegionInstance)

	if err != nil {
		return err
	}

	*o = RemoveRegionInstance(varRemoveRegionInstance)

	return err
}

type NullableRemoveRegionInstance struct {
	value *RemoveRegionInstance
	isSet bool
}

func (v NullableRemoveRegionInstance) Get() *RemoveRegionInstance {
	return v.value
}

func (v *NullableRemoveRegionInstance) Set(val *RemoveRegionInstance) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveRegionInstance) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveRegionInstance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveRegionInstance(val *RemoveRegionInstance) *NullableRemoveRegionInstance {
	return &NullableRemoveRegionInstance{value: val, isSet: true}
}

func (v NullableRemoveRegionInstance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveRegionInstance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


