/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IPSecRedundantTunnelUpdatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IPSecRedundantTunnelUpdatePayload{}

// IPSecRedundantTunnelUpdatePayload struct for IPSecRedundantTunnelUpdatePayload
type IPSecRedundantTunnelUpdatePayload struct {
	Passphrase string `json:"passphrase" validate:"regexp=^[a-zA-Z1-9._][a-zA-Z0-9._]{7,63}$"`
	P81GWInternalIP string `json:"p81GWInternalIP"`
	RemoteGWInternalIP string `json:"remoteGWInternalIP"`
	RemotePublicIP string `json:"remotePublicIP"`
	RemoteASN RemoteASN `json:"remoteASN"`
	RemoteID RemoteID `json:"remoteID"`
	GatewayID string `json:"gatewayID"`
	TunnelId string `json:"tunnelId"`
}

type _IPSecRedundantTunnelUpdatePayload IPSecRedundantTunnelUpdatePayload

// NewIPSecRedundantTunnelUpdatePayload instantiates a new IPSecRedundantTunnelUpdatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIPSecRedundantTunnelUpdatePayload(passphrase string, p81GWInternalIP string, remoteGWInternalIP string, remotePublicIP string, remoteASN RemoteASN, remoteID RemoteID, gatewayID string, tunnelId string) *IPSecRedundantTunnelUpdatePayload {
	this := IPSecRedundantTunnelUpdatePayload{}
	this.Passphrase = passphrase
	this.P81GWInternalIP = p81GWInternalIP
	this.RemoteGWInternalIP = remoteGWInternalIP
	this.RemotePublicIP = remotePublicIP
	this.RemoteASN = remoteASN
	this.RemoteID = remoteID
	this.GatewayID = gatewayID
	this.TunnelId = tunnelId
	return &this
}

// NewIPSecRedundantTunnelUpdatePayloadWithDefaults instantiates a new IPSecRedundantTunnelUpdatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIPSecRedundantTunnelUpdatePayloadWithDefaults() *IPSecRedundantTunnelUpdatePayload {
	this := IPSecRedundantTunnelUpdatePayload{}
	return &this
}

// GetPassphrase returns the Passphrase field value
func (o *IPSecRedundantTunnelUpdatePayload) GetPassphrase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetPassphraseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passphrase, true
}

// SetPassphrase sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetPassphrase(v string) {
	o.Passphrase = v
}

// GetP81GWInternalIP returns the P81GWInternalIP field value
func (o *IPSecRedundantTunnelUpdatePayload) GetP81GWInternalIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.P81GWInternalIP
}

// GetP81GWInternalIPOk returns a tuple with the P81GWInternalIP field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetP81GWInternalIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.P81GWInternalIP, true
}

// SetP81GWInternalIP sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetP81GWInternalIP(v string) {
	o.P81GWInternalIP = v
}

// GetRemoteGWInternalIP returns the RemoteGWInternalIP field value
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteGWInternalIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemoteGWInternalIP
}

// GetRemoteGWInternalIPOk returns a tuple with the RemoteGWInternalIP field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteGWInternalIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteGWInternalIP, true
}

// SetRemoteGWInternalIP sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetRemoteGWInternalIP(v string) {
	o.RemoteGWInternalIP = v
}

// GetRemotePublicIP returns the RemotePublicIP field value
func (o *IPSecRedundantTunnelUpdatePayload) GetRemotePublicIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemotePublicIP
}

// GetRemotePublicIPOk returns a tuple with the RemotePublicIP field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetRemotePublicIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemotePublicIP, true
}

// SetRemotePublicIP sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetRemotePublicIP(v string) {
	o.RemotePublicIP = v
}

// GetRemoteASN returns the RemoteASN field value
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteASN() RemoteASN {
	if o == nil {
		var ret RemoteASN
		return ret
	}

	return o.RemoteASN
}

// GetRemoteASNOk returns a tuple with the RemoteASN field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteASNOk() (*RemoteASN, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteASN, true
}

// SetRemoteASN sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetRemoteASN(v RemoteASN) {
	o.RemoteASN = v
}

// GetRemoteID returns the RemoteID field value
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteID() RemoteID {
	if o == nil {
		var ret RemoteID
		return ret
	}

	return o.RemoteID
}

// GetRemoteIDOk returns a tuple with the RemoteID field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetRemoteIDOk() (*RemoteID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemoteID, true
}

// SetRemoteID sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetRemoteID(v RemoteID) {
	o.RemoteID = v
}

// GetGatewayID returns the GatewayID field value
func (o *IPSecRedundantTunnelUpdatePayload) GetGatewayID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayID
}

// GetGatewayIDOk returns a tuple with the GatewayID field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetGatewayIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayID, true
}

// SetGatewayID sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetGatewayID(v string) {
	o.GatewayID = v
}

// GetTunnelId returns the TunnelId field value
func (o *IPSecRedundantTunnelUpdatePayload) GetTunnelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelId
}

// GetTunnelIdOk returns a tuple with the TunnelId field value
// and a boolean to check if the value has been set.
func (o *IPSecRedundantTunnelUpdatePayload) GetTunnelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelId, true
}

// SetTunnelId sets field value
func (o *IPSecRedundantTunnelUpdatePayload) SetTunnelId(v string) {
	o.TunnelId = v
}

func (o IPSecRedundantTunnelUpdatePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IPSecRedundantTunnelUpdatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passphrase"] = o.Passphrase
	toSerialize["p81GWInternalIP"] = o.P81GWInternalIP
	toSerialize["remoteGWInternalIP"] = o.RemoteGWInternalIP
	toSerialize["remotePublicIP"] = o.RemotePublicIP
	toSerialize["remoteASN"] = o.RemoteASN
	toSerialize["remoteID"] = o.RemoteID
	toSerialize["gatewayID"] = o.GatewayID
	toSerialize["tunnelId"] = o.TunnelId
	return toSerialize, nil
}

func (o *IPSecRedundantTunnelUpdatePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passphrase",
		"p81GWInternalIP",
		"remoteGWInternalIP",
		"remotePublicIP",
		"remoteASN",
		"remoteID",
		"gatewayID",
		"tunnelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIPSecRedundantTunnelUpdatePayload := _IPSecRedundantTunnelUpdatePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIPSecRedundantTunnelUpdatePayload)

	if err != nil {
		return err
	}

	*o = IPSecRedundantTunnelUpdatePayload(varIPSecRedundantTunnelUpdatePayload)

	return err
}

type NullableIPSecRedundantTunnelUpdatePayload struct {
	value *IPSecRedundantTunnelUpdatePayload
	isSet bool
}

func (v NullableIPSecRedundantTunnelUpdatePayload) Get() *IPSecRedundantTunnelUpdatePayload {
	return v.value
}

func (v *NullableIPSecRedundantTunnelUpdatePayload) Set(val *IPSecRedundantTunnelUpdatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableIPSecRedundantTunnelUpdatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableIPSecRedundantTunnelUpdatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIPSecRedundantTunnelUpdatePayload(val *IPSecRedundantTunnelUpdatePayload) *NullableIPSecRedundantTunnelUpdatePayload {
	return &NullableIPSecRedundantTunnelUpdatePayload{value: val, isSet: true}
}

func (v NullableIPSecRedundantTunnelUpdatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIPSecRedundantTunnelUpdatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


