/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the BasicApplicationAllOfGroups type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicApplicationAllOfGroups{}

// BasicApplicationAllOfGroups Application groups
type BasicApplicationAllOfGroups struct {
	// Unique Group ID
	Id *string `json:"id,omitempty"`
	// Group's name
	Name *string `json:"name,omitempty"`
}

// NewBasicApplicationAllOfGroups instantiates a new BasicApplicationAllOfGroups object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicApplicationAllOfGroups() *BasicApplicationAllOfGroups {
	this := BasicApplicationAllOfGroups{}
	return &this
}

// NewBasicApplicationAllOfGroupsWithDefaults instantiates a new BasicApplicationAllOfGroups object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicApplicationAllOfGroupsWithDefaults() *BasicApplicationAllOfGroups {
	this := BasicApplicationAllOfGroups{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BasicApplicationAllOfGroups) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfGroups) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BasicApplicationAllOfGroups) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BasicApplicationAllOfGroups) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BasicApplicationAllOfGroups) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasicApplicationAllOfGroups) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BasicApplicationAllOfGroups) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BasicApplicationAllOfGroups) SetName(v string) {
	o.Name = &v
}

func (o BasicApplicationAllOfGroups) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicApplicationAllOfGroups) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableBasicApplicationAllOfGroups struct {
	value *BasicApplicationAllOfGroups
	isSet bool
}

func (v NullableBasicApplicationAllOfGroups) Get() *BasicApplicationAllOfGroups {
	return v.value
}

func (v *NullableBasicApplicationAllOfGroups) Set(val *BasicApplicationAllOfGroups) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicApplicationAllOfGroups) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicApplicationAllOfGroups) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicApplicationAllOfGroups(val *BasicApplicationAllOfGroups) *NullableBasicApplicationAllOfGroups {
	return &NullableBasicApplicationAllOfGroups{value: val, isSet: true}
}

func (v NullableBasicApplicationAllOfGroups) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicApplicationAllOfGroups) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


