/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveRegionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveRegionDTO{}

// RemoveRegionDTO struct for RemoveRegionDTO
type RemoveRegionDTO struct {
	RegionId string `json:"regionId"`
}

type _RemoveRegionDTO RemoveRegionDTO

// NewRemoveRegionDTO instantiates a new RemoveRegionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveRegionDTO(regionId string) *RemoveRegionDTO {
	this := RemoveRegionDTO{}
	this.RegionId = regionId
	return &this
}

// NewRemoveRegionDTOWithDefaults instantiates a new RemoveRegionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveRegionDTOWithDefaults() *RemoveRegionDTO {
	this := RemoveRegionDTO{}
	return &this
}

// GetRegionId returns the RegionId field value
func (o *RemoveRegionDTO) GetRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionId
}

// GetRegionIdOk returns a tuple with the RegionId field value
// and a boolean to check if the value has been set.
func (o *RemoveRegionDTO) GetRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionId, true
}

// SetRegionId sets field value
func (o *RemoveRegionDTO) SetRegionId(v string) {
	o.RegionId = v
}

func (o RemoveRegionDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveRegionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionId"] = o.RegionId
	return toSerialize, nil
}

func (o *RemoveRegionDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveRegionDTO := _RemoveRegionDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveRegionDTO)

	if err != nil {
		return err
	}

	*o = RemoveRegionDTO(varRemoveRegionDTO)

	return err
}

type NullableRemoveRegionDTO struct {
	value *RemoveRegionDTO
	isSet bool
}

func (v NullableRemoveRegionDTO) Get() *RemoveRegionDTO {
	return v.value
}

func (v *NullableRemoveRegionDTO) Set(val *RemoveRegionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveRegionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveRegionDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveRegionDTO(val *RemoveRegionDTO) *NullableRemoveRegionDTO {
	return &NullableRemoveRegionDTO{value: val, isSet: true}
}

func (v NullableRemoveRegionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveRegionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


