/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateIPSecSinglePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIPSecSinglePayload{}

// CreateIPSecSinglePayload struct for CreateIPSecSinglePayload
type CreateIPSecSinglePayload struct {
	// Region ID
	RegionID string `json:"regionID"`
	// Gateway ID
	GatewayID string `json:"gatewayID"`
	// The name of the tunnel
	TunnelName string `json:"tunnelName" validate:"regexp=^[a-zA-Z0-9]*$"`
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidth *int32 `json:"peakBandwidth,omitempty"`
	P81ASN *RemoteASN `json:"p81ASN,omitempty"`
	Features *IPSecSharedSettingsFeatures `json:"features,omitempty"`
	KeyExchange string `json:"keyExchange"`
	IkeLifeTime string `json:"ikeLifeTime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime string `json:"lifetime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay string `json:"dpdDelay" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout string `json:"dpdTimeout" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 IPSecPhaseConfig `json:"phase1"`
	Phase2 IPSecPhaseConfig `json:"phase2"`
	Passphrase string `json:"passphrase" validate:"regexp=^[a-zA-Z1-9._][a-zA-Z0-9._]{7,63}$"`
	RemotePublicIP string `json:"remotePublicIP"`
	RemoteID *RemoteID `json:"remoteID,omitempty"`
}

type _CreateIPSecSinglePayload CreateIPSecSinglePayload

// NewCreateIPSecSinglePayload instantiates a new CreateIPSecSinglePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIPSecSinglePayload(regionID string, gatewayID string, tunnelName string, p81GatewaySubnets []string, remoteGatewaySubnets []string, keyExchange string, ikeLifeTime string, lifetime string, dpdDelay string, dpdTimeout string, phase1 IPSecPhaseConfig, phase2 IPSecPhaseConfig, passphrase string, remotePublicIP string) *CreateIPSecSinglePayload {
	this := CreateIPSecSinglePayload{}
	this.RegionID = regionID
	this.GatewayID = gatewayID
	this.TunnelName = tunnelName
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	this.KeyExchange = keyExchange
	this.IkeLifeTime = ikeLifeTime
	this.Lifetime = lifetime
	this.DpdDelay = dpdDelay
	this.DpdTimeout = dpdTimeout
	this.Phase1 = phase1
	this.Phase2 = phase2
	this.Passphrase = passphrase
	this.RemotePublicIP = remotePublicIP
	return &this
}

// NewCreateIPSecSinglePayloadWithDefaults instantiates a new CreateIPSecSinglePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIPSecSinglePayloadWithDefaults() *CreateIPSecSinglePayload {
	this := CreateIPSecSinglePayload{}
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	return &this
}

// GetRegionID returns the RegionID field value
func (o *CreateIPSecSinglePayload) GetRegionID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegionID
}

// GetRegionIDOk returns a tuple with the RegionID field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetRegionIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegionID, true
}

// SetRegionID sets field value
func (o *CreateIPSecSinglePayload) SetRegionID(v string) {
	o.RegionID = v
}

// GetGatewayID returns the GatewayID field value
func (o *CreateIPSecSinglePayload) GetGatewayID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GatewayID
}

// GetGatewayIDOk returns a tuple with the GatewayID field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetGatewayIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GatewayID, true
}

// SetGatewayID sets field value
func (o *CreateIPSecSinglePayload) SetGatewayID(v string) {
	o.GatewayID = v
}

// GetTunnelName returns the TunnelName field value
func (o *CreateIPSecSinglePayload) GetTunnelName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TunnelName
}

// GetTunnelNameOk returns a tuple with the TunnelName field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetTunnelNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TunnelName, true
}

// SetTunnelName sets field value
func (o *CreateIPSecSinglePayload) SetTunnelName(v string) {
	o.TunnelName = v
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *CreateIPSecSinglePayload) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *CreateIPSecSinglePayload) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *CreateIPSecSinglePayload) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *CreateIPSecSinglePayload) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetPeakBandwidth returns the PeakBandwidth field value if set, zero value otherwise.
func (o *CreateIPSecSinglePayload) GetPeakBandwidth() int32 {
	if o == nil || IsNil(o.PeakBandwidth) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidth
}

// GetPeakBandwidthOk returns a tuple with the PeakBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetPeakBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidth) {
		return nil, false
	}
	return o.PeakBandwidth, true
}

// HasPeakBandwidth returns a boolean if a field has been set.
func (o *CreateIPSecSinglePayload) HasPeakBandwidth() bool {
	if o != nil && !IsNil(o.PeakBandwidth) {
		return true
	}

	return false
}

// SetPeakBandwidth gets a reference to the given int32 and assigns it to the PeakBandwidth field.
func (o *CreateIPSecSinglePayload) SetPeakBandwidth(v int32) {
	o.PeakBandwidth = &v
}

// GetP81ASN returns the P81ASN field value if set, zero value otherwise.
func (o *CreateIPSecSinglePayload) GetP81ASN() RemoteASN {
	if o == nil || IsNil(o.P81ASN) {
		var ret RemoteASN
		return ret
	}
	return *o.P81ASN
}

// GetP81ASNOk returns a tuple with the P81ASN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetP81ASNOk() (*RemoteASN, bool) {
	if o == nil || IsNil(o.P81ASN) {
		return nil, false
	}
	return o.P81ASN, true
}

// HasP81ASN returns a boolean if a field has been set.
func (o *CreateIPSecSinglePayload) HasP81ASN() bool {
	if o != nil && !IsNil(o.P81ASN) {
		return true
	}

	return false
}

// SetP81ASN gets a reference to the given RemoteASN and assigns it to the P81ASN field.
func (o *CreateIPSecSinglePayload) SetP81ASN(v RemoteASN) {
	o.P81ASN = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *CreateIPSecSinglePayload) GetFeatures() IPSecSharedSettingsFeatures {
	if o == nil || IsNil(o.Features) {
		var ret IPSecSharedSettingsFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetFeaturesOk() (*IPSecSharedSettingsFeatures, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *CreateIPSecSinglePayload) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given IPSecSharedSettingsFeatures and assigns it to the Features field.
func (o *CreateIPSecSinglePayload) SetFeatures(v IPSecSharedSettingsFeatures) {
	o.Features = &v
}

// GetKeyExchange returns the KeyExchange field value
func (o *CreateIPSecSinglePayload) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *CreateIPSecSinglePayload) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetIkeLifeTime returns the IkeLifeTime field value
func (o *CreateIPSecSinglePayload) GetIkeLifeTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IkeLifeTime, true
}

// SetIkeLifeTime sets field value
func (o *CreateIPSecSinglePayload) SetIkeLifeTime(v string) {
	o.IkeLifeTime = v
}

// GetLifetime returns the Lifetime field value
func (o *CreateIPSecSinglePayload) GetLifetime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifetime, true
}

// SetLifetime sets field value
func (o *CreateIPSecSinglePayload) SetLifetime(v string) {
	o.Lifetime = v
}

// GetDpdDelay returns the DpdDelay field value
func (o *CreateIPSecSinglePayload) GetDpdDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetDpdDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdDelay, true
}

// SetDpdDelay sets field value
func (o *CreateIPSecSinglePayload) SetDpdDelay(v string) {
	o.DpdDelay = v
}

// GetDpdTimeout returns the DpdTimeout field value
func (o *CreateIPSecSinglePayload) GetDpdTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetDpdTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdTimeout, true
}

// SetDpdTimeout sets field value
func (o *CreateIPSecSinglePayload) SetDpdTimeout(v string) {
	o.DpdTimeout = v
}

// GetPhase1 returns the Phase1 field value
func (o *CreateIPSecSinglePayload) GetPhase1() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetPhase1Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase1, true
}

// SetPhase1 sets field value
func (o *CreateIPSecSinglePayload) SetPhase1(v IPSecPhaseConfig) {
	o.Phase1 = v
}

// GetPhase2 returns the Phase2 field value
func (o *CreateIPSecSinglePayload) GetPhase2() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetPhase2Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase2, true
}

// SetPhase2 sets field value
func (o *CreateIPSecSinglePayload) SetPhase2(v IPSecPhaseConfig) {
	o.Phase2 = v
}

// GetPassphrase returns the Passphrase field value
func (o *CreateIPSecSinglePayload) GetPassphrase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetPassphraseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passphrase, true
}

// SetPassphrase sets field value
func (o *CreateIPSecSinglePayload) SetPassphrase(v string) {
	o.Passphrase = v
}

// GetRemotePublicIP returns the RemotePublicIP field value
func (o *CreateIPSecSinglePayload) GetRemotePublicIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RemotePublicIP
}

// GetRemotePublicIPOk returns a tuple with the RemotePublicIP field value
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetRemotePublicIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RemotePublicIP, true
}

// SetRemotePublicIP sets field value
func (o *CreateIPSecSinglePayload) SetRemotePublicIP(v string) {
	o.RemotePublicIP = v
}

// GetRemoteID returns the RemoteID field value if set, zero value otherwise.
func (o *CreateIPSecSinglePayload) GetRemoteID() RemoteID {
	if o == nil || IsNil(o.RemoteID) {
		var ret RemoteID
		return ret
	}
	return *o.RemoteID
}

// GetRemoteIDOk returns a tuple with the RemoteID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIPSecSinglePayload) GetRemoteIDOk() (*RemoteID, bool) {
	if o == nil || IsNil(o.RemoteID) {
		return nil, false
	}
	return o.RemoteID, true
}

// HasRemoteID returns a boolean if a field has been set.
func (o *CreateIPSecSinglePayload) HasRemoteID() bool {
	if o != nil && !IsNil(o.RemoteID) {
		return true
	}

	return false
}

// SetRemoteID gets a reference to the given RemoteID and assigns it to the RemoteID field.
func (o *CreateIPSecSinglePayload) SetRemoteID(v RemoteID) {
	o.RemoteID = &v
}

func (o CreateIPSecSinglePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIPSecSinglePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["regionID"] = o.RegionID
	toSerialize["gatewayID"] = o.GatewayID
	toSerialize["tunnelName"] = o.TunnelName
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	if !IsNil(o.PeakBandwidth) {
		toSerialize["peakBandwidth"] = o.PeakBandwidth
	}
	if !IsNil(o.P81ASN) {
		toSerialize["p81ASN"] = o.P81ASN
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	toSerialize["keyExchange"] = o.KeyExchange
	toSerialize["ikeLifeTime"] = o.IkeLifeTime
	toSerialize["lifetime"] = o.Lifetime
	toSerialize["dpdDelay"] = o.DpdDelay
	toSerialize["dpdTimeout"] = o.DpdTimeout
	toSerialize["phase1"] = o.Phase1
	toSerialize["phase2"] = o.Phase2
	toSerialize["passphrase"] = o.Passphrase
	toSerialize["remotePublicIP"] = o.RemotePublicIP
	if !IsNil(o.RemoteID) {
		toSerialize["remoteID"] = o.RemoteID
	}
	return toSerialize, nil
}

func (o *CreateIPSecSinglePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"regionID",
		"gatewayID",
		"tunnelName",
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"keyExchange",
		"ikeLifeTime",
		"lifetime",
		"dpdDelay",
		"dpdTimeout",
		"phase1",
		"phase2",
		"passphrase",
		"remotePublicIP",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIPSecSinglePayload := _CreateIPSecSinglePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCreateIPSecSinglePayload)

	if err != nil {
		return err
	}

	*o = CreateIPSecSinglePayload(varCreateIPSecSinglePayload)

	return err
}

type NullableCreateIPSecSinglePayload struct {
	value *CreateIPSecSinglePayload
	isSet bool
}

func (v NullableCreateIPSecSinglePayload) Get() *CreateIPSecSinglePayload {
	return v.value
}

func (v *NullableCreateIPSecSinglePayload) Set(val *CreateIPSecSinglePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIPSecSinglePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIPSecSinglePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIPSecSinglePayload(val *CreateIPSecSinglePayload) *NullableCreateIPSecSinglePayload {
	return &NullableCreateIPSecSinglePayload{value: val, isSet: true}
}

func (v NullableCreateIPSecSinglePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIPSecSinglePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


