/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedRegionCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedRegionCreate{}

// EnhancedRegionCreate struct for EnhancedRegionCreate
type EnhancedRegionCreate struct {
	// Harmony SASE region ID, Take id from GET Harmony sases regions endpoint (/networks/enhanced/harmony-sase-regions).
	HarmonySaseRegionId string `json:"harmonySaseRegionId"`
	// Number of scale units for the region. Scale units determine the capacity and performance level of the enhanced region. Higher values provide greater throughput and connection capacity. 
	ScaleUnits *int32 `json:"scaleUnits,omitempty"`
	// Region is disabled for users if true
	Idle *bool `json:"idle,omitempty"`
}

type _EnhancedRegionCreate EnhancedRegionCreate

// NewEnhancedRegionCreate instantiates a new EnhancedRegionCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedRegionCreate(harmonySaseRegionId string) *EnhancedRegionCreate {
	this := EnhancedRegionCreate{}
	this.HarmonySaseRegionId = harmonySaseRegionId
	var scaleUnits int32 = 1
	this.ScaleUnits = &scaleUnits
	var idle bool = true
	this.Idle = &idle
	return &this
}

// NewEnhancedRegionCreateWithDefaults instantiates a new EnhancedRegionCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedRegionCreateWithDefaults() *EnhancedRegionCreate {
	this := EnhancedRegionCreate{}
	var scaleUnits int32 = 1
	this.ScaleUnits = &scaleUnits
	var idle bool = true
	this.Idle = &idle
	return &this
}

// GetHarmonySaseRegionId returns the HarmonySaseRegionId field value
func (o *EnhancedRegionCreate) GetHarmonySaseRegionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HarmonySaseRegionId
}

// GetHarmonySaseRegionIdOk returns a tuple with the HarmonySaseRegionId field value
// and a boolean to check if the value has been set.
func (o *EnhancedRegionCreate) GetHarmonySaseRegionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HarmonySaseRegionId, true
}

// SetHarmonySaseRegionId sets field value
func (o *EnhancedRegionCreate) SetHarmonySaseRegionId(v string) {
	o.HarmonySaseRegionId = v
}

// GetScaleUnits returns the ScaleUnits field value if set, zero value otherwise.
func (o *EnhancedRegionCreate) GetScaleUnits() int32 {
	if o == nil || IsNil(o.ScaleUnits) {
		var ret int32
		return ret
	}
	return *o.ScaleUnits
}

// GetScaleUnitsOk returns a tuple with the ScaleUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedRegionCreate) GetScaleUnitsOk() (*int32, bool) {
	if o == nil || IsNil(o.ScaleUnits) {
		return nil, false
	}
	return o.ScaleUnits, true
}

// HasScaleUnits returns a boolean if a field has been set.
func (o *EnhancedRegionCreate) HasScaleUnits() bool {
	if o != nil && !IsNil(o.ScaleUnits) {
		return true
	}

	return false
}

// SetScaleUnits gets a reference to the given int32 and assigns it to the ScaleUnits field.
func (o *EnhancedRegionCreate) SetScaleUnits(v int32) {
	o.ScaleUnits = &v
}

// GetIdle returns the Idle field value if set, zero value otherwise.
func (o *EnhancedRegionCreate) GetIdle() bool {
	if o == nil || IsNil(o.Idle) {
		var ret bool
		return ret
	}
	return *o.Idle
}

// GetIdleOk returns a tuple with the Idle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedRegionCreate) GetIdleOk() (*bool, bool) {
	if o == nil || IsNil(o.Idle) {
		return nil, false
	}
	return o.Idle, true
}

// HasIdle returns a boolean if a field has been set.
func (o *EnhancedRegionCreate) HasIdle() bool {
	if o != nil && !IsNil(o.Idle) {
		return true
	}

	return false
}

// SetIdle gets a reference to the given bool and assigns it to the Idle field.
func (o *EnhancedRegionCreate) SetIdle(v bool) {
	o.Idle = &v
}

func (o EnhancedRegionCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedRegionCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["harmonySaseRegionId"] = o.HarmonySaseRegionId
	if !IsNil(o.ScaleUnits) {
		toSerialize["scaleUnits"] = o.ScaleUnits
	}
	if !IsNil(o.Idle) {
		toSerialize["idle"] = o.Idle
	}
	return toSerialize, nil
}

func (o *EnhancedRegionCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"harmonySaseRegionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedRegionCreate := _EnhancedRegionCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varEnhancedRegionCreate)

	if err != nil {
		return err
	}

	*o = EnhancedRegionCreate(varEnhancedRegionCreate)

	return err
}

type NullableEnhancedRegionCreate struct {
	value *EnhancedRegionCreate
	isSet bool
}

func (v NullableEnhancedRegionCreate) Get() *EnhancedRegionCreate {
	return v.value
}

func (v *NullableEnhancedRegionCreate) Set(val *EnhancedRegionCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedRegionCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedRegionCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedRegionCreate(val *EnhancedRegionCreate) *NullableEnhancedRegionCreate {
	return &NullableEnhancedRegionCreate{value: val, isSet: true}
}

func (v NullableEnhancedRegionCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedRegionCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


