/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the NetworkTunnelIpsecRedundant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkTunnelIpsecRedundant{}

// NetworkTunnelIpsecRedundant struct for NetworkTunnelIpsecRedundant
type NetworkTunnelIpsecRedundant struct {
	// Unique ID.
	Id string `json:"id"`
	// ID of the network.
	Network string `json:"network"`
	// ID of the network region.
	Region string `json:"region"`
	// ID of the network instance.
	Instance string `json:"instance"`
	InterfaceName string `json:"interfaceName"`
	Type string `json:"type"`
	// Indicates if it's a redundant tunnel.
	IsHA bool `json:"isHA"`
	// ID of the tenant.
	TenantId string `json:"tenantId"`
	// The date when this record was created.
	CreatedAt time.Time `json:"createdAt"`
	// The date of last update of the record.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	KeyExchange string `json:"keyExchange"`
	IkeLifeTime string `json:"ikeLifeTime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	Lifetime string `json:"lifetime" validate:"regexp=^((1[0-9]|[2-9][0-9]|[1-9][0-9]{2,3}|[1-7][0-9]{4}|8[0-5][0-9]{3}|86[0-3][0-9]{2}|86400)s)|(([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|1[0-3][0-9][0-9]|14[0-3][0-9]|1440)m)|(([1-9]|1[0-9]|2[0-4])h)$"`
	DpdDelay string `json:"dpdDelay" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	DpdTimeout string `json:"dpdTimeout" validate:"regexp=^([5-9]|[1-5][0-9]|60)s$"`
	Phase1 IPSecPhaseConfig `json:"phase1"`
	Phase2 IPSecPhaseConfig `json:"phase2"`
	Right string `json:"right"`
	RightID NetworkIpsecBaseAllOfRightID `json:"rightID"`
	Passphrase string `json:"passphrase" validate:"regexp=^[$a-zA-Z1-9_\\/\\\\.][$a-zA-Z0-9_\\/\\\\.]{7,101}$"`
	// dpdAction.
	DpdAction string `json:"dpdAction"`
	LeftSubnets []string `json:"leftSubnets"`
	RightSubnets []string `json:"rightSubnets"`
	HaTunnelID NetworkHaTunnelID `json:"haTunnelID"`
	RightASN ASN `json:"rightASN"`
	RightPrivateIP string `json:"rightPrivateIP"`
	LeftPrivateIP string `json:"leftPrivateIP"`
}

type _NetworkTunnelIpsecRedundant NetworkTunnelIpsecRedundant

// NewNetworkTunnelIpsecRedundant instantiates a new NetworkTunnelIpsecRedundant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkTunnelIpsecRedundant(id string, network string, region string, instance string, interfaceName string, type_ string, isHA bool, tenantId string, createdAt time.Time, keyExchange string, ikeLifeTime string, lifetime string, dpdDelay string, dpdTimeout string, phase1 IPSecPhaseConfig, phase2 IPSecPhaseConfig, right string, rightID NetworkIpsecBaseAllOfRightID, passphrase string, dpdAction string, leftSubnets []string, rightSubnets []string, haTunnelID NetworkHaTunnelID, rightASN ASN, rightPrivateIP string, leftPrivateIP string) *NetworkTunnelIpsecRedundant {
	this := NetworkTunnelIpsecRedundant{}
	this.Id = id
	this.Network = network
	this.Region = region
	this.Instance = instance
	this.InterfaceName = interfaceName
	this.Type = type_
	this.IsHA = isHA
	this.TenantId = tenantId
	this.CreatedAt = createdAt
	this.KeyExchange = keyExchange
	this.IkeLifeTime = ikeLifeTime
	this.Lifetime = lifetime
	this.DpdDelay = dpdDelay
	this.DpdTimeout = dpdTimeout
	this.Phase1 = phase1
	this.Phase2 = phase2
	this.Right = right
	this.RightID = rightID
	this.Passphrase = passphrase
	this.DpdAction = dpdAction
	this.LeftSubnets = leftSubnets
	this.RightSubnets = rightSubnets
	this.HaTunnelID = haTunnelID
	this.RightASN = rightASN
	this.RightPrivateIP = rightPrivateIP
	this.LeftPrivateIP = leftPrivateIP
	return &this
}

// NewNetworkTunnelIpsecRedundantWithDefaults instantiates a new NetworkTunnelIpsecRedundant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkTunnelIpsecRedundantWithDefaults() *NetworkTunnelIpsecRedundant {
	this := NetworkTunnelIpsecRedundant{}
	return &this
}

// GetId returns the Id field value
func (o *NetworkTunnelIpsecRedundant) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkTunnelIpsecRedundant) SetId(v string) {
	o.Id = v
}

// GetNetwork returns the Network field value
func (o *NetworkTunnelIpsecRedundant) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *NetworkTunnelIpsecRedundant) SetNetwork(v string) {
	o.Network = v
}

// GetRegion returns the Region field value
func (o *NetworkTunnelIpsecRedundant) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *NetworkTunnelIpsecRedundant) SetRegion(v string) {
	o.Region = v
}

// GetInstance returns the Instance field value
func (o *NetworkTunnelIpsecRedundant) GetInstance() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetInstanceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instance, true
}

// SetInstance sets field value
func (o *NetworkTunnelIpsecRedundant) SetInstance(v string) {
	o.Instance = v
}

// GetInterfaceName returns the InterfaceName field value
func (o *NetworkTunnelIpsecRedundant) GetInterfaceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InterfaceName
}

// GetInterfaceNameOk returns a tuple with the InterfaceName field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetInterfaceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InterfaceName, true
}

// SetInterfaceName sets field value
func (o *NetworkTunnelIpsecRedundant) SetInterfaceName(v string) {
	o.InterfaceName = v
}

// GetType returns the Type field value
func (o *NetworkTunnelIpsecRedundant) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NetworkTunnelIpsecRedundant) SetType(v string) {
	o.Type = v
}

// GetIsHA returns the IsHA field value
func (o *NetworkTunnelIpsecRedundant) GetIsHA() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsHA
}

// GetIsHAOk returns a tuple with the IsHA field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetIsHAOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsHA, true
}

// SetIsHA sets field value
func (o *NetworkTunnelIpsecRedundant) SetIsHA(v bool) {
	o.IsHA = v
}

// GetTenantId returns the TenantId field value
func (o *NetworkTunnelIpsecRedundant) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *NetworkTunnelIpsecRedundant) SetTenantId(v string) {
	o.TenantId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *NetworkTunnelIpsecRedundant) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *NetworkTunnelIpsecRedundant) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *NetworkTunnelIpsecRedundant) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *NetworkTunnelIpsecRedundant) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *NetworkTunnelIpsecRedundant) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetKeyExchange returns the KeyExchange field value
func (o *NetworkTunnelIpsecRedundant) GetKeyExchange() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyExchange
}

// GetKeyExchangeOk returns a tuple with the KeyExchange field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetKeyExchangeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyExchange, true
}

// SetKeyExchange sets field value
func (o *NetworkTunnelIpsecRedundant) SetKeyExchange(v string) {
	o.KeyExchange = v
}

// GetIkeLifeTime returns the IkeLifeTime field value
func (o *NetworkTunnelIpsecRedundant) GetIkeLifeTime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IkeLifeTime
}

// GetIkeLifeTimeOk returns a tuple with the IkeLifeTime field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetIkeLifeTimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IkeLifeTime, true
}

// SetIkeLifeTime sets field value
func (o *NetworkTunnelIpsecRedundant) SetIkeLifeTime(v string) {
	o.IkeLifeTime = v
}

// GetLifetime returns the Lifetime field value
func (o *NetworkTunnelIpsecRedundant) GetLifetime() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lifetime
}

// GetLifetimeOk returns a tuple with the Lifetime field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetLifetimeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lifetime, true
}

// SetLifetime sets field value
func (o *NetworkTunnelIpsecRedundant) SetLifetime(v string) {
	o.Lifetime = v
}

// GetDpdDelay returns the DpdDelay field value
func (o *NetworkTunnelIpsecRedundant) GetDpdDelay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdDelay
}

// GetDpdDelayOk returns a tuple with the DpdDelay field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetDpdDelayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdDelay, true
}

// SetDpdDelay sets field value
func (o *NetworkTunnelIpsecRedundant) SetDpdDelay(v string) {
	o.DpdDelay = v
}

// GetDpdTimeout returns the DpdTimeout field value
func (o *NetworkTunnelIpsecRedundant) GetDpdTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdTimeout
}

// GetDpdTimeoutOk returns a tuple with the DpdTimeout field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetDpdTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdTimeout, true
}

// SetDpdTimeout sets field value
func (o *NetworkTunnelIpsecRedundant) SetDpdTimeout(v string) {
	o.DpdTimeout = v
}

// GetPhase1 returns the Phase1 field value
func (o *NetworkTunnelIpsecRedundant) GetPhase1() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase1
}

// GetPhase1Ok returns a tuple with the Phase1 field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetPhase1Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase1, true
}

// SetPhase1 sets field value
func (o *NetworkTunnelIpsecRedundant) SetPhase1(v IPSecPhaseConfig) {
	o.Phase1 = v
}

// GetPhase2 returns the Phase2 field value
func (o *NetworkTunnelIpsecRedundant) GetPhase2() IPSecPhaseConfig {
	if o == nil {
		var ret IPSecPhaseConfig
		return ret
	}

	return o.Phase2
}

// GetPhase2Ok returns a tuple with the Phase2 field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetPhase2Ok() (*IPSecPhaseConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phase2, true
}

// SetPhase2 sets field value
func (o *NetworkTunnelIpsecRedundant) SetPhase2(v IPSecPhaseConfig) {
	o.Phase2 = v
}

// GetRight returns the Right field value
func (o *NetworkTunnelIpsecRedundant) GetRight() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Right
}

// GetRightOk returns a tuple with the Right field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRightOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Right, true
}

// SetRight sets field value
func (o *NetworkTunnelIpsecRedundant) SetRight(v string) {
	o.Right = v
}

// GetRightID returns the RightID field value
func (o *NetworkTunnelIpsecRedundant) GetRightID() NetworkIpsecBaseAllOfRightID {
	if o == nil {
		var ret NetworkIpsecBaseAllOfRightID
		return ret
	}

	return o.RightID
}

// GetRightIDOk returns a tuple with the RightID field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRightIDOk() (*NetworkIpsecBaseAllOfRightID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RightID, true
}

// SetRightID sets field value
func (o *NetworkTunnelIpsecRedundant) SetRightID(v NetworkIpsecBaseAllOfRightID) {
	o.RightID = v
}

// GetPassphrase returns the Passphrase field value
func (o *NetworkTunnelIpsecRedundant) GetPassphrase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passphrase
}

// GetPassphraseOk returns a tuple with the Passphrase field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetPassphraseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passphrase, true
}

// SetPassphrase sets field value
func (o *NetworkTunnelIpsecRedundant) SetPassphrase(v string) {
	o.Passphrase = v
}

// GetDpdAction returns the DpdAction field value
func (o *NetworkTunnelIpsecRedundant) GetDpdAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DpdAction
}

// GetDpdActionOk returns a tuple with the DpdAction field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetDpdActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpdAction, true
}

// SetDpdAction sets field value
func (o *NetworkTunnelIpsecRedundant) SetDpdAction(v string) {
	o.DpdAction = v
}

// GetLeftSubnets returns the LeftSubnets field value
func (o *NetworkTunnelIpsecRedundant) GetLeftSubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.LeftSubnets
}

// GetLeftSubnetsOk returns a tuple with the LeftSubnets field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetLeftSubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LeftSubnets, true
}

// SetLeftSubnets sets field value
func (o *NetworkTunnelIpsecRedundant) SetLeftSubnets(v []string) {
	o.LeftSubnets = v
}

// GetRightSubnets returns the RightSubnets field value
func (o *NetworkTunnelIpsecRedundant) GetRightSubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RightSubnets
}

// GetRightSubnetsOk returns a tuple with the RightSubnets field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRightSubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RightSubnets, true
}

// SetRightSubnets sets field value
func (o *NetworkTunnelIpsecRedundant) SetRightSubnets(v []string) {
	o.RightSubnets = v
}

// GetHaTunnelID returns the HaTunnelID field value
func (o *NetworkTunnelIpsecRedundant) GetHaTunnelID() NetworkHaTunnelID {
	if o == nil {
		var ret NetworkHaTunnelID
		return ret
	}

	return o.HaTunnelID
}

// GetHaTunnelIDOk returns a tuple with the HaTunnelID field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetHaTunnelIDOk() (*NetworkHaTunnelID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HaTunnelID, true
}

// SetHaTunnelID sets field value
func (o *NetworkTunnelIpsecRedundant) SetHaTunnelID(v NetworkHaTunnelID) {
	o.HaTunnelID = v
}

// GetRightASN returns the RightASN field value
func (o *NetworkTunnelIpsecRedundant) GetRightASN() ASN {
	if o == nil {
		var ret ASN
		return ret
	}

	return o.RightASN
}

// GetRightASNOk returns a tuple with the RightASN field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRightASNOk() (*ASN, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RightASN, true
}

// SetRightASN sets field value
func (o *NetworkTunnelIpsecRedundant) SetRightASN(v ASN) {
	o.RightASN = v
}

// GetRightPrivateIP returns the RightPrivateIP field value
func (o *NetworkTunnelIpsecRedundant) GetRightPrivateIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RightPrivateIP
}

// GetRightPrivateIPOk returns a tuple with the RightPrivateIP field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetRightPrivateIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RightPrivateIP, true
}

// SetRightPrivateIP sets field value
func (o *NetworkTunnelIpsecRedundant) SetRightPrivateIP(v string) {
	o.RightPrivateIP = v
}

// GetLeftPrivateIP returns the LeftPrivateIP field value
func (o *NetworkTunnelIpsecRedundant) GetLeftPrivateIP() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeftPrivateIP
}

// GetLeftPrivateIPOk returns a tuple with the LeftPrivateIP field value
// and a boolean to check if the value has been set.
func (o *NetworkTunnelIpsecRedundant) GetLeftPrivateIPOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeftPrivateIP, true
}

// SetLeftPrivateIP sets field value
func (o *NetworkTunnelIpsecRedundant) SetLeftPrivateIP(v string) {
	o.LeftPrivateIP = v
}

func (o NetworkTunnelIpsecRedundant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkTunnelIpsecRedundant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["network"] = o.Network
	toSerialize["region"] = o.Region
	toSerialize["instance"] = o.Instance
	toSerialize["interfaceName"] = o.InterfaceName
	toSerialize["type"] = o.Type
	toSerialize["isHA"] = o.IsHA
	toSerialize["tenantId"] = o.TenantId
	toSerialize["createdAt"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	toSerialize["keyExchange"] = o.KeyExchange
	toSerialize["ikeLifeTime"] = o.IkeLifeTime
	toSerialize["lifetime"] = o.Lifetime
	toSerialize["dpdDelay"] = o.DpdDelay
	toSerialize["dpdTimeout"] = o.DpdTimeout
	toSerialize["phase1"] = o.Phase1
	toSerialize["phase2"] = o.Phase2
	toSerialize["right"] = o.Right
	toSerialize["rightID"] = o.RightID
	toSerialize["passphrase"] = o.Passphrase
	toSerialize["dpdAction"] = o.DpdAction
	toSerialize["leftSubnets"] = o.LeftSubnets
	toSerialize["rightSubnets"] = o.RightSubnets
	toSerialize["haTunnelID"] = o.HaTunnelID
	toSerialize["rightASN"] = o.RightASN
	toSerialize["rightPrivateIP"] = o.RightPrivateIP
	toSerialize["leftPrivateIP"] = o.LeftPrivateIP
	return toSerialize, nil
}

func (o *NetworkTunnelIpsecRedundant) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"network",
		"region",
		"instance",
		"interfaceName",
		"type",
		"isHA",
		"tenantId",
		"createdAt",
		"keyExchange",
		"ikeLifeTime",
		"lifetime",
		"dpdDelay",
		"dpdTimeout",
		"phase1",
		"phase2",
		"right",
		"rightID",
		"passphrase",
		"dpdAction",
		"leftSubnets",
		"rightSubnets",
		"haTunnelID",
		"rightASN",
		"rightPrivateIP",
		"leftPrivateIP",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkTunnelIpsecRedundant := _NetworkTunnelIpsecRedundant{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworkTunnelIpsecRedundant)

	if err != nil {
		return err
	}

	*o = NetworkTunnelIpsecRedundant(varNetworkTunnelIpsecRedundant)

	return err
}

type NullableNetworkTunnelIpsecRedundant struct {
	value *NetworkTunnelIpsecRedundant
	isSet bool
}

func (v NullableNetworkTunnelIpsecRedundant) Get() *NetworkTunnelIpsecRedundant {
	return v.value
}

func (v *NullableNetworkTunnelIpsecRedundant) Set(val *NetworkTunnelIpsecRedundant) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkTunnelIpsecRedundant) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkTunnelIpsecRedundant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkTunnelIpsecRedundant(val *NetworkTunnelIpsecRedundant) *NullableNetworkTunnelIpsecRedundant {
	return &NullableNetworkTunnelIpsecRedundant{value: val, isSet: true}
}

func (v NullableNetworkTunnelIpsecRedundant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkTunnelIpsecRedundant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


