/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnhancedIPSecSharedSettingsCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnhancedIPSecSharedSettingsCreate{}

// EnhancedIPSecSharedSettingsCreate struct for EnhancedIPSecSharedSettingsCreate
type EnhancedIPSecSharedSettingsCreate struct {
	P81GatewaySubnets []string `json:"p81GatewaySubnets"`
	RemoteGatewaySubnets []string `json:"remoteGatewaySubnets"`
	// Expected peak throughput of the tunnel communication in Mbps. Typical connection will be of 1000Mbps.
	PeakBandwidth *int32 `json:"peakBandwidth,omitempty"`
	P81ASN *RemoteASN `json:"p81ASN,omitempty"`
	Features NetworkFeaturesCreate `json:"features"`
	LeftASN RemoteASN `json:"leftASN"`
}

type _EnhancedIPSecSharedSettingsCreate EnhancedIPSecSharedSettingsCreate

// NewEnhancedIPSecSharedSettingsCreate instantiates a new EnhancedIPSecSharedSettingsCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnhancedIPSecSharedSettingsCreate(p81GatewaySubnets []string, remoteGatewaySubnets []string, features NetworkFeaturesCreate, leftASN RemoteASN) *EnhancedIPSecSharedSettingsCreate {
	this := EnhancedIPSecSharedSettingsCreate{}
	this.P81GatewaySubnets = p81GatewaySubnets
	this.RemoteGatewaySubnets = remoteGatewaySubnets
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	this.Features = features
	this.LeftASN = leftASN
	return &this
}

// NewEnhancedIPSecSharedSettingsCreateWithDefaults instantiates a new EnhancedIPSecSharedSettingsCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnhancedIPSecSharedSettingsCreateWithDefaults() *EnhancedIPSecSharedSettingsCreate {
	this := EnhancedIPSecSharedSettingsCreate{}
	var peakBandwidth int32 = 1000
	this.PeakBandwidth = &peakBandwidth
	return &this
}

// GetP81GatewaySubnets returns the P81GatewaySubnets field value
func (o *EnhancedIPSecSharedSettingsCreate) GetP81GatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.P81GatewaySubnets
}

// GetP81GatewaySubnetsOk returns a tuple with the P81GatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetP81GatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.P81GatewaySubnets, true
}

// SetP81GatewaySubnets sets field value
func (o *EnhancedIPSecSharedSettingsCreate) SetP81GatewaySubnets(v []string) {
	o.P81GatewaySubnets = v
}

// GetRemoteGatewaySubnets returns the RemoteGatewaySubnets field value
func (o *EnhancedIPSecSharedSettingsCreate) GetRemoteGatewaySubnets() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RemoteGatewaySubnets
}

// GetRemoteGatewaySubnetsOk returns a tuple with the RemoteGatewaySubnets field value
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetRemoteGatewaySubnetsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoteGatewaySubnets, true
}

// SetRemoteGatewaySubnets sets field value
func (o *EnhancedIPSecSharedSettingsCreate) SetRemoteGatewaySubnets(v []string) {
	o.RemoteGatewaySubnets = v
}

// GetPeakBandwidth returns the PeakBandwidth field value if set, zero value otherwise.
func (o *EnhancedIPSecSharedSettingsCreate) GetPeakBandwidth() int32 {
	if o == nil || IsNil(o.PeakBandwidth) {
		var ret int32
		return ret
	}
	return *o.PeakBandwidth
}

// GetPeakBandwidthOk returns a tuple with the PeakBandwidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetPeakBandwidthOk() (*int32, bool) {
	if o == nil || IsNil(o.PeakBandwidth) {
		return nil, false
	}
	return o.PeakBandwidth, true
}

// HasPeakBandwidth returns a boolean if a field has been set.
func (o *EnhancedIPSecSharedSettingsCreate) HasPeakBandwidth() bool {
	if o != nil && !IsNil(o.PeakBandwidth) {
		return true
	}

	return false
}

// SetPeakBandwidth gets a reference to the given int32 and assigns it to the PeakBandwidth field.
func (o *EnhancedIPSecSharedSettingsCreate) SetPeakBandwidth(v int32) {
	o.PeakBandwidth = &v
}

// GetP81ASN returns the P81ASN field value if set, zero value otherwise.
func (o *EnhancedIPSecSharedSettingsCreate) GetP81ASN() RemoteASN {
	if o == nil || IsNil(o.P81ASN) {
		var ret RemoteASN
		return ret
	}
	return *o.P81ASN
}

// GetP81ASNOk returns a tuple with the P81ASN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetP81ASNOk() (*RemoteASN, bool) {
	if o == nil || IsNil(o.P81ASN) {
		return nil, false
	}
	return o.P81ASN, true
}

// HasP81ASN returns a boolean if a field has been set.
func (o *EnhancedIPSecSharedSettingsCreate) HasP81ASN() bool {
	if o != nil && !IsNil(o.P81ASN) {
		return true
	}

	return false
}

// SetP81ASN gets a reference to the given RemoteASN and assigns it to the P81ASN field.
func (o *EnhancedIPSecSharedSettingsCreate) SetP81ASN(v RemoteASN) {
	o.P81ASN = &v
}

// GetFeatures returns the Features field value
func (o *EnhancedIPSecSharedSettingsCreate) GetFeatures() NetworkFeaturesCreate {
	if o == nil {
		var ret NetworkFeaturesCreate
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetFeaturesOk() (*NetworkFeaturesCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *EnhancedIPSecSharedSettingsCreate) SetFeatures(v NetworkFeaturesCreate) {
	o.Features = v
}

// GetLeftASN returns the LeftASN field value
func (o *EnhancedIPSecSharedSettingsCreate) GetLeftASN() RemoteASN {
	if o == nil {
		var ret RemoteASN
		return ret
	}

	return o.LeftASN
}

// GetLeftASNOk returns a tuple with the LeftASN field value
// and a boolean to check if the value has been set.
func (o *EnhancedIPSecSharedSettingsCreate) GetLeftASNOk() (*RemoteASN, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeftASN, true
}

// SetLeftASN sets field value
func (o *EnhancedIPSecSharedSettingsCreate) SetLeftASN(v RemoteASN) {
	o.LeftASN = v
}

func (o EnhancedIPSecSharedSettingsCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnhancedIPSecSharedSettingsCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["p81GatewaySubnets"] = o.P81GatewaySubnets
	toSerialize["remoteGatewaySubnets"] = o.RemoteGatewaySubnets
	if !IsNil(o.PeakBandwidth) {
		toSerialize["peakBandwidth"] = o.PeakBandwidth
	}
	if !IsNil(o.P81ASN) {
		toSerialize["p81ASN"] = o.P81ASN
	}
	toSerialize["features"] = o.Features
	toSerialize["leftASN"] = o.LeftASN
	return toSerialize, nil
}

func (o *EnhancedIPSecSharedSettingsCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"p81GatewaySubnets",
		"remoteGatewaySubnets",
		"features",
		"leftASN",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnhancedIPSecSharedSettingsCreate := _EnhancedIPSecSharedSettingsCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnhancedIPSecSharedSettingsCreate)

	if err != nil {
		return err
	}

	*o = EnhancedIPSecSharedSettingsCreate(varEnhancedIPSecSharedSettingsCreate)

	return err
}

type NullableEnhancedIPSecSharedSettingsCreate struct {
	value *EnhancedIPSecSharedSettingsCreate
	isSet bool
}

func (v NullableEnhancedIPSecSharedSettingsCreate) Get() *EnhancedIPSecSharedSettingsCreate {
	return v.value
}

func (v *NullableEnhancedIPSecSharedSettingsCreate) Set(val *EnhancedIPSecSharedSettingsCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableEnhancedIPSecSharedSettingsCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableEnhancedIPSecSharedSettingsCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnhancedIPSecSharedSettingsCreate(val *EnhancedIPSecSharedSettingsCreate) *NullableEnhancedIPSecSharedSettingsCreate {
	return &NullableEnhancedIPSecSharedSettingsCreate{value: val, isSet: true}
}

func (v NullableEnhancedIPSecSharedSettingsCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnhancedIPSecSharedSettingsCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


