/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommonCreateApplicationOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonCreateApplicationOneOf1{}

// CommonCreateApplicationOneOf1 struct for CommonCreateApplicationOneOf1
type CommonCreateApplicationOneOf1 struct {
	Groups []string `json:"groups"`
}

type _CommonCreateApplicationOneOf1 CommonCreateApplicationOneOf1

// NewCommonCreateApplicationOneOf1 instantiates a new CommonCreateApplicationOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonCreateApplicationOneOf1(groups []string) *CommonCreateApplicationOneOf1 {
	this := CommonCreateApplicationOneOf1{}
	this.Groups = groups
	return &this
}

// NewCommonCreateApplicationOneOf1WithDefaults instantiates a new CommonCreateApplicationOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonCreateApplicationOneOf1WithDefaults() *CommonCreateApplicationOneOf1 {
	this := CommonCreateApplicationOneOf1{}
	return &this
}

// GetGroups returns the Groups field value
func (o *CommonCreateApplicationOneOf1) GetGroups() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value
// and a boolean to check if the value has been set.
func (o *CommonCreateApplicationOneOf1) GetGroupsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Groups, true
}

// SetGroups sets field value
func (o *CommonCreateApplicationOneOf1) SetGroups(v []string) {
	o.Groups = v
}

func (o CommonCreateApplicationOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonCreateApplicationOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groups"] = o.Groups
	return toSerialize, nil
}

func (o *CommonCreateApplicationOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonCreateApplicationOneOf1 := _CommonCreateApplicationOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varCommonCreateApplicationOneOf1)

	if err != nil {
		return err
	}

	*o = CommonCreateApplicationOneOf1(varCommonCreateApplicationOneOf1)

	return err
}

type NullableCommonCreateApplicationOneOf1 struct {
	value *CommonCreateApplicationOneOf1
	isSet bool
}

func (v NullableCommonCreateApplicationOneOf1) Get() *CommonCreateApplicationOneOf1 {
	return v.value
}

func (v *NullableCommonCreateApplicationOneOf1) Set(val *CommonCreateApplicationOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonCreateApplicationOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonCreateApplicationOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonCreateApplicationOneOf1(val *CommonCreateApplicationOneOf1) *NullableCommonCreateApplicationOneOf1 {
	return &NullableCommonCreateApplicationOneOf1{value: val, isSet: true}
}

func (v NullableCommonCreateApplicationOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonCreateApplicationOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


