/*
 * Perimeter81 Public API
 *
 * The YAML for Preimeter81 Public API.
 *
 * API version: 1.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package perimeter81sdk

type ObjectsAddressObj struct {
	ValueType   string   `json:"valueType"`
	IpVersion   string   `json:"ipVersion"`
	Value       []string `json:"value"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
}
