/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// SourcesAndDestinations - struct for SourcesAndDestinations
type SourcesAndDestinations struct {
	Addresses *Addresses
	UsersAndGroups *UsersAndGroups
}

// AddressesAsSourcesAndDestinations is a convenience function that returns Addresses wrapped in SourcesAndDestinations
func AddressesAsSourcesAndDestinations(v *Addresses) SourcesAndDestinations {
	return SourcesAndDestinations{
		Addresses: v,
	}
}

// UsersAndGroupsAsSourcesAndDestinations is a convenience function that returns UsersAndGroups wrapped in SourcesAndDestinations
func UsersAndGroupsAsSourcesAndDestinations(v *UsersAndGroups) SourcesAndDestinations {
	return SourcesAndDestinations{
		UsersAndGroups: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SourcesAndDestinations) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Addresses
	err = newStrictDecoder(data).Decode(&dst.Addresses)
	if err == nil {
		jsonAddresses, _ := json.Marshal(dst.Addresses)
		if string(jsonAddresses) == "{}" { // empty struct
			dst.Addresses = nil
		} else {
			if err = validator.Validate(dst.Addresses); err != nil {
				dst.Addresses = nil
			} else {
				match++
			}
		}
	} else {
		dst.Addresses = nil
	}

	// try to unmarshal data into UsersAndGroups
	err = newStrictDecoder(data).Decode(&dst.UsersAndGroups)
	if err == nil {
		jsonUsersAndGroups, _ := json.Marshal(dst.UsersAndGroups)
		if string(jsonUsersAndGroups) == "{}" { // empty struct
			dst.UsersAndGroups = nil
		} else {
			if err = validator.Validate(dst.UsersAndGroups); err != nil {
				dst.UsersAndGroups = nil
			} else {
				match++
			}
		}
	} else {
		dst.UsersAndGroups = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Addresses = nil
		dst.UsersAndGroups = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SourcesAndDestinations)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SourcesAndDestinations)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SourcesAndDestinations) MarshalJSON() ([]byte, error) {
	if src.Addresses != nil {
		return json.Marshal(&src.Addresses)
	}

	if src.UsersAndGroups != nil {
		return json.Marshal(&src.UsersAndGroups)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SourcesAndDestinations) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Addresses != nil {
		return obj.Addresses
	}

	if obj.UsersAndGroups != nil {
		return obj.UsersAndGroups
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SourcesAndDestinations) GetActualInstanceValue() (interface{}) {
	if obj.Addresses != nil {
		return *obj.Addresses
	}

	if obj.UsersAndGroups != nil {
		return *obj.UsersAndGroups
	}

	// all schemas are nil
	return nil
}

type NullableSourcesAndDestinations struct {
	value *SourcesAndDestinations
	isSet bool
}

func (v NullableSourcesAndDestinations) Get() *SourcesAndDestinations {
	return v.value
}

func (v *NullableSourcesAndDestinations) Set(val *SourcesAndDestinations) {
	v.value = val
	v.isSet = true
}

func (v NullableSourcesAndDestinations) IsSet() bool {
	return v.isSet
}

func (v *NullableSourcesAndDestinations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourcesAndDestinations(val *SourcesAndDestinations) *NullableSourcesAndDestinations {
	return &NullableSourcesAndDestinations{value: val, isSet: true}
}

func (v NullableSourcesAndDestinations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourcesAndDestinations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


