/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectsServicesRequestObj type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectsServicesRequestObj{}

// ObjectsServicesRequestObj struct for ObjectsServicesRequestObj
type ObjectsServicesRequestObj struct {
	// The name of the Objects
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9_ ]+$"`
	Description *string `json:"description,omitempty"`
	Protocols []ObjectsServicesProtocolRequestObj `json:"protocols"`
}

type _ObjectsServicesRequestObj ObjectsServicesRequestObj

// NewObjectsServicesRequestObj instantiates a new ObjectsServicesRequestObj object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectsServicesRequestObj(name string, protocols []ObjectsServicesProtocolRequestObj) *ObjectsServicesRequestObj {
	this := ObjectsServicesRequestObj{}
	this.Name = name
	this.Protocols = protocols
	return &this
}

// NewObjectsServicesRequestObjWithDefaults instantiates a new ObjectsServicesRequestObj object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectsServicesRequestObjWithDefaults() *ObjectsServicesRequestObj {
	this := ObjectsServicesRequestObj{}
	return &this
}

// GetName returns the Name field value
func (o *ObjectsServicesRequestObj) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesRequestObj) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectsServicesRequestObj) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ObjectsServicesRequestObj) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectsServicesRequestObj) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ObjectsServicesRequestObj) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ObjectsServicesRequestObj) SetDescription(v string) {
	o.Description = &v
}

// GetProtocols returns the Protocols field value
func (o *ObjectsServicesRequestObj) GetProtocols() []ObjectsServicesProtocolRequestObj {
	if o == nil {
		var ret []ObjectsServicesProtocolRequestObj
		return ret
	}

	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesRequestObj) GetProtocolsOk() ([]ObjectsServicesProtocolRequestObj, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocols, true
}

// SetProtocols sets field value
func (o *ObjectsServicesRequestObj) SetProtocols(v []ObjectsServicesProtocolRequestObj) {
	o.Protocols = v
}

func (o ObjectsServicesRequestObj) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectsServicesRequestObj) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["protocols"] = o.Protocols
	return toSerialize, nil
}

func (o *ObjectsServicesRequestObj) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"protocols",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectsServicesRequestObj := _ObjectsServicesRequestObj{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varObjectsServicesRequestObj)

	if err != nil {
		return err
	}

	*o = ObjectsServicesRequestObj(varObjectsServicesRequestObj)

	return err
}

type NullableObjectsServicesRequestObj struct {
	value *ObjectsServicesRequestObj
	isSet bool
}

func (v NullableObjectsServicesRequestObj) Get() *ObjectsServicesRequestObj {
	return v.value
}

func (v *NullableObjectsServicesRequestObj) Set(val *ObjectsServicesRequestObj) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectsServicesRequestObj) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectsServicesRequestObj) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectsServicesRequestObj(val *ObjectsServicesRequestObj) *NullableObjectsServicesRequestObj {
	return &NullableObjectsServicesRequestObj{value: val, isSet: true}
}

func (v NullableObjectsServicesRequestObj) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectsServicesRequestObj) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


