/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
)

// checks if the HttpAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HttpAttributes{}

// HttpAttributes HTTP Application attributes
type HttpAttributes struct {
	CheckStatus *int32 `json:"checkStatus,omitempty"`
	CheckPath *string `json:"checkPath,omitempty"`
	StartRelativePath *string `json:"startRelativePath,omitempty" validate:"regexp=^$|^\\/[\\\\w\\\\d-._~!$&'()*+,;=:@\\/?#%]+$"`
}

// NewHttpAttributes instantiates a new HttpAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHttpAttributes() *HttpAttributes {
	this := HttpAttributes{}
	var checkStatus int32 = 200
	this.CheckStatus = &checkStatus
	var checkPath string = ""
	this.CheckPath = &checkPath
	var startRelativePath string = ""
	this.StartRelativePath = &startRelativePath
	return &this
}

// NewHttpAttributesWithDefaults instantiates a new HttpAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHttpAttributesWithDefaults() *HttpAttributes {
	this := HttpAttributes{}
	var checkStatus int32 = 200
	this.CheckStatus = &checkStatus
	var checkPath string = ""
	this.CheckPath = &checkPath
	var startRelativePath string = ""
	this.StartRelativePath = &startRelativePath
	return &this
}

// GetCheckStatus returns the CheckStatus field value if set, zero value otherwise.
func (o *HttpAttributes) GetCheckStatus() int32 {
	if o == nil || IsNil(o.CheckStatus) {
		var ret int32
		return ret
	}
	return *o.CheckStatus
}

// GetCheckStatusOk returns a tuple with the CheckStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpAttributes) GetCheckStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.CheckStatus) {
		return nil, false
	}
	return o.CheckStatus, true
}

// HasCheckStatus returns a boolean if a field has been set.
func (o *HttpAttributes) HasCheckStatus() bool {
	if o != nil && !IsNil(o.CheckStatus) {
		return true
	}

	return false
}

// SetCheckStatus gets a reference to the given int32 and assigns it to the CheckStatus field.
func (o *HttpAttributes) SetCheckStatus(v int32) {
	o.CheckStatus = &v
}

// GetCheckPath returns the CheckPath field value if set, zero value otherwise.
func (o *HttpAttributes) GetCheckPath() string {
	if o == nil || IsNil(o.CheckPath) {
		var ret string
		return ret
	}
	return *o.CheckPath
}

// GetCheckPathOk returns a tuple with the CheckPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpAttributes) GetCheckPathOk() (*string, bool) {
	if o == nil || IsNil(o.CheckPath) {
		return nil, false
	}
	return o.CheckPath, true
}

// HasCheckPath returns a boolean if a field has been set.
func (o *HttpAttributes) HasCheckPath() bool {
	if o != nil && !IsNil(o.CheckPath) {
		return true
	}

	return false
}

// SetCheckPath gets a reference to the given string and assigns it to the CheckPath field.
func (o *HttpAttributes) SetCheckPath(v string) {
	o.CheckPath = &v
}

// GetStartRelativePath returns the StartRelativePath field value if set, zero value otherwise.
func (o *HttpAttributes) GetStartRelativePath() string {
	if o == nil || IsNil(o.StartRelativePath) {
		var ret string
		return ret
	}
	return *o.StartRelativePath
}

// GetStartRelativePathOk returns a tuple with the StartRelativePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HttpAttributes) GetStartRelativePathOk() (*string, bool) {
	if o == nil || IsNil(o.StartRelativePath) {
		return nil, false
	}
	return o.StartRelativePath, true
}

// HasStartRelativePath returns a boolean if a field has been set.
func (o *HttpAttributes) HasStartRelativePath() bool {
	if o != nil && !IsNil(o.StartRelativePath) {
		return true
	}

	return false
}

// SetStartRelativePath gets a reference to the given string and assigns it to the StartRelativePath field.
func (o *HttpAttributes) SetStartRelativePath(v string) {
	o.StartRelativePath = &v
}

func (o HttpAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HttpAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckStatus) {
		toSerialize["checkStatus"] = o.CheckStatus
	}
	if !IsNil(o.CheckPath) {
		toSerialize["checkPath"] = o.CheckPath
	}
	if !IsNil(o.StartRelativePath) {
		toSerialize["startRelativePath"] = o.StartRelativePath
	}
	return toSerialize, nil
}

type NullableHttpAttributes struct {
	value *HttpAttributes
	isSet bool
}

func (v NullableHttpAttributes) Get() *HttpAttributes {
	return v.value
}

func (v *NullableHttpAttributes) Set(val *HttpAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableHttpAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableHttpAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHttpAttributes(val *HttpAttributes) *NullableHttpAttributes {
	return &NullableHttpAttributes{value: val, isSet: true}
}

func (v NullableHttpAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHttpAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


