/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostObjectsServices201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostObjectsServices201Response{}

// PostObjectsServices201Response struct for PostObjectsServices201Response
type PostObjectsServices201Response struct {
	// The name of the Objects
	Name string `json:"name" validate:"regexp=^[a-zA-Z0-9_ ]+$"`
	Description *string `json:"description,omitempty"`
	Protocols []ObjectsServicesProtocolResponseObj `json:"protocols"`
	Id *string `json:"id,omitempty"`
}

type _PostObjectsServices201Response PostObjectsServices201Response

// NewPostObjectsServices201Response instantiates a new PostObjectsServices201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostObjectsServices201Response(name string, protocols []ObjectsServicesProtocolResponseObj) *PostObjectsServices201Response {
	this := PostObjectsServices201Response{}
	this.Name = name
	this.Protocols = protocols
	return &this
}

// NewPostObjectsServices201ResponseWithDefaults instantiates a new PostObjectsServices201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostObjectsServices201ResponseWithDefaults() *PostObjectsServices201Response {
	this := PostObjectsServices201Response{}
	return &this
}

// GetName returns the Name field value
func (o *PostObjectsServices201Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PostObjectsServices201Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PostObjectsServices201Response) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PostObjectsServices201Response) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostObjectsServices201Response) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PostObjectsServices201Response) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PostObjectsServices201Response) SetDescription(v string) {
	o.Description = &v
}

// GetProtocols returns the Protocols field value
func (o *PostObjectsServices201Response) GetProtocols() []ObjectsServicesProtocolResponseObj {
	if o == nil {
		var ret []ObjectsServicesProtocolResponseObj
		return ret
	}

	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value
// and a boolean to check if the value has been set.
func (o *PostObjectsServices201Response) GetProtocolsOk() ([]ObjectsServicesProtocolResponseObj, bool) {
	if o == nil {
		return nil, false
	}
	return o.Protocols, true
}

// SetProtocols sets field value
func (o *PostObjectsServices201Response) SetProtocols(v []ObjectsServicesProtocolResponseObj) {
	o.Protocols = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PostObjectsServices201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostObjectsServices201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PostObjectsServices201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PostObjectsServices201Response) SetId(v string) {
	o.Id = &v
}

func (o PostObjectsServices201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostObjectsServices201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["protocols"] = o.Protocols
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

func (o *PostObjectsServices201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"protocols",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostObjectsServices201Response := _PostObjectsServices201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostObjectsServices201Response)

	if err != nil {
		return err
	}

	*o = PostObjectsServices201Response(varPostObjectsServices201Response)

	return err
}

type NullablePostObjectsServices201Response struct {
	value *PostObjectsServices201Response
	isSet bool
}

func (v NullablePostObjectsServices201Response) Get() *PostObjectsServices201Response {
	return v.value
}

func (v *NullablePostObjectsServices201Response) Set(val *PostObjectsServices201Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostObjectsServices201Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostObjectsServices201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostObjectsServices201Response(val *PostObjectsServices201Response) *NullablePostObjectsServices201Response {
	return &NullablePostObjectsServices201Response{value: val, isSet: true}
}

func (v NullablePostObjectsServices201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostObjectsServices201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


