/*
Harmony SASE Public API

The YAML for Harmony SASE Public API. 

API version: 2.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package perimeter81sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectsServicesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectsServicesResponse{}

// ObjectsServicesResponse struct for ObjectsServicesResponse
type ObjectsServicesResponse struct {
	Page float32 `json:"page"`
	TotalPage float32 `json:"totalPage"`
	ItemsTotal float32 `json:"itemsTotal"`
	Data []ObjectsServicesResponseObj `json:"data"`
}

type _ObjectsServicesResponse ObjectsServicesResponse

// NewObjectsServicesResponse instantiates a new ObjectsServicesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectsServicesResponse(page float32, totalPage float32, itemsTotal float32, data []ObjectsServicesResponseObj) *ObjectsServicesResponse {
	this := ObjectsServicesResponse{}
	this.Page = page
	this.TotalPage = totalPage
	this.ItemsTotal = itemsTotal
	this.Data = data
	return &this
}

// NewObjectsServicesResponseWithDefaults instantiates a new ObjectsServicesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectsServicesResponseWithDefaults() *ObjectsServicesResponse {
	this := ObjectsServicesResponse{}
	return &this
}

// GetPage returns the Page field value
func (o *ObjectsServicesResponse) GetPage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesResponse) GetPageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ObjectsServicesResponse) SetPage(v float32) {
	o.Page = v
}

// GetTotalPage returns the TotalPage field value
func (o *ObjectsServicesResponse) GetTotalPage() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPage
}

// GetTotalPageOk returns a tuple with the TotalPage field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesResponse) GetTotalPageOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPage, true
}

// SetTotalPage sets field value
func (o *ObjectsServicesResponse) SetTotalPage(v float32) {
	o.TotalPage = v
}

// GetItemsTotal returns the ItemsTotal field value
func (o *ObjectsServicesResponse) GetItemsTotal() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ItemsTotal
}

// GetItemsTotalOk returns a tuple with the ItemsTotal field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesResponse) GetItemsTotalOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ItemsTotal, true
}

// SetItemsTotal sets field value
func (o *ObjectsServicesResponse) SetItemsTotal(v float32) {
	o.ItemsTotal = v
}

// GetData returns the Data field value
func (o *ObjectsServicesResponse) GetData() []ObjectsServicesResponseObj {
	if o == nil {
		var ret []ObjectsServicesResponseObj
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ObjectsServicesResponse) GetDataOk() ([]ObjectsServicesResponseObj, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ObjectsServicesResponse) SetData(v []ObjectsServicesResponseObj) {
	o.Data = v
}

func (o ObjectsServicesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectsServicesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["totalPage"] = o.TotalPage
	toSerialize["itemsTotal"] = o.ItemsTotal
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ObjectsServicesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"totalPage",
		"itemsTotal",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectsServicesResponse := _ObjectsServicesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectsServicesResponse)

	if err != nil {
		return err
	}

	*o = ObjectsServicesResponse(varObjectsServicesResponse)

	return err
}

type NullableObjectsServicesResponse struct {
	value *ObjectsServicesResponse
	isSet bool
}

func (v NullableObjectsServicesResponse) Get() *ObjectsServicesResponse {
	return v.value
}

func (v *NullableObjectsServicesResponse) Set(val *ObjectsServicesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectsServicesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectsServicesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectsServicesResponse(val *ObjectsServicesResponse) *NullableObjectsServicesResponse {
	return &NullableObjectsServicesResponse{value: val, isSet: true}
}

func (v NullableObjectsServicesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectsServicesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


